// flow-typed signature: 37cb0430f0d6e006290c27b384bed901
// flow-typed version: <<STUB>>/react-native-image-picker_v4.7.3/flow_v0.162.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-image-picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "vision-camera-plugin-inatvision" {
  declare module.exports: any;
}
