export default ( {
  API_URL: process.env.API_URL,
  OAUTH_API_URL: process.env.OAUTH_API_URL,
  JWT_ANONYMOUS_API_SECRET: process.env.JWT_ANONYMOUS_API_SECRET,
  IOS_OAUTH_CLIENT_ID: process.env.IOS_OAUTH_CLIENT_ID,
  IOS_OAUTH_CLIENT_SECRET: process.env.IOS_OAUTH_CLIENT_SECRET,
  ANDROID_OAUTH_CLIENT_ID: process.env.ANDROID_OAUTH_CLIENT_ID,
  ANDROID_OAUTH_CLIENT_SECRET: process.env.ANDROID_OAUTH_CLIENT_SECRET,
} );
