# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build of iNaturalistReactNative to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "iNaturalistReactNative.xcodeproj")
    build_app(workspace: "iNaturalistReactNative.xcworkspace", scheme: "iNaturalistReactNative")
    upload_to_testflight
    slack(
      message: "iNaturalistReactNative iOS beta successfully deployed!",
      success: true,
      slack_url: ENV["SLACK_WEBHOOK"],
      default_payloads: [:lane, :test_result, :git_branch, :last_git_commit_hash],
      attachment_properties: {
           fields: [
               {
                  title: "Version",
                  value: lane_context[SharedValues::LATEST_VERSION]
               },
               {
                 title: "Build",
                 value: lane_context[SharedValues::LATEST_BUILD_NUMBER]
               }
           ]
       })
  end
end
