/* eslint-disable max-len */
// flow-typed signature: ab773cd5d3948cf68e6729ed92add6ba
// flow-typed version: <<STUB>>/@tanstack/react-query_v5.28.14/flow_v0.182.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tanstack/react-query'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@tanstack/react-query" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@tanstack/react-query/build/codemods/coverage/block-navigation" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/codemods/coverage/prettify" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/codemods/coverage/sorter" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/codemods/src/utils" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/codemods/src/utils/transformers/query-cache-transformer" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/codemods/src/utils/transformers/query-client-transformer" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/codemods/src/utils/transformers/use-query-like-transformer" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/codemods/src/v4/key-transformation" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/codemods/src/v4/replace-import-specifier" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/codemods/src/v4/utils/replacers/key-replacer" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/codemods/src/v5/is-loading/is-loading" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/codemods/src/v5/keep-previous-data/keep-previous-data" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/codemods/src/v5/keep-previous-data/utils/already-has-placeholder-data-property" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/codemods/src/v5/remove-overloads/remove-overloads" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/codemods/src/v5/remove-overloads/transformers/filter-aware-usage-transformer" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/codemods/src/v5/remove-overloads/transformers/query-fn-aware-usage-transformer" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/codemods/src/v5/remove-overloads/utils" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/codemods/src/v5/remove-overloads/utils/unknown-usage-error" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/codemods/src/v5/rename-hydrate/rename-hydrate" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/codemods/src/v5/rename-properties/rename-properties" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/legacy/errorBoundaryUtils" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/legacy/HydrationBoundary" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/legacy" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/legacy/infiniteQueryOptions" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/legacy/isRestoring" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/legacy/QueryClientProvider" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/legacy/QueryErrorResetBoundary" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/legacy/queryOptions" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/legacy/suspense" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/legacy/types" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/legacy/useBaseQuery" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/legacy/useInfiniteQuery" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/legacy/useIsFetching" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/legacy/useMutation" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/legacy/useMutationState" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/legacy/useQueries" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/legacy/useQuery" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/legacy/useSuspenseInfiniteQuery" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/legacy/useSuspenseQueries" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/legacy/useSuspenseQuery" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/legacy/utils" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/modern/errorBoundaryUtils" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/modern/HydrationBoundary" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/modern" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/modern/infiniteQueryOptions" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/modern/isRestoring" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/modern/QueryClientProvider" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/modern/QueryErrorResetBoundary" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/modern/queryOptions" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/modern/suspense" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/modern/types" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/modern/useBaseQuery" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/modern/useInfiniteQuery" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/modern/useIsFetching" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/modern/useMutation" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/modern/useMutationState" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/modern/useQueries" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/modern/useQuery" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/modern/useSuspenseInfiniteQuery" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/modern/useSuspenseQueries" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/modern/useSuspenseQuery" {
  declare module.exports: any;
}

declare module "@tanstack/react-query/build/modern/utils" {
  declare module.exports: any;
}

// Filename aliases
declare module "@tanstack/react-query/build/codemods/coverage/block-navigation.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/codemods/coverage/block-navigation'>;
}
declare module "@tanstack/react-query/build/codemods/coverage/prettify.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/codemods/coverage/prettify'>;
}
declare module "@tanstack/react-query/build/codemods/coverage/sorter.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/codemods/coverage/sorter'>;
}
declare module "@tanstack/react-query/build/codemods/src/utils/index" {
  declare module.exports: $Exports<'@tanstack/react-query/build/codemods/src/utils'>;
}
declare module "@tanstack/react-query/build/codemods/src/utils/index.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/codemods/src/utils'>;
}
declare module "@tanstack/react-query/build/codemods/src/utils/transformers/query-cache-transformer.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/codemods/src/utils/transformers/query-cache-transformer'>;
}
declare module "@tanstack/react-query/build/codemods/src/utils/transformers/query-client-transformer.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/codemods/src/utils/transformers/query-client-transformer'>;
}
declare module "@tanstack/react-query/build/codemods/src/utils/transformers/use-query-like-transformer.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/codemods/src/utils/transformers/use-query-like-transformer'>;
}
declare module "@tanstack/react-query/build/codemods/src/v4/key-transformation.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/codemods/src/v4/key-transformation'>;
}
declare module "@tanstack/react-query/build/codemods/src/v4/replace-import-specifier.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/codemods/src/v4/replace-import-specifier'>;
}
declare module "@tanstack/react-query/build/codemods/src/v4/utils/replacers/key-replacer.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/codemods/src/v4/utils/replacers/key-replacer'>;
}
declare module "@tanstack/react-query/build/codemods/src/v5/is-loading/is-loading.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/codemods/src/v5/is-loading/is-loading'>;
}
declare module "@tanstack/react-query/build/codemods/src/v5/keep-previous-data/keep-previous-data.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/codemods/src/v5/keep-previous-data/keep-previous-data'>;
}
declare module "@tanstack/react-query/build/codemods/src/v5/keep-previous-data/utils/already-has-placeholder-data-property.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/codemods/src/v5/keep-previous-data/utils/already-has-placeholder-data-property'>;
}
declare module "@tanstack/react-query/build/codemods/src/v5/remove-overloads/remove-overloads.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/codemods/src/v5/remove-overloads/remove-overloads'>;
}
declare module "@tanstack/react-query/build/codemods/src/v5/remove-overloads/transformers/filter-aware-usage-transformer.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/codemods/src/v5/remove-overloads/transformers/filter-aware-usage-transformer'>;
}
declare module "@tanstack/react-query/build/codemods/src/v5/remove-overloads/transformers/query-fn-aware-usage-transformer.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/codemods/src/v5/remove-overloads/transformers/query-fn-aware-usage-transformer'>;
}
declare module "@tanstack/react-query/build/codemods/src/v5/remove-overloads/utils/index" {
  declare module.exports: $Exports<'@tanstack/react-query/build/codemods/src/v5/remove-overloads/utils'>;
}
declare module "@tanstack/react-query/build/codemods/src/v5/remove-overloads/utils/index.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/codemods/src/v5/remove-overloads/utils'>;
}
declare module "@tanstack/react-query/build/codemods/src/v5/remove-overloads/utils/unknown-usage-error.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/codemods/src/v5/remove-overloads/utils/unknown-usage-error'>;
}
declare module "@tanstack/react-query/build/codemods/src/v5/rename-hydrate/rename-hydrate.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/codemods/src/v5/rename-hydrate/rename-hydrate'>;
}
declare module "@tanstack/react-query/build/codemods/src/v5/rename-properties/rename-properties.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/codemods/src/v5/rename-properties/rename-properties'>;
}
declare module "@tanstack/react-query/build/legacy/errorBoundaryUtils.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/legacy/errorBoundaryUtils'>;
}
declare module "@tanstack/react-query/build/legacy/HydrationBoundary.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/legacy/HydrationBoundary'>;
}
declare module "@tanstack/react-query/build/legacy/index" {
  declare module.exports: $Exports<'@tanstack/react-query/build/legacy'>;
}
declare module "@tanstack/react-query/build/legacy/index.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/legacy'>;
}
declare module "@tanstack/react-query/build/legacy/infiniteQueryOptions.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/legacy/infiniteQueryOptions'>;
}
declare module "@tanstack/react-query/build/legacy/isRestoring.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/legacy/isRestoring'>;
}
declare module "@tanstack/react-query/build/legacy/QueryClientProvider.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/legacy/QueryClientProvider'>;
}
declare module "@tanstack/react-query/build/legacy/QueryErrorResetBoundary.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/legacy/QueryErrorResetBoundary'>;
}
declare module "@tanstack/react-query/build/legacy/queryOptions.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/legacy/queryOptions'>;
}
declare module "@tanstack/react-query/build/legacy/suspense.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/legacy/suspense'>;
}
declare module "@tanstack/react-query/build/legacy/types.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/legacy/types'>;
}
declare module "@tanstack/react-query/build/legacy/useBaseQuery.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/legacy/useBaseQuery'>;
}
declare module "@tanstack/react-query/build/legacy/useInfiniteQuery.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/legacy/useInfiniteQuery'>;
}
declare module "@tanstack/react-query/build/legacy/useIsFetching.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/legacy/useIsFetching'>;
}
declare module "@tanstack/react-query/build/legacy/useMutation.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/legacy/useMutation'>;
}
declare module "@tanstack/react-query/build/legacy/useMutationState.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/legacy/useMutationState'>;
}
declare module "@tanstack/react-query/build/legacy/useQueries.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/legacy/useQueries'>;
}
declare module "@tanstack/react-query/build/legacy/useQuery.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/legacy/useQuery'>;
}
declare module "@tanstack/react-query/build/legacy/useSuspenseInfiniteQuery.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/legacy/useSuspenseInfiniteQuery'>;
}
declare module "@tanstack/react-query/build/legacy/useSuspenseQueries.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/legacy/useSuspenseQueries'>;
}
declare module "@tanstack/react-query/build/legacy/useSuspenseQuery.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/legacy/useSuspenseQuery'>;
}
declare module "@tanstack/react-query/build/legacy/utils.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/legacy/utils'>;
}
declare module "@tanstack/react-query/build/modern/errorBoundaryUtils.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/modern/errorBoundaryUtils'>;
}
declare module "@tanstack/react-query/build/modern/HydrationBoundary.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/modern/HydrationBoundary'>;
}
declare module "@tanstack/react-query/build/modern/index" {
  declare module.exports: $Exports<'@tanstack/react-query/build/modern'>;
}
declare module "@tanstack/react-query/build/modern/index.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/modern'>;
}
declare module "@tanstack/react-query/build/modern/infiniteQueryOptions.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/modern/infiniteQueryOptions'>;
}
declare module "@tanstack/react-query/build/modern/isRestoring.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/modern/isRestoring'>;
}
declare module "@tanstack/react-query/build/modern/QueryClientProvider.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/modern/QueryClientProvider'>;
}
declare module "@tanstack/react-query/build/modern/QueryErrorResetBoundary.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/modern/QueryErrorResetBoundary'>;
}
declare module "@tanstack/react-query/build/modern/queryOptions.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/modern/queryOptions'>;
}
declare module "@tanstack/react-query/build/modern/suspense.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/modern/suspense'>;
}
declare module "@tanstack/react-query/build/modern/types.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/modern/types'>;
}
declare module "@tanstack/react-query/build/modern/useBaseQuery.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/modern/useBaseQuery'>;
}
declare module "@tanstack/react-query/build/modern/useInfiniteQuery.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/modern/useInfiniteQuery'>;
}
declare module "@tanstack/react-query/build/modern/useIsFetching.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/modern/useIsFetching'>;
}
declare module "@tanstack/react-query/build/modern/useMutation.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/modern/useMutation'>;
}
declare module "@tanstack/react-query/build/modern/useMutationState.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/modern/useMutationState'>;
}
declare module "@tanstack/react-query/build/modern/useQueries.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/modern/useQueries'>;
}
declare module "@tanstack/react-query/build/modern/useQuery.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/modern/useQuery'>;
}
declare module "@tanstack/react-query/build/modern/useSuspenseInfiniteQuery.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/modern/useSuspenseInfiniteQuery'>;
}
declare module "@tanstack/react-query/build/modern/useSuspenseQueries.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/modern/useSuspenseQueries'>;
}
declare module "@tanstack/react-query/build/modern/useSuspenseQuery.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/modern/useSuspenseQuery'>;
}
declare module "@tanstack/react-query/build/modern/utils.js" {
  declare module.exports: $Exports<'@tanstack/react-query/build/modern/utils'>;
}
