### DO NOT EDIT THIS FILE!
###
### This file came from Crowdin and was normalized by i18ncli.js.
### It will be overwritten during the next translation sync. To add
### translations, go to https://crowdin.com/editor/inaturalistios/724
###

All = All
Cancel = Cancel
Casual--quality-grade = Casual
Collection-Project = Collection Project
Date = Date
Delete-observation = Delete observation
Delete-photo = Delete photo
Edit = Edit
Explore = Explore
improving--identification = Improving
leading--identification = Leading
maverick--identification = Maverick
Nearby = Nearby
Obscured = Obscured
Observe = Observe
OK = OK
Open = Open
Private = Private
Projects = Projects
Research-Grade--quality-grade = Research Grade
Satellite--map-type = Satellite
Save = Save
Search = Search
Share = Share
supporting--identification = Supporting
Taxa = Taxa
Traditional-Project = Traditional Project
Umbrella-Project = Umbrella Project
Unknown--rank = Unknown
Unknown--taxon = Unknown
Unknown--user = Unknown
View-in-browser = View in browser
