### DO NOT EDIT THIS FILE!
###
### This file came from Crowdin and was normalized by ftl.js.
### It will be overwritten during the next translation sync. To add
### translations, go to https://crowdin.com/editor/inaturalistios/724
###

A-global-community-for-nature = A global community for nature
ABOUT = ACERCA DE
ABOUT-COLLECTION-PROJECTS = ACERCA DE LOS PROYECTOS DE COLECCIÓN
ABOUT-INATURALIST = ACERCA DE INATURALIST
ABOUT-THE-DQA = SOBRE LA GCD
About-the-DQA-description = El grado de calidad resume la exactitud, precisión, integridad, pertinencia e idoneidad de una observación de iNaturalist como datos de biodiversidad. Algunos atributos se determinan automáticamente, mientras que otros están sujetos a votación por parte de los usuarios de iNat. iNaturalist comparte observaciones con licencia "Grado de Investigación" con una serie de socios de datos para su uso en la ciencia y la conservación.
ABOUT-TRADITIONAL-PROJECTS = SOBRE PROYECTOS TRADICIONALES
ABOUT-UMBRELLA-PROJECTS = SOBRE PROYECTOS UMBRELLA
accessible-comname-sciname = { $commonName } ({ $scientificName })
accessible-sciname-comname = { $scientificName } ({ $commonName })
Account-Deleted = Cuenta Eliminada
ACCOUNT-SETTINGS = CONFIGURACIÓN DE LA CUENTA
ACTIVITY = ACTIVIDAD
Add-agreement = Añadir Acuerdo
ADD-AN-ID = AÑADIR ID
Add-an-ID-Later = Añadir ID más tarde
ADD-COMMENT = AÑADIR COMENTARIO
Add-Date-Time = Añadir Fecha/Hora
Add-disagreement = Añadir Desacuerdo
ADD-EVIDENCE = AÑADIR MUESTRA
Add-evidence = Añadir muestra
Add-favorite = Añadir Favorito
Add-Location = Añadir ubicación
Add-location-for-better-identifications = Añadir ubicación para mejorar las identificaciones
ADD-LOCATION-FOR-BETTER-IDS = AÑADIR UBICACIÓN PARA MEJOR SDI
Add-location-to-refresh-suggestions = Añadir ubicación para actualizar sugerencias
Add-observations = Agregar observaciones
ADD-OPTIONAL-COMMENT = AÑADIR COMENTARIO OPCIONAL
Add-optional-notes = Añadir notas opcionales
Adds-your-vote-of-agreement = Añade tu voto de acuerdo
Adds-your-vote-of-disagreement = Añade tu voto de desacuerdo
ADVANCED-SETTINGS = ADVANCED SETTINGS
Affiliation = Afiliación: { $site }
After-capturing-or-importing-photos-show = Después de capturar o importar fotos, muestra:
Agree = Aceptar
AGREE = DE ACUERDO
AGREE-WITH-ID = ¿ESTÁ DE ACUERDO CON EL ID?
Agree-with-ID-description = ¿Está de acuerdo con el ID y sugiere las siguientes identificaciones?
AI-Camera = Cámara IA
ALL = TODO
All = Todos
All-observation-options--list = All observation options: iNaturalist AI Camera, Standard Camera, Uploading from Photo Library, and Sound Recorder
All-observations = Todas las observaciones
All-observations-need-a-date-and-location-to-be-used-for-science = All observations need a date and location to be used for science. Please edit observations if they need more information.
All-organisms = Todos los organismos
all-rights-reserved = todos los derechos reservados
All-taxa = Todos los taxones
ALL-USERS-EXCEPT = TODOS LOS USUARIOS EXCEPTO
ALLOW-LOCATION-ACCESS = PERMITIR ACCESO A LA UBICACIÓN
An-Internet-connection-is-required = Se necesita conexión a internet para cargar más observaciones.
Any--date = Cualquiera
Any--establishment-means = Cualquier
Any--media-type = Cualquier
Any--project = Cualquier
Any--quality-grade = Cualquier
Any--user = Cualquier
Anyone-using-iNaturalist-can-see = Cualquiera que utilice iNaturalist puede ver dónde se observó esta especie, y los científicos pueden usarla más fácilmente en su investigación.
APP-LANGUAGE = IDIOMA DE LA APP
apple-full-name = UNIRSE { JOIN($namePrefix, $givenName, $middleName, $nickname, $familyName, $nameSuffix, separador: "") }
APPLY-FILTERS = APLICAR FILTROS
Apply-filters = Aplicar filtros
April = Abril
Are-you-an-educator = ¿Eres un profesor que quiere usar iNaturalist con sus estudiantes?
Are-you-sure-you-want-to-log-out = ¿Estás seguro de que quieres salir de tu cuenta de iNaturalist? Todas las observaciones que no se hayan subido a iNaturalist se borrarán.
attribution-cc-by = Algunos derechos reservados (CC BY)
attribution-cc-by-nc = Algunos derechos reservados (CC BY-NC)
attribution-cc-by-nc-nd = Algunos derechos reservados (CC BY-NC-ND)
attribution-cc-by-nc-sa = Algunos derechos reservados (CC BY-NC-SA)
attribution-cc-by-nd = Algunos derechos reservados (CC BY-ND)
attribution-cc-by-sa = Algunos derechos reservados (CC BY-SA)
August = Agosto
BACK-TO-LOGIN = VOLVER AL INICIO DE SESIÓN
BLOG = BLOG
Bulk-importer = Importador a Granel
By-exiting-changes-not-saved = Al salir, los cambios en su observación no será guardada.
By-exiting-observation-not-saved = Al salir, su observación no será guardada.
By-exiting-your-observations-not-saved = Al salir, sus observaciones no serán guardadas. Usted puede guardarlas en su dispositivo, o puede borrarlas.
By-exiting-your-photos-will-not-be-saved = Al salir, sus fotos no serán guardadas.
By-exiting-your-recorded-sound-will-not-be-saved = Al salir, su sonido grabado no será guardado.
BY-ME = POR MI
By-uploading-your-observation-to-iNaturalist-you-can = Al cargar su observación a iNaturalist, puede:
Camera = Cámara
CANCEL = CANCELAR
Cancel = Cancelar
Captive-Cultivated = En cautividad / Cultivado
Casual--quality-grade = Casual
CC-BY = CC BY
CC-BY-NC = CC BY-NC
CC-BY-NC-ND = CC BY-NC-ND
CC-BY-NC-SA = CC BY-NC-SA
CC-BY-ND = CC BY-ND
CC-BY-SA = CC BY-SA
CC0 = CC0
CHANGE-APP-LANGUAGE = CAMBIAR IDIOMA DE LA APP
CHANGE-DATE = CAMBIAR FECHA
Change-date = Cambiar fecha
CHANGE-END-DATE = CAMBIAR FECHA FINAL
Change-end-date = Cambiar fecha final
Change-project = Cambiar proyecto
CHANGE-START-DATE = CAMBIAR FECHA INICIAL
Change-start-date = Cambiar fecha inicial
Change-taxon = Cambiar taxón
Change-taxon-filter = Cambiar filtro de taxón
Change-user = Cambiar usuario
Change-zoom = Cambiar zoom
CHECK-YOUR-EMAIL = ¡REVISA TU CORREO!
CHOOSE-A-USERNAME = CHOOSE A USERNAME
Choose-taxon = ELEGIR TAXON
Choose-top-taxon = ELEGIR TAXON SUPERIOR
Clear = Borrar
Close = Cerrar
Close-permission-request-screen = Cerrar la pantalla de solicitud de permisos
Close-search = Cerrar búsqueda
Closes-explanation = Closes explanation
Closes-introduction = Cerrar introducción
Closes-new-observation-explanation = Closes new observation explanation.
Closes-new-observation-options = Cerrar nuevas opciones de observación.
Closes-withdraw-id-sheet = Cerrar hoja "Retirar ID"
COLLABORATORS = COLABORADORES
Collection-Project = Proyecto de colección
Combine-Photos = Combinar Fotos
COMMENT = COMENTAR
Comment-options = Opciones de Comentarios
Common-Name-Scientific-Name = Nombre Común (Nombre Científico)
Community-Discussion = Community Discussion
Community-Guidelines = Directrices de la comunidad
COMMUNITY-GUIDELINES = Directrices Comunitarias
Confidence--label = Seguridad
CONFIRM = CONFIRMAR
Congratulations-You-made-your-first-observation = Congratulations! You made your first observation!
Connect-with-expert-naturalists = Connect with expert naturalists
Connect-with-other-naturalists = Conecte con otros naturalistas y participe en conversaciones.
Connection-problem-Please-try-again-later = Problema de conexión. Inténtelo de nuevo más tarde.
CONTACT-SUPPORT = CONTACTAR SOPORTE
CONTINUE = CONTINUAR
Coordinates-copied-to-clipboard = Coordenadas copiadas en el portapapeles
Copy-coordinates = Copiar Coordenadas
Copyright = Derechos de Autor
Could-not-find-a-camera-on-this-device = No se puede encontrar una cámara en este dispositivo
Couldnt-create-comment = No se puede crear el comentario
Couldnt-create-identification-error = No se pudo crear la identificación { $error }
Couldnt-create-identification-unknown-error = No se pudo crear la identificación, error desconocido.
CREATE-AN-ACCOUNT = CREAR UNA CUENTA
Create-an-observation-evidence = Crear una observación sin evidencia
DATA-QUALITY = CALIDAD DE DATOS
DATA-QUALITY-ASSESSMENT = EVALUACIÓN DE LA CALIDAD DE DATOS
Data-Quality-Assessment = Evaluación de la Calidad de Datos
Data-quality-assessment-can-taxon-still-be-confirmed-improved-based-on-the-evidence = Basándose en las pruebas, ¿se puede seguir mejorando el taxón comunitario?
Data-quality-assessment-community-taxon-species-level-or-lower = Taxón comunitario a nivel de especie o inferior
Data-quality-assessment-date-is-accurate = La fecha es correcta
Data-quality-assessment-date-specified = Fecha especificada
Data-quality-assessment-description-casual = Esta observación no ha cumplido las condiciones para la condición de Investigación.
Data-quality-assessment-description-needs-id = Esta observación no ha cumplido las condiciones para la condición de Investigación.
Data-quality-assessment-description-research = Ahora puede utilizarse para propósitos de investigación y presentarse en otros sitios web
Data-quality-assessment-evidence-of-organism = Evidencia del organismo
Data-quality-assessment-has-photos-or-sounds = Tiene fotos o sonidos
Data-quality-assessment-id-supported-by-two-or-more = Tiene Ident apoyado por dos o más
Data-quality-assessment-location-is-accurate = La ubicación es precisa
Data-quality-assessment-location-specified = Ubicación especificada
Data-quality-assessment-organism-is-wild = El organismo es silvestre
Data-quality-assessment-recent-evidence-of-organism = Evidencia reciente de un organismo
Data-quality-assessment-single-subject = Evidencia relativa a un único individuo
Data-quality-assessment-title-casual = Esta observación es de Grado Informal
Data-quality-assessment-title-needs-id = Esta observación necesita ID
Data-quality-assessment-title-research = Esta observación es de Grado de Investigación!
DATE = FECHA
Date = Fecha
date-format-long = PP
date-format-month-day = d MMM
date-format-month-year = MMM yyyy
date-format-short = d/M/yy
DATE-OBSERVED = FECHA DE OBSERVACIÓN
Date-observed = Fecha de observación
Date-observed-header-short = Observado el
DATE-OBSERVED-NEWEST = FECHA DE OBSERVACIÓN - DE LA MÁS RECIENTE A LA MÁS ANTIGUA
DATE-OBSERVED-OLDEST = FECHA DE OBSERVACIÓN - DE LA MÁS ANTIGUA A LA MÁS RECIENTE
Date-Range = Intervalo de fechas
DATE-RANGE = RANGO DE FECHAS
date-to-date = { $d1 } - { $d2 }
DATE-UPLOADED = FECHA DE SUBIDA
Date-uploaded = Fecha de Subida
Date-uploaded-header-short = Subida
DATE-UPLOADED-NEWEST = FECHA DE SUBIDA - DE LA MÁS RECIENTE A LA MÁS ANTIGUA
DATE-UPLOADED-OLDEST = FECHA DE SUBIDA - DE LA MÁS ANTIGUA A LA MÁS RECIENTE
Date-uploaded-on-header-short = Subido el:
datetime-difference-days = { $count }d
datetime-difference-hours = { $count }d
datetime-difference-minutes = { $count }m
datetime-difference-weeks = { $count }w
datetime-format-long = Pp
datetime-format-long-with-zone = Pp (zzz)
datetime-format-short = d/M/yy hh:mm
datetime-format-short-with-zone = d/M/yy h:mm a zzz
December = Diciembre
DELETE = BORRAR
Delete-all-observations = Borrar todas las observaciones
Delete-comment = Borrar comentario
DELETE-COMMENT--question = ¿BORRAR COMENTARIO?
Delete-current-observation = Borrar la observación actual
Delete-observation = Borrar observación
DELETE-OBSERVATION--question = ¿ELIMINAR OBSERVACIÓN?
Delete-photo = Eliminar foto
Delete-sound = Eliminar sonido
Deletes-entered-text = Eliminar texto introducido
Deleting-x-of-y--observations =
    Eliminando { $currentDeleteCount } { $total ->
        [one] de { $total }
       *[other] de observaciones { $total }
    }
Deleting-x-of-y-observations-2 =
    Eliminando { $currentDeleteCount } { $total ->
        [one] de { $total }
       *[other] de observaciones { $total }
    }
Details = Detalles
DETAILS = DETALLES
Device-storage-full = El almacenamiento del dispositivo está lleno.
Device-storage-full-description = Es posible que iNaturalist no pueda guardar sus fotos o que se bloquee.
Disable-flash = Desactivar Flash
Disable-location = Deshabilitar ubicación
Disagreement = *@{ $username } no está de acuerdo con esto es <0/>
DISCARD = DESCARTAR
DISCARD-ALL = DESCARTAR TODO
DISCARD-CHANGES = DESCARTAR CAMBIOS
DISCARD-FILTER-CHANGES = DESCARTAR CAMBIOS DE FILTRO
DISCARD-MEDIA--question = ¿DESCARTAR MEDIA?
DISCARD-OBSERVATION = DESCARTAR OBSERVACIÓN
DISCARD-PHOTOS--question = ¿DESCARTAR FOTOS?
DISCARD-RECORDING = DESCARTAR GRABACIÓN
DISCARD-SOUND--question = ¿DESCARTAR SONIDO?
DISCARD-X-OBSERVATIONS =
    { $count ->
        [one] OBSERVATION DE DISCARD
       *[other] DESCARD { $count } OBSERVATIONS
    }
DISCOVER-NATURE-AROUND-YOU = DISCOVER NATURE AROUND YOU
DISMISS = DESESTIMAR
Do-you-know-what-group-this-is-in = Do you know what group this is in?
DONATE = DONAR
DONATE-TO-INATURALIST = DONAR A INATURALIST
DONE = HECHO
Dont-have-an-account = <0>¿No tienes una cuenta? </0><1>Regístrate</1>
During-app-start-no-model-found = Durante el inicio de la aplicación no se encontró ningún modelo de visión de ordenador. No habrá cámara IA.
Edit = Editar
EDIT-COMMENT = EDITAR COMENTARIO
Edit-comment = Editar comentario
Edit-identification = Editar identificación
EDIT-LOCATION = EDITAR UBICACIÓN
Edit-location = Editar ubicación
Edit-Observation = Editar observación
Edit-your-profile-change-your-settings = Edita tu perfil, cambia la configuración de las notificaciones y administra todas las demás partes de tu cuenta.
Edits-this-observations-taxon = Edita el taxón de esta observación
EDUCATORS = EDUCADORES
EMAIL = EMAIL
EMAIL-DEBUG-LOGS = EMAIL DEBUG LOGS
Enable-flash = Enable flash
Enable-location = Enable location
Enable-notifications = Enable notifications
Endemic = Endémico
Endemic-to-place = Endemic to { $place }
Error = Error
ERROR = ERROR
ERROR-LOADING-DQA = ERROR LOADING IN DQA
Error-title = Error
ERROR-VOTING-IN-DQA = ERROR VOTING IN DQA
Error-voting-in-DQA-description = Your vote may not have been cast in the DQA. Check your internet connection and try again.
Establishment = Establecimiento
ESTABLISHMENT-MEANS = ESTABLISHMENT MEANS
Every-observation-needs = Every observation needs a location, date, and time to be helpful to identifiers. You can edit geoprivacy if you’re concerned about location privacy.
Every-time-a-collection-project = Every time a collection project's page is loaded, iNaturalist will perform a quick search and display all observations that match the project's requirements. It is an easy way to display a set of observations, such as for a class project, a park, or a bioblitz without making participants take the extra step of manually adding their observations to a project.
EVIDENCE = EVIDENCE
Exact-Date = Fecha exacta
EXACT-DATE = EXACT DATE
except = excepto
EXPAND-MAP = EXPAND MAP
Experts-help-verify-and-improve-IDs = Experts help verify and improve IDs
Explore = Explora
EXPLORE = EXPLORE
Explore-Filters = Explore Filters
EXPLORE-IDENTIFIERS = EXPLORE IDENTIFIERS
EXPLORE-OBSERVATIONS = EXPLORE OBSERVATIONS
EXPLORE-OBSERVERS = EXPLORE OBSERVERS
EXPLORE-SPECIES = EXPLORE SPECIES
Failed-to-delete-sound = Failed to delete sound
Failed-to-log-in = Failed to log in
FEATURED = DESTACADO
February = febrero
FEEDBACK = FEEDBACK
Feedback-Submitted = Feedback Submitted
Fetching-location = Fetching location...
Filter = Filtro
FILTER-BY-A-PROJECT = FILTER BY A PROJECT
FILTER-BY-A-USER = FILTER BY A USER
Filter-by-observed-between-dates = Filter by observations observed between two specific dates
Filter-by-observed-during-months = Filter by observations observed during specific months
Filter-by-observed-on-date = Filter by observations observed on a specific date
Filter-by-uploaded-between-dates = Filter by observations uploaded between two specific dates
Filter-by-uploaded-on-date = Filter by observations uploaded on a specific date
Filters = Filtros
Flag-An-Item = Marcar un elemento
Flag-Item-Description = Flagging brings something to the attention of volunteer site curators. Please don't flag problems you can address with identifications, the Data Quality Assessment, or by talking to the person who made the content.
Flag-Item-Other = Flagged as Other Description Box
Flag-Item-Other-Description = Alguna otra razón, puedes explicarla a continuación.
Flag-Item-Other-Input-Hint = Especificar la razón por la que has marcado este elemento
Flagged = Marcado
Flash = Flash
Flip-camera = Flip camera
FOLLOW = FOLLOW
FOLLOWING--notifications = FOLLOWING
FOLLOWING-X-PEOPLE =
    { $count ->
        [one] FOLLOWING { $count } PERSON
       *[other] FOLLOWING { $count } PEOPLE
    }
Forgot-Password = Forgot Password
GEOPRIVACY = GEOPRIVACY
Geoprivacy-status = Geoprivacy: { $status }
Get-an-instant-ID-of-any-plant-animal-fungus = Get an instant ID of any plant, animal, or fungus
Get-feedback-from-naturalists-and-experts-who-will-help-verify = Get feedback from naturalists and experts who will help verify and refine your identifications.
Get-your-identification-verified-by-real-people = Obtenga su identificación verificada por personas reales en la comunidad de iNaturalist
Getting-an-even-more-accurate-ID = Getting an even more accurate ID...
Go-back = Volver
Google-Play-Services-Not-Installed = Los Servicios de Google Play no están instalados
GRANT-PERMISSION = CONCEDER PERMISO
Grant-Permission-title = Conceder Permiso
Group-Photos = Grupo de fotos
Group-photos-onboarding = Agrupar fotos en observaciones– asegúrese de que solo hay una especie por observación
HELP = AYUDA
Help-create-Research-Grade-data-used-in-science-and-conservation = Help create Research Grade data used in science and conservation.
Help-protect-species = Help protect species
Hide = Ocultar
Highest = El más alto
HIGHEST-RANK = RANGO MÁS ALTO
I-agree-to-the-Terms-of-Use = <0>I agree to the Terms of Use and Privacy Policy, and I have reviewed the Community Guidelines (</0><1>required</1><0>).</0>
Iconic-taxon-name = Nombre del taxón ícono: { $iconicTaxon }
ID-Suggestions = Sugerencias de identificación
ID-Withdrawn = Id. retirada
IDENTIFICATION = IDENTIFICACIÓN
Identification-options = Opciones de identificación
IDENTIFICATIONS-WITHOUT-NUMBER =
    { $count ->
        [one] IDENTIFICACIÓN
       *[other] IDENTIFICATIONS
    }
Identifiers = Identificadores
Identifiers-View = Vista de identificadores
Identify-an-organism = Identificar un organismo
Identify-organisms-in-real-time-with-your-camera = Identify organisms in real time with your camera
Identify-species-anywhere = Identify species anywhere
If-an-account-with-that-email-exists = Si existe una cuenta con ese correo electrónico, hemos enviado instrucciones para restablecer la contraseña a su correo electrónico.
If-you-have-an-existing-account-try-sign-in-reset = Si tiene una cuenta de iNat existente, intente iniciar sesión con su nombre de usuario y contraseña, o intente restablecer su contraseña usando la dirección de correo electrónico asociada a su cuenta.
If-you-hold-down-instead-of-tapping-the-camera-button-you-can = If you hold down (instead of tapping) the camera button, you can record sounds, take multiple photos, and import from your photo library.
If-you-leave-x-of-your-observations-removed =
    Si abandonas este proyecto tradicional, { $count ->
        [one] 1 de tus observaciones
       *[other] { $count } de tus observaciones
    } también será eliminado de este proyecto.
If-you-save-this-observation-and-upload-it-to-iNaturalist = If you save this observation and upload it to iNaturalist, other people may be able to help identify it.
If-you-want-to-collate-compare-promote = Si desea cotejar, comparar o promover un conjunto de proyectos existentes, entonces un proyecto de Umbrella es lo que debe utilizar. Por ejemplo, el Desafío de la Naturaleza de la Ciudad de 2018, que reunió más de 60 proyectos, hecho para una gran página de aterrizaje donde cualquiera podría comparar y contrastar las observaciones de cada ciudad. Tanto los proyectos de Colección como Tradicionales pueden ser utilizados en un proyecto de Umbrella y hasta 500 proyectos pueden ser compilados por un proyecto de Umbrella.
If-youre-seeing-this-error = Si usted viendo esto y está en línea, el personal de iNat ya ha sido notificado. ¡Gracias por encontrar un error! Si está fuera de línea, por favor tome una captura de pantalla y envíanos un correo electrónico cuando esté de nuevo en Internet.
IGNORE-LOCATION = IGNORAR UBICACIÓN
Ignore-notifications = Ignorar notificaciones
Ignoring-location = Ignoring location
Import-Photos-From = Importar fotos desde
IMPORT-X-OBSERVATIONS =
    IMPORTAR { $count ->
        [one] OBSERVACIÓN 1
       *[other] { $count } OBSERVACIONES
    }
Improve-suggestions-by-using-your-location = Improve suggestions by using your location
IMPROVE-THESE-SUGGESTIONS-BY-USING-YOUR-LOCATION = MEJORAR ESTAS SUGERENCIAS UTILIZANDO SU UBICACIÓN
improving--identification = Mejorando
INATURALIST-ACCOUNT-SETTINGS = CONFIGURACIÓN DE LA CUENTA INATURALIST
iNaturalist-AI-Camera = Cámara IA iNaturalist
iNaturalist-can-save-photos-you-take-in-the-app-to-your-devices-library = iNaturalist can save photos you take in the app to your device’s library.
iNaturalist-can-use-your-location-to-give-you-better-identification-suggestions = iNaturalist can use your location to give you better identification suggestions. We also use it to help you find species seen nearby. Sharing your location makes it easier to create useful data for science.
INATURALIST-COMMUNITY = COMUNIDAD INATURALIST
INATURALIST-FORUM = FORO INATURALIST
iNaturalist-has-no-ID-suggestions-for-this-photo = iNaturalist no tiene sugerencias de identificación para esta foto.
INATURALIST-HELP-PAGE = PÁGINA DE AYUDA INATURALIST
iNaturalist-helps-you-identify = iNaturalist te ayuda a identificar las plantas y animales que te rodean y a la vez a generar datos para la ciencia y la conservación. ¡Conéctate con una comunidad de millones de científicos y naturalistas que pueden ayudarte a aprender más sobre la naturaleza!
iNaturalist-identification-suggestions-are-based-on = Las sugerencias de identificación de iNaturalist se basan en observaciones e identificaciones realizadas por la comunidad iNaturalista, incluyendo { $user1 }, { $user2 }, { $user3 }y muchos otros.
iNaturalist-is-a-501 = iNaturalist es una organización sin fines de lucro 501(c)(3) en los Estados Unidos de América (Tax ID/EIN 92-1296468).
iNaturalist-is-loading-ID-suggestions = iNaturalist está cargando sugerencias de ID...
iNaturalist-is-supported-by = iNaturalist cuenta con el apoyo de una organización independiente 501(c)(3) sin fines de lucro con sede en los Estados Unidos de América. La plataforma iNaturalist incluye esta aplicación, Seek by iNaturalist, el sitio web de iNaturalist y más.
iNaturalist-is-supported-by-our-community = iNaturalist cuenta con el apoyo de nuestra increíble comunidad. Desde naturalistas cotidianos que añaden observaciones e identificaciones, hasta curadores que gestionan nuestra taxonomía y ayudan con moderación, a los traductores voluntarios que hacen que iNaturalist sea más accesible para el público mundial, a nuestros donantes que pertenecen a la comunidad, estamos extraordinariamente agradecidos con todas las personas de nuestra comunidad que hacen de iNaturalist la plataforma que es.
iNaturalist-mission-is-to-connect = La misión de iNaturalist es conectar a las personas con la naturaleza y promover la ciencia y conservación de la biodiversidad.
INATURALIST-MISSION-VISION = MISIÓN Y VISIÓN DE INATURALIST
INATURALIST-NETWORK = RED INATURALIST
INATURALIST-SETTINGS = CONFIGURACIÓN DE INATURALIST
INATURALIST-STAFF = { $inaturalist } STAFF
INATURALIST-STORE = INATURALIST STORE
INATURALIST-TEAM = INATURALIST TEAM
iNaturalist-users-who-have-left-an-identification = iNaturalist users who have left an identification on another user's observation
iNaturalist-users-who-have-observed = iNaturalist users who have observed a particular taxon at a particular time and place
iNaturalists-apps-are-designed-and-developed-3 = iNaturalist's apps are designed, developed, and supported by the iNaturalist team: Yaron Budowski, Amanda Bullington, Tony Iwane, Johannes Klein, Patrick Leary, Joanne Lin, Scott Loarie, Abhas Misraraj, Sylvain Morin, Carrie Seltzer, Alex Shepard, Thea Skaff, Angie Ta, Ken-ichi Ueda, Kirk van Gorkom, Jason Walthall, & Jane Weeden.
iNaturalists-vision-is-a-world = iNaturalist's vision is a world where everyone can understand and sustain biodiversity through the practice of observing wild organisms and sharing information about them.
Individual-encounters-with-organisms = Individual encounters with organisms at a particular time and location, usually with evidence
Internet-Connection-Required = Internet Connection Required
Intl-number = { $val }
Introduced = Introducida
Introduced-to-place = Introduced to { $place }
It-can-now-be-shared-for-use-in-research = It can now be shared for use in research
It-may-take-up-to-an-hour-to-remove-content = It may take up to an hour to completely delete all associated content
It-might-also-be = It might also be
It-might-be-one-of-these = It might be one of these
January = enero
JOIN = ÚNETE
Join-a-global-community-for-nature = Join a global community for nature
JOIN-PROJECT = JOIN PROJECT
JOIN-PROJECT--question = JOIN PROJECT?
JOINED = UNIDO
Joined-date = Joined: { $date }
JOINED-X-PROJECTS =
    { $count ->
        [one] JOINED { $count } PROJECT
       *[other] JOINED { $count } PROJECTS
    }
JOURNAL-POSTS-WITHOUT-NUMBER =
    { $count ->
        [one] JOURNAL POST
       *[other] JOURNAL POSTS
    }
July = Julio
June = Junio
Just-make-sure-the-organism-is-wild = Just make sure the organism is wild (not a pet, zoo animal, or garden plant)
Last-Active-date = Last Active: { $date }
Lat-Lon = { NUMBER($latitude, maximumFractionDigits: 6) }, { NUMBER($longitude, maximumFractionDigits: 6) }
Lat-Lon-Acc = Lat: { NUMBER($latitude, maximumFractionDigits: 6) }, Lon: { NUMBER($longitude, maximumFractionDigits: 6) }, Acc: { $accuracy }
leading--identification = Principal
Learn-from-people-who-verify-and-refine-your-identifications = Learn from people who verify and refine your identifications.
Learn-More = Aprende más
LEARN-MORE-ABOUT-THIS-GROUP = LEARN MORE ABOUT THIS GROUP
LEARN-MORE-ABOUT-THIS-SPECIES = LEARN MORE ABOUT THIS SPECIES
LEAVE = LEAVE
LEAVE-PROJECT = LEAVE PROJECT
LEAVE-PROJECT--question = LEAVE PROJECT?
LEAVE-US-A-REVIEW = LEAVE US A REVIEW!
Lets-reset-your-password = Let’s reset your password.
Loading-iNaturalists-AI-Camera = Loading iNaturalist's AI Camera
Loads-content-that-requires-an-Internet-connection = Loads content that requires an Internet connection
LOCATION = LOCATION
Location = Ubicación
Location-accuracy-is-too-imprecise = Location accuracy is too imprecise to help identifiers. Please zoom in.
LOCATION-TOO-IMPRECISE = LOCATION TOO IMPRECISE
LOG-IN = LOG IN
LOG-IN-TO-INATURALIST = LOG IN TO INATURALIST
Log-in-to-iNaturalist = Log in to iNaturalist
LOG-OUT = CERRAR SESIÓN
LOG-OUT--question = LOG OUT?
Lowest = Lowest
LOWEST-RANK = LOWEST RANK
MAP = MAP
Map-Area = Mapa del área
March = Marzo
Match-Screen = Match Screen
maverick--identification = Discordante
May = Mayo
MEDIA = MEDIA
Media-Type = Tipo de medios
MEMBERS-WITHOUT-NUMBER =
    { $count ->
        [one] MIEMBRO
       *[other] MIEMBROS
    }
Menu = Menu
Missing-Date = Fecha faltante
MISSING-EVIDENCE = FALTA EVIDENCIA
Monthly-Donor = Donante mensual
Months = Meses
MONTHS = MESES
More = Más
More-info = Más información
More-ways-to-observe = More ways to observe
MOST-FAVED = LOS MÁS FAVORITOS
Most-faved = Los más favoritos
MY-CONTENT--notifications = MI CONTENIDO
My-Observations = Mis Observaciones
My-Observations--bottom-tab = Yo
Native = Nativa
Native-to-place = Nativo de { $place }
Navigates-to-AI-camera = Navegar a la cámara IA
Navigates-to-bulk-importer = Navegar al importador a granel
Navigates-to-camera = Navegar a la cámara
Navigates-to-explore = Navegar para explorar
Navigates-to-match-screen = Navigates to match screen
Navigates-to-notifications = Navegar a las notificaciones
Navigates-to-observation-details = Navegar a la pantalla de detalles de observación
Navigates-to-observation-edit-screen = Navegar a la pantalla de edición de observaciones
Navigates-to-photo-importer = Navegar al importador de fotos
Navigates-to-previous-screen = Navegar a la pantalla anterior
Navigates-to-project-details = Navegar a los detalles del proyecto
Navigates-to-sound-recorder = Navegar a la grabadora de sonido
Navigates-to-suggest-identification = Navegar para sugerir identificación
Navigates-to-taxon-details = Navegar a los detalles del taxón
Navigates-to-user-profile = Navegar al perfil de usuario
Navigates-to-your-observations = Volver a sus observaciones
NEARBY = CERCA
Nearby = Cerca
Needs-ID--quality-grade = Necesita Ident.
New-Observation = Nuevas observaciones
Newest-to-oldest = Del más reciente al más antiguo
Next-observation = Siguiente observación
Next-slide = Next slide
No-Camera-Available = No hay cámara disponible
No-email-app-installed = No hay aplicación de correo instalada
No-email-app-installed-body = Si tiene otra forma de enviar correo electrónico, la dirección es { $address }
No-email-app-installed-body-check-other = Intente revisar su correo electrónico en un navegador web o en otro dispositivo.
No-Location = No hay ubicaciones
No-Media = Sin archivos multimedia
No-model-found = No se encuentra el modelo
No-Notifications-Found = ¡No tiene notificaciones! Empiece creando sus propias observaciones.
No-projects-match-that-search = Ningún proyecto coincide con esa búsqueda
No-results-found-for-that-search = No se encontraron resultados para esa búsqueda
No-results-found-try-different-search = No se han encontrado resultados. Intente una búsqueda diferente o ajuste sus filtros.
no-rights-reserved-cc0 = No hay derechos reservados (CC0)
none--accuracy = Ninguno
NONE--ranks = NINGUNO
NOT-BY-ME = YO NO
Not-enough-space-left-on-device = No queda suficiente espacio en el dispositivo
Not-enough-space-left-on-device-try-again = No hay suficiente espacio de almacenamiento en su dispositivo para hacer eso. Por favor, libere algo de espacio e inténtelo de nuevo.
NOTES = NOTES
Notes = Notes
NOTIFICATIONS = NOTIFICATIONS
Notifications--bottom-tab = Activity
notifications-user-added-comment-to-observation-by-you = <0>{ $userName }</0> added a comment to an observation by you
notifications-user-added-identification-to-observation-by-you = <0>{ $userName }</0> added an identification to an observation by you
notifications-user1-added-comment-to-observation-by-user2 = <0>{ $user1 }</0>añadió un comentario a una observación de { $user2 }
notifications-user1-added-identification-to-observation-by-user2 = <0>{ $user1 }</0>añadió una identificación a una observación de { $user2 }
November = Noviembre
Obervations-must-be-manually-added = Observations must be manually added to a traditional project, either during the upload stage or after the observation has been shared to iNaturalist. A user must also join a traditional project in order to add their observations to it.
Obscured = Oscurecida
Observation = Observación
Observation-Attribution = Observation: © { $userName } · { $restrictions }
Observation-Copyright = Observation Copyright: © { $userName } · { $restrictions }
Observation-has-no-photos-and-no-sounds = This observation has no photos and no sounds.
Observation-location-obscured-randomized-point = This observation’s location is obscured. You are seeing a randomized point within the obscuration polygon.
Observation-location-obscured-you-can-see-your-own = This observation’s location is obscured. You can always see the location of your own observations.
Observation-location-obscured-you-have-permission = This observation’s location is obscured. You have permission to see this location.
Observation-options = Observation options
OBSERVATION-WAS-DELETED = OBSERVATION WAS DELETED
Observation-with-no-evidence = Observation with no evidence
Observations = Observaciones
Observations-need-location-date--warning = iNaturalist observations need a location and date to be useful to scientists. Please check observations with this icon before uploading.
Observations-View = Observations View
OBSERVATIONS-WITHOUT-NUMBER =
    { $count ->
        [one] OBSERVATION
       *[other] OBSERVATIONS
    }
OBSERVE-ORGANISMS = OBSERVE ORGANISMS
OBSERVED-AT--label = OBSERVED AT
OBSERVED-IN--label = OBSERVED IN
Observers = Observadores
Observers-View = Observers View
October = Octubre
Offensive-Inappropriate = Ofensivo/inapropiado
Offensive-Inappropriate-Examples = Misleading or illegal content, racial or ethnic slurs, etc. For more on our definition of "appropriate," see the FAQ.
Offline-DQA-description = The DQA may not be accurate. Check your internet connection and try again.
Offline-suggestions-may-differ-from-online = Offline suggestions may differ from online suggestions, and taxon images and common names may not load.
OK = Ok
Oldest-to-newest = Oldest to newest
Once-you-create-and-upload-observations = Once you create & upload observations, other members of our community can add identifications to help your observations reach research grade.
Open = Abrir
OPEN-EMAIL = OPEN EMAIL
Open-menu = Open menu.
OPEN-SETTINGS = OPEN SETTINGS
Opens-add-comment-form = Opens add comment form.
Opens-AI-camera = Opens AI camera.
Opens-edit-comment-form = Opens edit comment form.
Opens-location-permission-prompt = Opens location permission prompt
Opens-the-side-drawer-menu = Opens the side drawer menu.
OR-SIGN-IN-WITH = OR SIGN IN WITH
Or-you-can-try-to-get-a-clearer-photo-by-zooming-in-getting-closer = Or, you can try to get a clearer photo by zooming in, getting closer, or trying a different angle.
Organism-is-captive = Organism is captive
Organisms-that-are-identified-to-species = Organisms that are identified to species rank or below
Other = Otro
OTHER-DATA = OTHER DATA
OTHER-SUGGESTIONS = OTHER SUGGESTIONS
PASSWORD = PASSWORD
PEOPLE--title = PEOPLE
Photo-importer = Photo importer
PHOTO-LICENSING = PHOTO LICENSING
Photos = Fotos
Photos-you-take-will-appear-here = Photos you take will appear here
Please-allow-Camera-Access = Please allow Camera Access
Please-allow-Location-Access = Please allow Location Access
Please-allow-Microphone-Access = Please allow Microphone Access
Please-choose-a-different-password = Please choose a different password.
Please-Grant-Permission = Please Grant Permission
PLEASE-LOG-IN = PLEASE LOG IN
Please-make-sure-your-password-is-at-least-6-characters = Please make sure your password is at least 6 characters.
Please-try-again-when-you-are-connected-to-the-internet = Please try again when you are connected to the Internet.
Please-try-again-when-you-are-online = Please try again when you are online!
Point-the-camera-at-an-animal-plant-or-fungus = Point the camera at an animal, plant, or fungus
POTENTIAL-DISAGREEMENT = POTENTIAL DISAGREEMENT
Potential-disagreement-description = <0>Is the evidence enough to confirm this is </0><1></1><0>?<0>
Potential-disagreement-disagree = <0>No, but this is a member of </0><1></1>
Potential-disagreement-unsure = <0>I don't know but I am sure this is </0><1></1>
Previous-observation = Previous observation
Previous-slide = Previous slide
Privacy-Policy = Política de privacidad
PRIVACY-POLICY = PRIVACY POLICY
Private = Privado
PROJECT = PROJECT
Project-Members-Only = Solo miembros del proyecto
PROJECT-REQUIREMENTS = PROJECT REQUIREMENTS
project-start-time-datetime = Start time: { $datetime }
PROJECTS = PROJECTS
Projects = Proyectos
PROJECTS-X = PROYECTOS ({ $projectCount })
Pull-to-refresh-and-sync-observations = Pull to refresh and sync observations
Pull-to-refresh-notifications = Pull to refresh notifications
QUALITY-GRADE = QUALITY GRADE
Quality-Grade = Grado de calidad
Quality-Grade-Casual--label = Quality Grade: Casual
Quality-Grade-Needs-ID--label = Quality Grade: Needs ID
Quality-Grade-Research--label = Quality Grade: Research
Ranks-CLASS = CLASS
Ranks-Class = Clase
Ranks-COMPLEX = COMPLEX
Ranks-Complex = Complejo
Ranks-EPIFAMILY = EPIFAMILY
Ranks-Epifamily = Epifamilia
Ranks-FAMILY = FAMILY
Ranks-Family = Familia
Ranks-FORM = FORM
Ranks-Form = Forma
Ranks-GENUS = GENUS
Ranks-Genus = Género
Ranks-GENUSHYBRID = GENUSHYBRID
Ranks-Genushybrid = Género híbrido
Ranks-HYBRID = HYBRID
Ranks-Hybrid = Híbrido
Ranks-INFRACLASS = INFRACLASS
Ranks-Infraclass = Infraclase
Ranks-INFRAHYBRID = INFRAHYBRID
Ranks-Infrahybrid = Infrahíbrido
Ranks-INFRAORDER = INFRAORDER
Ranks-Infraorder = Infraorden
Ranks-KINGDOM = KINGDOM
Ranks-Kingdom = Reino
Ranks-ORDER = ORDER
Ranks-Order = Orden
Ranks-PARVORDER = PARVORDER
Ranks-Parvorder = Parvorden
Ranks-PHYLUM = PHYLUM
Ranks-Phylum = Filo
Ranks-SECTION = SECTION
Ranks-Section = Sección
Ranks-SPECIES = ESPECIE
Ranks-Species = Especies
Ranks-Statefmatter = Estado de la materia
Ranks-STATEOFMATTER = STATE OF MATTER
Ranks-SUBCLASS = SUBCLASS
Ranks-Subclass = Subclase
Ranks-SUBFAMILY = SUBFAMILY
Ranks-Subfamily = Subfamilia
Ranks-SUBGENUS = SUBGENUS
Ranks-Subgenus = Subgénero
Ranks-SUBKINGDOM = SUBKINGDOM
Ranks-Subkingdom = Subreino
Ranks-SUBORDER = SUBORDER
Ranks-Suborder = Suborden
Ranks-SUBPHYLUM = SUBPHYLUM
Ranks-Subphylum = Subfilo
Ranks-SUBSECTION = SUBSECTION
Ranks-Subsection = Subsección
Ranks-SUBSPECIES = SUBSPECIES
Ranks-Subspecies = Subespecie
Ranks-SUBTERCLASS = SUBTERCLASS
Ranks-Subterclass = Subterclase
Ranks-SUBTRIBE = SUBTRIBE
Ranks-Subtribe = Subtribu
Ranks-SUPERCLASS = SUPERCLASS
Ranks-Superclass = Superclase
Ranks-SUPERFAMILY = SUPERFAMILY
Ranks-Superfamily = Superfamilia
Ranks-SUPERORDER = SUPERORDER
Ranks-Superorder = Superorden
Ranks-SUPERTRIBE = SUPERTRIBE
Ranks-Supertribe = Supertribu
Ranks-TRIBE = TRIBE
Ranks-Tribe = Tribu
Ranks-VARIETY = VARIETY
Ranks-Variety = Variedad
Ranks-ZOOSECTION = ZOOSECTION
Ranks-Zoosection = Zoosección
Ranks-ZOOSUBSECTION = ZOOSUBSECTION
Ranks-Zoosubsection = Zoosubsección
Read-more-on-Wikipedia = Read more on Wikipedia
Record-a-sound = Record a sound
Record-animal-sounds = Record animal sounds
RECORD-NEW-SOUND = RECORD NEW SOUND
RECORD-SOUND = RECORD SOUND
Record-verb = Registro
Recording-sound = Recording sound
Recording-stopped-Tap-to-play-the-current-recording = Recording stopped. Tap to play the current recording.
REDO-SEARCH-IN-MAP-AREA = REDO SEARCH IN MAP AREA
Remove-agreement = Remove agreement
Remove-disagreement = Remove disagreement
Remove-favorite = Remove favorite
Remove-identification = Eliminar identificación
Remove-Photos = Remove Photos
Remove-project-filter = Eliminar filtro de proyecto
Remove-taxon-filter = Remove taxon filter
Remove-user-filter = Remove user filter
Removes-this-observations-taxon = Removes this observation's taxon
Removes-your-vote-of-agreement = Removes your vote of agreement
Removes-your-vote-of-disagreement = Removes your vote of disagreement
Research-Grade--quality-grade = Calificación de la investigación
RESEARCH-GRADE--quality-grade = RESEARCH GRADE
Research-Grade-Status = Research Grade Status
RESET-PASSWORD = RESET PASSWORD
RESET-RECORDING = RESET RECORDING
RESET-SEARCH = RESET SEARCH
RESET-SOUND-header = RESET SOUND?
Reset-verb = Restablecer
RESTART-APP = RESTART APP
Restore = Restaurar
Reveal = Reveal
REVIEW-INATURALIST = REVIEW INATURALIST
REVIEWED = REVIEWED
Reviewed-observations-only = Reviewed observations only
Satellite--map-type = Satélite
SAVE = GUARDAR
Save = Guardar
SAVE-ALL = SAVE ALL
Save-all-observations = Guardar todas las observaciones
SAVE-CHANGES = SAVE CHANGES
SAVE-FOR-LATER = SAVE FOR LATER
SAVE-LOCATION = SAVE LOCATION
SAVE-PHOTOS = SAVE PHOTOS
Save-photos-to-your-library = Save photos to your library
Saved-Observation = Saved observation, in queue to upload
Scientific-Name = Nombre científico
Scientific-Name-Common-Name = Scientific Name (Common Name)
SEARCH = SEARCH
Search = Buscar
Search-for-a-project = Search for a project
SEARCH-FOR-A-TAXON = SEARCH FOR A TAXON
Search-for-a-taxon = Search for a taxon
SEARCH-LOCATION = SEARCH LOCATION
SEARCH-PROJECTS = SEARCH PROJECTS
Search-suggestions-with-location = Search suggestions with location
Search-suggestions-without-location = Search suggestions without location
SEARCH-TAXA = SEARCH TAXA
SEARCH-USERS = SEARCH USERS
See-observations-by-this-user-in-Explore = See observations by this user in Explore
See-observations-of-this-taxon-in-explore = See observations of this taxon in explore
See-project-members = See project members
See-species-observed-by-this-user-in-Explore = See species observed by this user in Explore
Select-a-date-and-time-for-observation = Select a date and time for observation
Select-captive-or-cultivated-status = Select captive or cultivated status
Select-geoprivacy-status = Select geoprivacy status
Select-or-drag-media = Select or drag media
Select-photo = Select photo
SELECT-THIS-TAXON = SELECT THIS TAXON
Select-user = Select user
Selects-iconic-taxon-X-for-identification = Selects iconic taxon { $iconicTaxon } for identification.
Separate-Photos = Separate Photos
September = Septiembre
SETTINGS = SETTINGS
Share = Comparte
SHARE-DEBUG-LOGS = SHARE DEBUG LOGS
Share-location = Compartir ubicación
Share-map = Share map
Share-your-observation-where-it-can-help-scientists = Share your observation, where it can help scientists across the world better understand biodiversity.
SHOP-INATURALIST-MERCH = SHOP INATURALIST MERCH
Show-observation-options = Show observation options.
Showing-offline-search-results--taxa = Showing offline search results. To search for more species, try again when connected to the Internet.
Shows-identification-suggestions = Shows identification suggestions
Shows-iNaturalist-bird-logo = Shows iNaturalist bird logo.
Shows-observation-creation-options = Shows observation creation options
Sign-in-with-Apple = Sign in with Apple
Sign-in-with-Apple-Failed = Sign in with Apple Failed
Sign-in-with-Google = Sign in with Google
Sign-in-with-Google-Failed = Sign in with Google Failed
Skip-additional-suggestions = Skip additional suggestions
Skip-for-now = Skip for now
Something-went-wrong = Something went wrong.
Sorry-this-observation-was-deleted = Sorry, this observation was deleted
Sorry-we-dont-know-how-to-open-that-URL = Sorry, we don't know how to open that URL: { $url }
SORT-BY = SORT BY
Sort-by = Ordenar por
sound-playback-separator = /
Sound-recorder = Sound recorder
sound-recorder-help-A-recording-of = A recording of 5-15 seconds is best to help identifiers.
sound-recorder-help-Get-as-close-as-you-can = Get as close as you safely can to record the organism.
sound-recorder-help-Get-closer = Get closer
sound-recorder-help-Keep-it-short = Keep it short
sound-recorder-help-Make-sure = Make sure the sound of your own movement doesn’t cover up the sound of the organism.
sound-recorder-help-One-organism = One organism
sound-recorder-help-Stop-moving = Stop moving
sound-recorder-help-Try-to-isolate = Try to isolate the sound of a single organism. If you can’t, make sure to leave a note of which organism you’re recording.
Sounds = Sonidos
Source-List = <0>(Source List: </0><1>{ $source }</1><0>)</0>
Spam = Spam
Spam-Examples = Anuncia algo, los enlaces no son validos, etc.
Species = Especies
Species-View = Species View
SPECIES-WITHOUT-NUMBER =
    { $count ->
        [one] SPECIES
       *[other] SPECIES
    }
Standard--map-type = Estándar
Start-must-be-before-end = The start date must be before the end date.
Start-upload = Start upload
Starts-recording-sound = Starts recording sound
Stay-on-this-screen = Stay on this screen while your location loads.
Still-need-help = Still need help? You can file a support request here.
Stop-upload = Stop upload
Stop-verb = Parar
Stops-recording-sound = Stops recording sound
SUBMIT = SUBMIT
SUBMIT-ID-SUGGESTION = SUBMIT ID SUGGESTION
SUGGEST-ID = SUGGEST ID
Suggest-ID = SUGGEST ID
supporting--identification = Coincidente
Switches-to-tab = Switches to { $tab } tab.
Sync-observations = Sync observations
Syncing = Sincronizando...
Take-multiple-photos-of-a-single-organism = Take multiple photos of a single organism
Take-photo = Take photo
Taxa = Taxones
TAXON = TAXON
TAXON-NAMES-DISPLAY = TAXON NAMES DISPLAY
TAXONOMIC-RANKS = TAXONOMIC RANKS
TAXONOMY-header = TAXONOMY
TEAM = TEAM
Terms-of-Use = Condiciones de uso
TERMS-OF-USE = TERMS OF USE
Text-Box-to-Describe-Reason-for-Flag = Text box to describe reason for flag.
Thank-you-for-sharing-your-feedback = Thank you for sharing your feedback to help us improve!
Thanks-for-using-any-suggestions = Thanks for using this app! Do you have any suggestions for the people who make it?
That-email-is-already-associated-with-an-account = That email is already associated with an account.
That-user-profile-doesnt-exist = That user profile doesn't exist
That-username-is-unavailable = That username is unavailable
The-AI-is-not-confident-It-may-be-one-of-the-IDs-below = The AI is not confident. It may be one of the IDs below.
The-AI-is-not-confident-Upload-to-ask-the-community = The AI is not confident. Upload to ask the community.
The-exact-location-will-be-hidden = The exact location will be hidden publicly, and instead generalized to a larger area. (Threatened and endangered species are automatically obscured).
The-iNaturalist-community-will-help-verify-and-refine-identifications = The iNaturalist community will help verify and refine identifications on your observations to create Research Grade data for science and conservation.
The-iNaturalist-Network = The iNaturalist network is a collection of localized websites that are fully connected to the global iNaturalist community. Network sites are supported by local institutions that promote local use and facilitate the use of data from iNaturalist to benefit local biodiversity.
The-location-will-not-be-visible-to-others = The location will not be visible to others, which might make the observation impossible to identify
The-models-that-suggest-species = The models that suggest species based on visual similarity and location are thanks in part to collaborations with Sara Beery, Tom Brooks, Elijah Cole, Christian Lange, Oisin Mac Aodha, Pietro Perona, and Grant Van Horn.
This-is-a-wild-organism = This is a wild organism and wasn't placed in this location by humans.
This-is-how-taxon-names-will-be-displayed = This is how all taxon names will be displayed to you across iNaturalist:
This-is-your-identification-other-people-may-help-confirm-it = This is your identification. Other people may help confirm it!
This-may-take-a-few-seconds = This may take a few seconds.
This-observation-has-no-comments-or-identifications-yet = This observation has no comments or identifications yet.
This-observation-has-not-met-the-conditions-required-to-meet-Research-Grade = This observation has not met the conditions required to meet Research Grade status
This-observation-is-not-eligible-for-research-grade-status = This observation is not eligible for research grade status. Learn more in the Data Quality Assessment below.
This-observation-is-research-grade-and-can-be-used-by-scientists = This observation is research grade and can be used by scientists!
This-observation-needs-more-identifications = This observation needs more identifications to reach Research Grade status
This-observation-needs-more-identifications-to-become-research-grade = This observation needs more identifications to become research grade.
This-observer-has-opted-out-of-the-Community-Taxon = This observer has opted out of the Community Taxon
This-organism-was-placed-by-humans = This organism was placed in this location by humans. This applies to things like garden plants, pets, and zoo animals.
To-sync-your-observations-to-iNaturalist = To sync your observations to iNaturalist, please log in.
To-view-nearby-organisms-please-enable-location = To view nearby organisms, please enable location.
To-view-nearby-projects-please-enable-location = To view nearby projects, please enable location.
Toggle-map-type = Toggle map type
TOP-ID-SUGGESTION = TOP ID SUGGESTION
Traditional-Project = Proyecto tradicional
Umbrella-Project = Proyecto sombrilla
UNFOLLOW = UNFOLLOW
UNFOLLOW-USER = UNFOLLOW USER?
Unknown--rank = Desconocido
Unknown--taxon = Desconocido
Unknown--user = Desconocido
Unknown-error = Error desconocido
Unknown-organism = Unknown organism
Unreviewed-observations-only = Unreviewed observations only
Upload-Complete = Upload Complete
Upload-in-progress = Upload in progress
UPLOAD-NOW = UPLOAD NOW
Upload-photos-from-your-photo-library = Upload multiple photos from your photo library
Upload-Progress = Upload { $uploadProgress } percent complete
UPLOAD-TO-INATURALIST = UPLOAD TO INATURALIST
Upload-x-observations =
    Upload { $count ->
        [one] 1 observation
       *[other] { $count } observations
    }
Upload-your-observations-to-contribute-data-to-help-save-species = Upload your observations to contribute data to help save species.
Uploaded-via-application = Uploaded via: { $application }
Uploading-x-of-y = Uploading { $currentUploadCount } of { $total }
Uploading-x-of-y-observations =
    { $total ->
        [one] Uploading { $currentUploadCount } observation
       *[other] Uploading { $currentUploadCount } of { $total } observations
    }
Use-iNaturalist-to-identify-any-living-thing = Use iNaturalist to identify any living thing
Use-iNaturalists-AI-Camera = Use iNaturalist's AI Camera to identify organisms in real time
USE-LOCATION = USE LOCATION
Use-the-devices-other-camera = Use the device's other camera.
Use-the-iNaturalist-camera-to-see-real-time-identifications-and-take-photos = Use the iNaturalist camera to see real-time identifications and take photos!
Use-your-devices-microphone-to-record-animal-sounds-and-share-them = Use your device’s microphone to record animal sounds and share them to get identifications and contribute to science!
USER = USER
User = User { $userHandle }
USERNAME-OR-EMAIL = USERNAME OR EMAIL
Users = Usuarios
Using-location = Using location
Verified-IDs-are-used-for-science-and-conservation = Verified IDs are used for science and conservation
Version-app-build = Version { $appVersion } ({ $buildVersion })
View-Advanced-Settings = View Advanced Settings
VIEW-ALL-X-PLACES = VIEW ALL { $count } PLACES
VIEW-ALL-X-PROJECTS = VIEW ALL { $count } PROJECTS
VIEW-ALL-X-TAXA = VIEW ALL { $count } TAXA
VIEW-ALL-X-USERS = VIEW ALL { $count } USERS
VIEW-CHILDREN-TAXA = VIEW CHILDREN TAXA
VIEW-DATA-QUALITY-ASSESSMENT = VIEW DATA QUALITY ASSESSMENT
VIEW-EDUCATORS-GUIDE = VIEW EDUCATOR'S GUIDE
VIEW-FOLLOWERS = VIEW FOLLOWERS
VIEW-FOLLOWING = VIEW FOLLOWING
View-in-browser = Ver en el navegador
VIEW-IN-EXPLORE = VIEW IN EXPLORE
VIEW-INATURALIST-HELP = VIEW INATURALIST HELP
View-photo = View photo
View-photo-licensing-info = View photo licensing info
VIEW-PROJECT-REQUIREMENTS = VIEW PROJECT REQUIREMENTS
VIEW-PROJECTS = VIEW PROJECTS
View-suggestions = Ver sugerencias
Watch-your-notifications-for-identifications = Watch your notifications for identifications!
We-are-not-confident-enough-to-make-a-top-ID-suggestion = We’re not confident enough to make a top ID suggestion, but here are some other suggestions:
Welcome-back = Welcome back!
WHAT-IS-INATURALIST = WHAT IS INATURALIST?
Whats-more-by-recording = What's more, by recording and sharing your observations, you'll create research-quality data for scientists working to better understand and protect nature. So if you like recording your findings from the outdoors, or if you just like learning about life, join us!
When-tapping-the-green-observation-button = When tapping the green observation button, open:
WIKIPEDIA = WIKIPEDIA
Wild = Silveste
WILD-STATUS = WILD STATUS
Withdraw = Retirar
WITHDRAW-ID = WITHDRAW ID
WITHDRAW-ID-QUESTION = WITHDRAW ID?
Withdraws-identification = Withdraws identification
Worldwide = Mundial
WORLDWIDE = WORLDWIDE
Would-you-like-to-discard-your-current-recording-and-start-over = Would you like to discard your current recording and start over?
Would-you-like-to-suggest-the-following-identification = Would you like to suggest the following identification?
x-comments =
    { $count ->
        [one] { $count } comment
       *[other] { $count } comments
    }
x-failed =
    { $count ->
        [one] { $count } failed
       *[other] { $count } failed
    }
X-FOLLOWERS =
    { $count ->
        [one] { $count } FOLLOWER
       *[other] { $count } FOLLOWERS
    }
X-Identifications =
    { $count ->
        [one] { $count } Identification
       *[other] { $count } Identifications
    }
x-identifications =
    { $count ->
        [one] { $count } identification
       *[other] { $count } identifications
    }
X-Identifiers =
    { $count ->
        [one] { $count } Identifier
       *[other] { $count } Identifiers
    }
X-MEMBERS = { $count } MEMBERS
X-Observations =
    { $count ->
        [one] 1 Observation
       *[other] { $count } Observations
    }
X-OBSERVATIONS--below-number =
    { $count ->
        [one] OBSERVATION
       *[other] OBSERVATIONS
    }
X-observations-deleted =
    { $count ->
        [one] 1 observation deleted
       *[other] { $count } observations deleted
    }
X-observations-uploaded =
    { $count ->
        [one] 1 observation uploaded
       *[other] { $count } observations uploaded
    }
X-Observers =
    { $count ->
        [one] { $count } Observer
       *[other] { $count } Observers
    }
X-of-Y =
    { $x ->
        [one] 1
       *[other] { $x }
    } { $y ->
        [one] of { $y }
       *[other] of { $y }
    }
X-percent = { $count }%
X-percent-confidence = { $count }% confidence
X-PHOTOS =
    { $photoCount ->
        [one] 1 PHOTO
       *[other] { $photoCount } PHOTOS
    }
X-PHOTOS-X-OBSERVATIONS =
    { $photoCount ->
        [one] 1 PHOTO
       *[other] { $photoCount } PHOTOS
    }, { $observationCount ->
        [one] 1 OBSERVATION
       *[other] { $observationCount } OBSERVATIONS
    }
X-PHOTOS-Y-SOUNDS =
    { $photoCount ->
        [one] 1 PHOTO
       *[other] { $photoCount } PHOTOS
    }, { $soundCount ->
        [one] 1 SOUND
       *[other] { $soundCount } SOUNDS
    }
X-PROJECTS =
    { $projectCount ->
        [one] { $projectCount } PROYECTO
       *[other] { $projectCount } PROYECTOS
    }
x-saved =
    { $count ->
        [one] { $count } saved
       *[other] { $count } saved
    }
X-SOUNDS =
    { $count ->
        [one] 1 SOUND
       *[other] { $count } SOUNDS
    }
X-Species =
    { $count ->
        [one] { $count } Species
       *[other] { $count } Species
    }
X-SPECIES--below-number =
    { $count ->
        [one] SPECIES
       *[other] SPECIES
    }
x-uploaded =
    { $count ->
        [one] { $count } uploaded
       *[other] { $count } uploaded
    }
x-uploading =
    { $count ->
        [one] { $count } uploading
       *[other] { $count } uploading
    }
x-uploads-failed =
    { $count ->
        [one] { $count } upload failed
       *[other] { $count } uploads failed
    }
You-are-offline = You are offline
You-are-offline-Tap-to-reload = You are offline. Tap to reload.
You-are-offline-Tap-to-try-again = You are offline. Tap to try again.
You-can-add-up-to-20-media = You can add up to 20 photos and 20 sounds per observation.
You-can-also-check-out-merchandise = You can also check out merchandise for iNaturalist and Seek at our store below!
You-can-click-join-on-the-project-page = You can click “join” on the project page.
You-can-find-answers-on-our-help-page = You can find answers on our help page.
You-can-now-upload-your-observations-to-iNaturalist-and-contribute = You can now upload your observations to iNaturalist and contribute to global biodiversity research.
You-can-only-add-20-photos-per-observation = You can only add 20 photos per observation
You-can-still-share-the-file = You can still share the file with another app. If you can email it, please send it to { $email }
You-can-upload-this-observation-to-our-community = You can upload this observation to our community to get an identification from a real person, and help our AI improve its identifications in the future
You-changed-filters-will-be-discarded = You changed filters, but they were not applied to your explore search results.
You-have-opted-out-of-the-Community-Taxon = You have opted out of the Community Taxon
You-havent-joined-any-projects-yet = You haven’t joined any projects yet!
You-havent-observed-any-species-yet = You haven't observed any species yet.
You-likely-observed-a-new-species = You likely observed a new species!
You-likely-observed-a-species = You likely observed a species
You-likely-observed-an-organism-in-this-group = You likely observed an organism in this group
You-may-have-observed-a-new-species = You may have observed a new species!
You-may-have-observed-a-species = You may have observed a species
You-may-have-observed-an-organism-in-this-group = You may have observed an organism in this group
You-may-notice-changes-to-how-things-look-and-flow = You may notice changes to how things look and flow. You can control your options in the settings.
You-must-be-logged-in-to-view-messages = You must be logged in to view messages
You-must-install-Google-Play-Services-to-sign-in-with-Google = You must install Google Play Services to sign in with Google.
You-need-an-Internet-connection-to-do-that = You need an Internet connection to do that.
You-need-log-in-to-do-that = Debes iniciar sesión para hacer eso.
You-observed-a-new-species = You observed a new species!
You-observed-a-species = You observed a species
You-observed-an-organism-in-this-group = You observed an organism in this group
You-will-see-notifications = You’ll see notifications here once you log in & upload observations.
Your-donation-to-iNaturalist = Your donation to iNaturalist supports the improvement and stability of the mobile apps and website that connects millions of people to nature and enables the protection of biodiversity worldwide!
Your-email-is-confirmed = Your email is confirmed! Please log in to continue.
Your-location-uncertainty-is-over-x-km = Your location uncertainty is over { $x } km, which is too high to be helpful to identifiers. Edit the location and zoom in until the accuracy circle turns green and is centered on where you observed the organism.
Your-observations-can-help-science = Your observations can help science!
Youre-ready-to-share-your-observations = You’re ready to share your observations!
Youve-denied-permission-prompt = You’ve denied permission. Please grant permission in the settings app.
Youve-previously-denied-camera-permissions = You've previously denied camera permissions, so please enable them in settings.
Youve-previously-denied-location-permissions = You’ve previously denied location permissions, so please enable them in settings.
Youve-previously-denied-microphone-permissions = You’ve previously denied microphone permissions, so please enable them in settings.
Zoom-in-as-much-as-possible-to-improve = Zoom in as much as possible to improve location accuracy and get better identifications.
Zoom-to-current-location = Zoom to current location
zoom-x = { $zoom }×
