### DO NOT EDIT THIS FILE!
###
### This file came from Crowdin and was normalized by ftl.js.
### It will be overwritten during the next translation sync. To add
### translations, go to https://crowdin.com/editor/inaturalistios/724
###

A-global-community-for-nature = A global community for nature
ABOUT = INFO
ABOUT-COLLECTION-PROJECTS = KOGUMISPROJEKTIDEST
ABOUT-INATURALIST = INATURALISTIST
ABOUT-THE-DQA = ANDMETE KVALITEEDIHINNANGUST
About-the-DQA-description = Kvaliteedihinnang võtab kokku iNaturalisti vaatluse liigilise ja asukohalise täpsuse, täielikkuse, asjakohasuse ja sobivuse bioloogilise mitmekesisuse andmeteks. Mõned omadused määratakse automaatselt, teised aga iNaturalisti kasutajate poolt hääletuse abil. iNaturalist jagab litsentseeritud "teaduskõlbulike" vaatlusi mitmete andmepartneritega kasutamiseks teaduses ja looduskaitses.
ABOUT-TRADITIONAL-PROJECTS = TAVAPROJEKTIDEST
ABOUT-UMBRELLA-PROJECTS = ÜLEMPROJEKTIDEST
accessible-comname-sciname = { $commonName } ({ $scientificName })
accessible-sciname-comname = { $scientificName } ({ $commonName })
Account-Deleted = Konto kustutatud
ACCOUNT-SETTINGS = KONTO SÄTTED
ACTIVITY = SÜNDMUSED
Add-agreement = Nõustu
ADD-AN-ID = LISA MÄÄRATLUS
Add-an-ID-Later = Lisa määratlus hiljem
ADD-COMMENT = LISA KOMMENTAAR
Add-Date-Time = Lisa kuupäev/kellaaeg
Add-disagreement = Ära nõustu
ADD-EVIDENCE = LISA TÕEND
Add-evidence = Lisa tõend
Add-favorite = Lisa lemmikuks
Add-Location = Lisa asukoht
Add-location-for-better-identifications = Lisa paremaks määratlemiseks asukoht
ADD-LOCATION-FOR-BETTER-IDS = LISA PAREMAKS MÄÄRATLEMISEKS ASUKOHT
Add-location-to-refresh-suggestions = Soovituste uuendamiseks lisa asukoht
Add-observations = Lisa vaatluseid
ADD-OPTIONAL-COMMENT = LISA SOOVIKORRAL KOMMENTAAR
Add-optional-notes = Lisa soovi korral märkuseid
Adds-ID = Adds ID
Adds-your-vote-of-agreement = Lisab sinupoolse nõustumise
Adds-your-vote-of-disagreement = Lisab sinupoolse mitte nõustumise
Advanced-Settings = Advanced Settings
ADVANCED-SETTINGS = ADVANCED SETTINGS
Affiliation = Kuuluvus: { $site }
After-capturing-or-importing-photos-show = After capturing or importing photos, show:
Agree = Nõustun
AGREE = NÕUSTUN
AGREE-WITH-ID = NÕUSTUS MÄÄRATLUSEGA?
Agree-with-ID-description = Sooviksid sa määratlusega nõusutuda ja seda omalt poolt välja pakkuda?
AI-Camera = AI-kaamera
ALL = KÕIK
All = Kõik
All-observation-options--list = All observation options: iNaturalist AI Camera, Standard Camera, Uploading from Photo Library, and Sound Recorder
All-observations = Kõik vaatlused
All-observations-need-a-date-and-location-to-be-used-for-science = All observations need a date and location to be used for science. Please edit observations if they need more information.
All-organisms = Kõik organismid
all-rights-reserved = kõig õigused kaitstud
All-taxa = Kõik taksonid
ALL-USERS-EXCEPT = KÕIK KASUTAJAD PEALE
ALLOW-LOCATION-ACCESS = LUBA LIGIPÄÄSU ASUKOHALE
An-Internet-connection-is-required = Vaatluste juurde laadimiseks vajad interneti ühendust.
Any--date = Kõik
Any--establishment-means = Kõik
Any--media-type = Kõik
Any--project = Kõik
Any--quality-grade = Kõik
Any--user = Kõik
Anyone-using-iNaturalist-can-see = Kõik iNaturalisti kasutajad näevad, kus seda liiki vaadeldi, ning teadlased saavad seda lihtsamail moel teaduses kasutada.
APP-LANGUAGE = RAKENDUSE KEEL
apple-full-name = { JOIN($namePrefix, $givenName, $middleName, $nickname, $familyName, $nameSuffix, separator: " ") }
APPLY-FILTERS = LISA FILTRID
Apply-filters = Lisa filtrid
April = aprill
Are-you-an-educator = Oled sa õpetaja, kes soovib iNaturalisti koos oma õpilastega kasutada?
Are-you-sure-you-want-to-log-out = Oled kindel, et soovid iNaturalisti kontolt välja logida? Kõik vaatlused, mida pole iNaturalisti üles laetud, kustutatakse.
attribution-cc-by = mõned õigused kaitstud (CC BY)
attribution-cc-by-nc = mõned õigused kaitstud (CC BY-NC)
attribution-cc-by-nc-nd = mõned õigused kaitstud (CC BY-NC-ND)
attribution-cc-by-nc-sa = mõned õigused kaitstud (CC BY-NC-SA)
attribution-cc-by-nd = mõned õigused kaitstud (CC BY-ND)
attribution-cc-by-sa = mõned õigused kaitstud (CC BY-SA)
August = august
BACK-TO-LOGIN = TAGASI SISSELOGIMA
BLOG = BLOGI
Bulk-importer = Mass-importija
By-exiting-changes-not-saved = Väljudes ei salvestata muutuseid sinu vaatlusele.
By-exiting-observation-not-saved = Väljudes su vaatlust ei salvestata.
By-exiting-your-observations-not-saved = Väljudes su vaatluseid ei salvestata. Võid need enda seadmesse salvestada või kustutada.
By-exiting-your-photos-will-not-be-saved = Väljudes su fotosid ei salvestata.
By-exiting-your-recorded-sound-will-not-be-saved = Väljudes sinu heli ei salvestata.
BY-ME = MINU
By-uploading-your-observation-to-iNaturalist-you-can = Oma vaatluseid iNaturalisti laadides saad:
Camera = Kaamera
CANCEL = KATKESTA
Cancel = Loobu
Captive-Cultivated = Vangistatud/kultiveeritud
Casual--quality-grade = Juhuvaatlus
CC-BY = CC BY
CC-BY-NC = CC BY-NC
CC-BY-NC-ND = CC BY-NC-ND
CC-BY-NC-SA = CC BY-NC-SA
CC-BY-ND = CC BY-ND
CC-BY-SA = CC BY-SA
CC0 = CC0
CHANGE-APP-LANGUAGE = MUUDA RAKENDUSE KEELT
CHANGE-DATE = MUUDA KUUPÄEVA
Change-date = Muuda kuupäeva
CHANGE-END-DATE = MUUDA LÕPUKUUPÄEVA
Change-end-date = Muuda lõpukuupäeva
Change-project = Muuda projekti
CHANGE-START-DATE = MUUDA ALGUSKUUPÄEVA
Change-start-date = Muuda alguskuupäeva
Change-taxon = Muuda taksonit
Change-taxon-filter = Muuda taksonifiltrit
Change-user = Muuda kasutajat
Change-zoom = Muuda suurendusastet
CHECK-YOUR-EMAIL = KONTROLLI OMA E-POSTI!
CHOOSE-A-USERNAME = VALI KASUTAJANIMI
Choose-taxon = Vali takson
Choose-top-taxon = Vali kõrgeima taseme takson
Clear = Tühjenda
Close = Sulge
Close-permission-request-screen = Sulge loa nõutamise aken
Close-search = Sulge otsing
Closes-explanation = Closes explanation
Closes-introduction = Sulge sissejuhatus
Closes-new-observation-explanation = Closes new observation explanation.
Closes-new-observation-options = Sulge uue vaatluse sätted.
Closes-withdraw-id-sheet = Sulge "Määratluse tagasivõtmise" leht
COLLABORATORS = KAASAAITAJAD
Collection-Project = Kogumisprojekt
Combine-Photos = KOMBINEERI FOTOD
COMMENT = KOMMENTEERI
Comment-options = Kommentaari sätted
Common-Name-Scientific-Name = Rahvapärane nimetus (Teaduslik nimetus)
Community-Discussion = Community Discussion
Community-Guidelines = Kogukonna reeglid
COMMUNITY-GUIDELINES = KOGUKONNA REEGLID
Confidence--label = Confidence
CONFIRM = KINNITA
Congratulations-You-made-your-first-observation = Congratulations! You made your first observation!
Connect-with-expert-naturalists = Connect with expert naturalists
Connect-with-other-naturalists = Suhtle teise loodusarmastajatega ja osale vestlustes.
Connection-problem-Please-try-again-later = Ühenduse probleem. Palun proovi hiljem uuesti.
CONTACT-SUPPORT = KONTAKTEERU KASUTAJATOEGA
CONTINUE = JÄTKA
Coordinates-copied-to-clipboard = Kooridnaadid kopeeritud
Copy-coordinates = Kopeeri koordinaadid
Copyright = Autoriõigused
Could-not-find-a-camera-on-this-device = Selle seadme kaamerat ei leitud
Couldnt-create-comment = Kommentaari ei õnnestunud luua
Couldnt-create-identification-error = Vaatlust ei õnnestunud luua { $error }
Couldnt-create-identification-unknown-error = Määratlust ei õnnestunud luua, tundmatu viga.
CREATE-AN-ACCOUNT = LOO KONTO
Create-an-observation-evidence = Loo ilma tõendusmaterjalita vaatlus
DATA-QUALITY = ANDMETE KVALITEET
DATA-QUALITY-ASSESSMENT = ANDMETE KVALITEED HINNANG
Data-Quality-Assessment = Data Quality Assessment
Data-quality-assessment-can-taxon-still-be-confirmed-improved-based-on-the-evidence = Kas kogukondliku taksonit saab tõendusmaterjalist lähtuvalt täpsustada?
Data-quality-assessment-community-taxon-species-level-or-lower = Kogukondlik takson on liigi tasemel või täpsem
Data-quality-assessment-date-is-accurate = Kuupäev on täpne
Data-quality-assessment-date-specified = Kuupäev määratud
Data-quality-assessment-description-casual = See vaatlus ei vasta teaduskõlbulikkuse tingimustele.
Data-quality-assessment-description-needs-id = See vaatlus ei vasta veel teaduskõlbulikkuse tingimustele:
Data-quality-assessment-description-research = Seda saab nüüd kasutada teadustööks ja näidata teistel veebilehtedel.
Data-quality-assessment-evidence-of-organism = Tõendid organismi kohta
Data-quality-assessment-has-photos-or-sounds = On piltide ja helidega
Data-quality-assessment-id-supported-by-two-or-more = On kahe või enama kasutaja poolt määratud
Data-quality-assessment-location-is-accurate = Asukoht on täpne
Data-quality-assessment-location-specified = Asukoht määratud
Data-quality-assessment-organism-is-wild = Organism on metsik
Data-quality-assessment-recent-evidence-of-organism = Hiljutised tõendid organismi kohta
Data-quality-assessment-single-subject = Ühe isendiga seotud tõendusmaterjal
Data-quality-assessment-title-casual = See vaatlus on juhuvaatlus
Data-quality-assessment-title-needs-id = See vaatlus vajab määratlust
Data-quality-assessment-title-research = See vaatlus on teaduskõlbulik!
DATE = KUUPÄEV
Date = Kuupäev
date-format-long = d. MMM y
date-format-month-day = d. MMM
date-format-month-year = MMMM y
date-format-short = dd.MM.yy
DATE-OBSERVED = VAATLUSKUUPÄEV
Date-observed = Vaatluskuupäev
Date-observed-header-short = Vaadeldud
DATE-OBSERVED-NEWEST = VAATLUSKUUPÄEV - UUEMAST VANEMAKS
DATE-OBSERVED-OLDEST = VAATLUSKUUPÄEV - VANEMAST UUEMAKS
Date-Range = Kuupäevavahemik
DATE-RANGE = KUUPÄEVAVAHEMIK
date-to-date = { $d1 }–{ $d2 }
DATE-UPLOADED = ÜLESLAADIMISE KUUPÄEV
Date-uploaded = Üleslaadimise kuupäev
Date-uploaded-header-short = Üleslaetud
DATE-UPLOADED-NEWEST = ÜLESLAADIMISE KUUPÄEV - UUEMAST VANEMAKS
DATE-UPLOADED-OLDEST = ÜLESLAADIMISE KUUPÄEV - VANEMAST UUEMAKS
Date-uploaded-on-header-short = Uploaded on:
datetime-difference-days = { $count } p
datetime-difference-hours = { $count } t
datetime-difference-minutes = { $count } m
datetime-difference-weeks = { $count } n
datetime-format-long = Pp
datetime-format-long-with-zone = Pp (zzz)
datetime-format-short = dd.MM.yy hh.mm
datetime-format-short-with-zone = M/d/yy h:mm a zzz
December = detsember
DELETE = KUSTUTA
Delete-all-observations = Kustuta kõik vaatlused
Delete-comment = Kustuta kommentaar
DELETE-COMMENT--question = KUSTUTA KOMMENTAAR?
Delete-current-observation = Kustuta see vaatlus
Delete-observation = Kustuta vaatlus
DELETE-OBSERVATION--question = KUSTUTA VAATLUS?
Delete-photo = Kustuta foto
Delete-sound = Kustuta heli
Deletes-entered-text = Kustutab sisestatud teksti
Deleting-x-of-y--observations =
    Kustutan { $currentDeleteCount } { $total ->
        [one] / { $total }
       *[other] / { $total } vaatlust
    }
Deleting-x-of-y-observations-2 =
    Kustutan { $currentDeleteCount } { $total ->
        [one] vaatlust
       *[other] / { $total } vaatlust
    }
Details = Details
DETAILS = DETAILSEM
Device-storage-full = Seadme mälu täis
Device-storage-full-description = iNaturalist ei pruugi suuta su fotosid salvestada või võib kokku joosta.
Disable-flash = Lülita välk välja
Disable-location = Disable location
Disagreement = *@{ $username } ei arva, et tegu on taksoniga <0/>
DISCARD = EEMALDA
DISCARD-ALL = EEMALDA KÕIK
DISCARD-CHANGES = KAOTA MUUTUSED
DISCARD-FILTER-CHANGES = KAOTA FILTRI MUUTUSED
DISCARD-MEDIA--question = EEMALDA MEEDIA?
DISCARD-OBSERVATION = EEMALDA VAATLUS
DISCARD-PHOTOS--question = EEMALDA FOTOD?
DISCARD-RECORDING = EEMALDA HELI
DISCARD-SOUND--question = EEMALDA HELI?
DISCARD-X-OBSERVATIONS =
    { $count ->
        [one] EEMALDA VAATLUS
       *[other] EEMALDA { $count } VAATLUST
    }
DISCOVER-NATURE-AROUND-YOU = DISCOVER NATURE AROUND YOU
DISMISS = KATKESTA
Do-you-know-what-group-this-is-in = Do you know what group this is in?
DONATE = ANNETA
DONATE-TO-INATURALIST = ANNETA INATURALISTILE
DONE = VALMIS
Dont-have-an-account = <0>Don't have an account? </0><1>Sign up</1>
During-app-start-no-model-found = Rakenduse käivitamisel ei leitud masin-nägemismudelit. AI-kaamera ei toimi.
Edit = Muuda
EDIT-COMMENT = MUUDA KOMMENTAARI
Edit-comment = Muuda kommentaari
Edit-identification = Muuda määratlust
EDIT-LOCATION = MUUDA ASUKOHTA
Edit-location = Muuda asukohta
Edit-Observation = Muuda vaatlust
Edit-your-profile-change-your-settings = Muuda oma profiili, teavitus-sätteid ja teisi konto omadusi.
Edits-this-observations-taxon = Muuda selle vaatluse taksonit
EDUCATORS = HARIDUSTÖÖTAJAD
EMAIL = E-POST
EMAIL-DEBUG-LOGS = VEALOGID E-POSTI
Enable-flash = Välk sisse
Enable-location = Enable location
Enable-notifications = Enable notifications
Endemic = Endeemiline
Endemic-to-place = Endeemiline kohas { $place }
Error = Viga
ERROR = VIGA
ERROR-LOADING-DQA = VIGA HINNANGU LAADIMISEL
Error-title = Viga
ERROR-VOTING-IN-DQA = VIGA HINNANGU ANDMISEL
Error-voting-in-DQA-description = Sinu hinnang andmete kvaliteedile ei pruukinud salvestuda. Kontrolli oma internetiühendust ja proovi uuesti.
Establishment = Asutus
ESTABLISHMENT-MEANS = ASUSTAMISMEETOD
Every-observation-needs = Iga vaatlus vajab määrajate abistamiseks asukohta, kuupäeva ja kellaaega. Kui muretsed asukoha privaatsuse pärast, saad muuta geoprivaatsuse sätteid.
Every-time-a-collection-project = Every time a collection project's page is loaded, iNaturalist will perform a quick search and display all observations that match the project's requirements. It is an easy way to display a set of observations, such as for a class project, a park, or a bioblitz without making participants take the extra step of manually adding their observations to a project.
EVIDENCE = TÕENDID
Exact-Date = Täpne kuupäev
EXACT-DATE = TÄPNE KUUPÄEV
except = väljaarvatud
EXPAND-MAP = SUUREM KAART
Experts-help-verify-and-improve-IDs = Experts help verify and improve IDs
Explore = Avasta
EXPLORE = AVASTA
Explore-Filters = Filtreeri avastusi
EXPLORE-IDENTIFIERS = AVASTA MÄÄRATLEJAID
EXPLORE-OBSERVATIONS = AVASTA VAATLUSEID
EXPLORE-OBSERVERS = AVASTA VAATLEJAID
EXPLORE-SPECIES = AVASTA LIIKE
Failed-to-delete-sound = Heli kustutamine ebaõnnestus
Failed-to-log-in = Sisse logimine ebaõnnestus
FEATURED = OLULISED
February = veebruar
FEEDBACK = TAGASISIDE
Feedback-Submitted = Tagasiside edastatud...
Fetching-location = Otsin asukohta...
Filter = Filtreeri
FILTER-BY-A-PROJECT = FILTREERI PROJEKTI JÄRGI
FILTER-BY-A-USER = FILTREERI KASUTAJA JÄRGI
Filter-by-observed-between-dates = Filter by observations observed between two specific dates
Filter-by-observed-during-months = Filter by observations observed during specific months
Filter-by-observed-on-date = Filter by observations observed on a specific date
Filter-by-uploaded-between-dates = Filter by observations uploaded between two specific dates
Filter-by-uploaded-on-date = Filter by observations uploaded on a specific date
Filters = Filtrid
Flag-An-Item = Lisa märkus
Flag-Item-Description = Flagging brings something to the attention of volunteer site curators. Please don't flag problems you can address with identifications, the Data Quality Assessment, or by talking to the person who made the content.
Flag-Item-Other-Description = Mõni teine põhjus, mida saad allpool kirjeldada.
Flag-Item-Other-Input-Hint = Põhjus märkuse lisamiseks
Flagged = Märkusega
Flash = Flash
Flip-camera = Pööra kaamerat
FOLLOW = JÄLGI
FOLLOWING--notifications = FOLLOWING
FOLLOWING-X-PEOPLE =
    { $count ->
        [one] JÄLGIN { $count } INIMEST
       *[other] JÄLGIN { $count } INIMEST
    }
Forgot-Password = Unustasin salasõna
GEOPRIVACY = GEOPRIVAATSUS
Geoprivacy-status = Geoprivaatsus: { $status }
Get-an-instant-ID-of-any-plant-animal-fungus = Get an instant ID of any plant, animal, or fungus
Get-feedback-from-naturalists-and-experts-who-will-help-verify = Get feedback from naturalists and experts who will help verify and refine your identifications.
Get-your-identification-verified-by-real-people = Get your identification verified by real people in the iNaturalist community
Getting-an-even-more-accurate-ID = Getting an even more accurate ID...
Go-back = Tagasi
Google-Play-Services-Not-Installed = Google Play Services Not Installed
GRANT-PERMISSION = ANNA LUBA
Grant-Permission-title = Anna luba
Group-Photos = Grupeeri fotod
Group-photos-onboarding = Grupeeri fotod vaatlusteks, kuid ole kindel, et igas vaatluses oleks üks liik
HELP = ABI
Help-create-Research-Grade-data-used-in-science-and-conservation = Help create Research Grade data used in science and conservation.
Help-protect-species = Help protect species
Hide = Peida
Highest = Üldiseim
HIGHEST-RANK = Üldiseim tase
I-agree-to-the-Terms-of-Use = <0>I agree to the Terms of Use and Privacy Policy, and I have reviewed the Community Guidelines (</0><1>required</1><0>).</0>
Iconic-taxon-name = Iconic taxon name: { $iconicTaxon }
ID-Suggestions = ID Suggestions
ID-Withdrawn = Määratlus tagasivõetud
IDENTIFICATION = MÄÄRATLUS
Identification-options = Määratluse sätted
IDENTIFICATIONS-WITHOUT-NUMBER =
    { $count ->
        [one] MÄÄRATLUS
       *[other] MÄÄRATLUST
    }
Identifiers = Määrajad
Identifiers-View = Identifiers View
Identify-an-organism = Määratle organism
Identify-organisms-in-real-time-with-your-camera = Identify organisms in real time with your camera
Identify-species-anywhere = Identify species anywhere
If-an-account-with-that-email-exists = Kui selle e-posti aadressiga konto eksisteerib, oleme salasõna lähtestamise juhendi sinu e-postile saatnud.
If-you-have-an-existing-account-try-sign-in-reset = Kui sul on olemasolev iNaturalisti konto, proovi oma kasutajatunnuse ja salasõnaga sisse logida või oma salasõna kontoga seotud e-posti aadressi abil lähtestada.
If-you-hold-down-instead-of-tapping-the-camera-button-you-can = If you hold down (instead of tapping) the camera button, you can record sounds, take multiple photos, and import from your photo library.
If-you-leave-x-of-your-observations-removed =
    If you leave this traditional project, { $count ->
        [one] 1 of your observations
       *[other] { $count } of your observations
    } will also be removed from this project.
If-you-save-this-observation-and-upload-it-to-iNaturalist = If you save this observation and upload it to iNaturalist, other people may be able to help identify it.
If-you-want-to-collate-compare-promote = If you want to collate, compare, or promote a set of existing projects, then an Umbrella project is what you should use. For example the 2018 City Nature Challenge, which collated over 60 projects, made for a great landing page where anyone could compare and contrast each city's observations. Both Collection and Traditional projects can be used in an Umbrella project, and up to 500 projects can be collated by an Umbrella project.
If-youre-seeing-this-error = If you're seeing this and you're online, iNat staff have already been notified. Thanks for finding a bug! If you're offline, please take a screenshot and send us an email when you're back on the Internet.
IGNORE-LOCATION = IGNOREERI ASUKOHTA
Ignore-notifications = Ignore notifications
Ignoring-location = Ignoring location
Import-Photos-From = Impordi fotosid:
IMPORT-X-OBSERVATIONS =
    IMPORDI { $count ->
        [one] 1 VAATLUS
       *[other] { $count } VAATLUST
    }
Improve-suggestions-by-using-your-location = Improve suggestions by using your location
IMPROVE-THESE-SUGGESTIONS-BY-USING-YOUR-LOCATION = IMPROVE THESE SUGGESTIONS BY USING YOUR LOCATION
improving--identification = Täiendaja
INATURALIST-ACCOUNT-SETTINGS = INATURALISTI KONTO SÄTTED
iNaturalist-AI-Camera = iNaturalisti AI-kaamera
iNaturalist-can-save-photos-you-take-in-the-app-to-your-devices-library = iNaturalist can save photos you take in the app to your device’s library.
iNaturalist-can-use-your-location-to-give-you-better-identification-suggestions = iNaturalist can use your location to give you better identification suggestions. We also use it to help you find species seen nearby. Sharing your location makes it easier to create useful data for science.
INATURALIST-COMMUNITY = INATURALISTI KOGUKOND
INATURALIST-FORUM = INATURALISTI FOORUM
iNaturalist-has-no-ID-suggestions-for-this-photo = iNaturalist ei oska sellele fotole pakkuda ühtegi määratlust.
INATURALIST-HELP-PAGE = INATURALISTI ABILEHT
iNaturalist-helps-you-identify = iNaturalist helps you identify the plants and animals around you while generating data for science and conservation. Get connected with a community of millions scientists and naturalists who can help you learn more about nature!
iNaturalist-identification-suggestions-are-based-on = iNaturalist's identification suggestions are based on observations and identifications made by the iNaturalist community, including { $user1 }, { $user2 }, { $user3 }, and many others.
iNaturalist-is-a-501 = iNaturalist is a 501(c)(3) non-profit in the United States of America (Tax ID/EIN 92-1296468).
iNaturalist-is-loading-ID-suggestions = iNaturalist is loading ID suggestions...
iNaturalist-is-supported-by = iNaturalist is supported by an independent, 501(c)(3) nonprofit organization based in the United States of America. The iNaturalist platform includes this app, Seek by iNaturalist, the iNaturalist website, and more.
iNaturalist-is-supported-by-our-community = iNaturalist is supported by our amazing community. From everyday naturalists who add observations and identifications, to curators who manage our taxonomy and help with moderation, to the volunteer translators who make iNaturalist more accessible to worldwide audiences, to our community-based donors, we are extraordinarily grateful to all the people in our community who make iNaturalist the platform it is.
iNaturalist-mission-is-to-connect = iNaturalist's mission is to connect people to nature and advance biodiversity science and conservation.
INATURALIST-MISSION-VISION = INATURALISTI MISSIOON & VISIOON
INATURALIST-NETWORK = INATURALISTI VÕRGUSTIK
INATURALIST-SETTINGS = INATURALISTI SÄTTED
INATURALIST-STAFF = { $inaturalist }I MEESKOND
INATURALIST-STORE = INATURALISTI POOD
INATURALIST-TEAM = INATURALISTI MEESKOND
iNaturalist-users-who-have-left-an-identification = iNaturalist users who have left an identification on another user's observation
iNaturalist-users-who-have-observed = iNaturalist users who have observed a particular taxon at a particular time and place
iNaturalists-apps-are-designed-and-developed-3 = iNaturalisti rakendusi disainib, arendab ja toetab iNaturalist meeskond: Yaron Budowski, Amanda Bullington, Tony Iwane, Johannes Klein, Patrick Leary, Joanne Lin, Scott Loarie, Abhas Misraraj, Sylvain Morin, Carrie Seltzer, Alex Shepard, Thea Skaff, Angie Ta, Ken-ichi Ueda, Kirk van Gorkom, Jason Walthall ja Jane Weeden.
iNaturalists-vision-is-a-world = iNaturalisti visiooniks on maailm, kus kõik suudavad metsikuid orgnaisme vaadeldes ja nende kohta infot jagades mõista ja hoida bioloogilist mitmekesisust.
Individual-encounters-with-organisms = Kokkupuuted organismidega kindlal ajal ja kindlas kohas, enamasti koos tõendusmaterjaliga.
Internet-Connection-Required = Vaja interneti ühendust
Intl-number = { $val }
Introduced = Sissetoodud
Introduced-to-place = Sissetoodud kohta { $place }
It-can-now-be-shared-for-use-in-research = Seda saab nüüd teadustöö jaoks jagada
It-may-take-up-to-an-hour-to-remove-content = It may take up to an hour to completely delete all associated content
It-might-also-be = It might also be
It-might-be-one-of-these = It might be one of these
January = jaanuar
JOIN = LIITU
Join-a-global-community-for-nature = Join a global community for nature
JOIN-PROJECT = LIITU PROJEKTIGA
JOIN-PROJECT--question = LIITU PROJEKTIGA?
JOINED = LIIGE
Joined-date = Liitunud: { $date }
JOINED-X-PROJECTS =
    { $count ->
        [one] LIITUNUD { $count } PROJEKTIGA
       *[other] LIITUNUD { $count } PROJEKTIGA
    }
JOURNAL-POSTS-WITHOUT-NUMBER =
    { $count ->
        [one] PÄEVIKU SISSEKANNE
       *[other] PÄEVIKU SISSEKANNET
    }
July = juuli
June = juuni
Just-make-sure-the-organism-is-wild = Ole lihtsalt kindel, et tegu on metsiku organismiga (pole lemmikloom, loomaaia elanik või aiataim)
Last-Active-date = Viimati aktiivne: { $date }
Lat-Lon = { NUMBER($latitude, maximumFractionDigits: 6) }, { NUMBER($longitude, maximumFractionDigits: 6) }
Lat-Lon-Acc = Laius: { NUMBER($latitude, maximumFractionDigits: 6) }, pikkus: { NUMBER($longitude, maximumFractionDigits: 6) }, täpsus: { $accuracy }
leading--identification = Suunaja
Learn-from-people-who-verify-and-refine-your-identifications = Learn from people who verify and refine your identifications.
Learn-More = Lisateave
LEARN-MORE-ABOUT-THIS-GROUP = LEARN MORE ABOUT THIS GROUP
LEARN-MORE-ABOUT-THIS-SPECIES = LEARN MORE ABOUT THIS SPECIES
LEAVE = LAHKU
LEAVE-PROJECT = LAHKU PROJEKTIST
LEAVE-PROJECT--question = LAHKU PROJEKTIST?
LEAVE-US-A-REVIEW = KIRJUTA MEIST ARVUSTUS!
Lets-reset-your-password = Let’s reset your password.
Loading-iNaturalists-AI-Camera = Laen iNaturalisti AI-kaamerat
Loads-content-that-requires-an-Internet-connection = Laeb sisu, mis nõuab internetiühendust
LOCATION = ASUKOHT
Location = Asukoht
Location-accuracy-is-too-imprecise = Asukoht on määratlejate abistamiseks liiga ebatäpne. Palun suurenda kaarti.
LOCATION-TOO-IMPRECISE = ASUKOHT LIIGA EBATÄPNE
LOG-IN = LOGI SISSE
LOG-IN-TO-INATURALIST = LOGI INATURALISTI SISSE
Log-in-to-iNaturalist = Logi iNaturalisti sisse
LOG-OUT = LOGI VÄLJA
LOG-OUT--question = LOGI VÄLJA?
Lowest = Madalaim
LOWEST-RANK = MADALAIM TASE
MAP = KAART
Map-Area = Kaardi piirkond
March = märts
Match-Screen = Match Screen
maverick--identification = Sõltumatu
May = mai
MEDIA = MEEDIA
Media-Type = Failitüüp
MEMBERS-WITHOUT-NUMBER =
    { $count ->
        [one] LIIGE
       *[other] LIIGET
    }
Menu = Menüü
Missing-Date = Kuupäev puudub
MISSING-EVIDENCE = TÕENDID PUUDUVAD
Monthly-Donor = Igakuine toetaja
Months = Kuud
MONTHS = KUUD
More = More
More-info = Lisainfo
More-ways-to-observe = More ways to observe
MOST-FAVED = LEMMIK
Most-faved = Lemmik
MY-CONTENT--notifications = MINU SISU
My-Observations = My Observations
My-Observations--bottom-tab = Me
Native = Kohalik
Native-to-place = Kohalik paigas: { $place }
Navigates-to-AI-camera = Mine AI-kaamerasse
Navigates-to-bulk-importer = Mine mass-importijasse
Navigates-to-camera = Mine kaamerasse
Navigates-to-explore = Mine avastama
Navigates-to-match-screen = Navigates to match screen
Navigates-to-notifications = Mine teavituste juurde
Navigates-to-observation-details = Mine vaatluse andmete lehele
Navigates-to-observation-edit-screen = Mine vaatluse muutmise lehele
Navigates-to-photo-importer = Mine fotoimportiasse
Navigates-to-previous-screen = Mine eelmisele ekraanile
Navigates-to-project-details = Mine projekti andmete lehele
Navigates-to-sound-recorder = Mine helisalvestajasse
Navigates-to-suggest-identification = Mine määratlust soovitama
Navigates-to-taxon-details = Mine taksoni detailidesse
Navigates-to-user-profile = Mine kasutajaprofiilile
Navigates-to-your-observations = Läheb sinu vaatluste juurde
NEARBY = LÄHEDAL
Nearby = Lähedal asuvad
Needs-ID--quality-grade = Vajab määramist
New-Observation = Uus vaatlus
Newest-to-oldest = Uuemast vanemani
Next-observation = Järgmine vaatlus
Next-slide = Next slide
No-Camera-Available = Kaamera pole saadaval
No-email-app-installed = E-postirakendus pole installeeritud
No-email-app-installed-body = Kui kasutad mõnda muud moodust e-post saatumisega, kirjuta aadressile { $address }
No-email-app-installed-body-check-other = Kontrolli e-posti kas veebilehitsejas või mõnes muus seadmes.
No-Location = Asukoht puudub
No-Media = Meedia puudub
No-model-found = Mudelit ei leitud
No-Notifications-Found = Sul ei ole teavitusi! Alustamiseks tee ise mõned vaatlused.
No-projects-match-that-search = Ükski projekt ei vasta sinu otsingukriteeriumitele
No-results-found-for-that-search = See otsing ei toonud tulemusi.
No-results-found-try-different-search = Tulemusi ei leitud. Proovi teist otsingut või muuda filtreid.
no-rights-reserved-cc0 = piiramata õigustega (CC0)
none--accuracy = puudub
NONE--ranks = PUUDUB
NOT-BY-ME = NOT BY ME
Not-enough-space-left-on-device = Seadmes pole piisavalt ruumi
Not-enough-space-left-on-device-try-again = Sinu seadmes pole selleks piisavalt salvestusmahtu. Palun vabasta natuke mahtu ja proovi uuesti.
NOTES = MÄRKMED
Notes = Notes
NOTIFICATIONS = TEAVITUSED
Notifications--bottom-tab = Activity
notifications-user-added-comment-to-observation-by-you = <0>{ $userName }</0> lisas sinu tehtud vaatlusele kommentaari
notifications-user-added-identification-to-observation-by-you = <0>{ $userName }</0> lisas sinu tehtud vaatlusele määratluse
notifications-user1-added-comment-to-observation-by-user2 = <0>{ $user1 }</0> lisas kommentaari kasutaja { $user2 } vaatlusele
notifications-user1-added-identification-to-observation-by-user2 = <0>{ $user1 }</0> lisas määratluse kasutaja { $user2 } vaatlusele
November = november
Obervations-must-be-manually-added = Observations must be manually added to a traditional project, either during the upload stage or after the observation has been shared to iNaturalist. A user must also join a traditional project in order to add their observations to it.
Obscured = Varjatud
Observation = Vaatlus
Observation-Attribution = Vaatlus: © { $userName } · { $restrictions }
Observation-Copyright = Observation Copyright: © { $userName } · { $restrictions }
Observation-has-no-photos-and-no-sounds = Sel vaatlusel pole pilte ega helisid.
Observation-location-obscured-randomized-point = This observation’s location is obscured. You are seeing a randomized point within the obscuration polygon.
Observation-location-obscured-you-can-see-your-own = This observation’s location is obscured. You can always see the location of your own observations.
Observation-location-obscured-you-have-permission = This observation’s location is obscured. You have permission to see this location.
Observation-options = Vaatluse sätted
OBSERVATION-WAS-DELETED = VAATLUS KUSTUTATUD
Observation-with-no-evidence = Observation with no evidence
Observations = Vaatlused
Observations-need-location-date--warning = iNaturalist observations need a location and date to be useful to scientists. Please check observations with this icon before uploading.
Observations-View = Observations View
OBSERVATIONS-WITHOUT-NUMBER =
    { $count ->
        [one] OBSERVATION
       *[other] OBSERVATIONS
    }
OBSERVE-ORGANISMS = OBSERVE ORGANISMS
OBSERVED-AT--label = OBSERVED AT
OBSERVED-IN--label = OBSERVED IN
Observers = Vaatlejad
Observers-View = Observers View
October = oktoober
Offensive-Inappropriate = Solvav / ebasobiv
Offensive-Inappropriate-Examples = Misleading or illegal content, racial or ethnic slurs, etc. For more on our definition of "appropriate," see the FAQ.
Offline-DQA-description = The DQA may not be accurate. Check your internet connection and try again.
Offline-suggestions-may-differ-from-online = Offline suggestions may differ from online suggestions, and taxon images and common names may not load.
OK = OK
Oldest-to-newest = Oldest to newest
Once-you-create-and-upload-observations = Once you create & upload observations, other members of our community can add identifications to help your observations reach research grade.
Open = Avalik
OPEN-EMAIL = AVA E-POST
Open-menu = Ava menüü.
OPEN-SETTINGS = AVA SÄTTED
Opens-add-comment-form = Avab kommentaari lisamise vormi.
Opens-AI-camera = Avab AI-kaamera.
Opens-edit-comment-form = Avab kommentaari muutmise vormi.
Opens-location-permission-prompt = Avab asukoha õigused
Opens-the-side-drawer-menu = Avab kõrvalmenüü.
OR-SIGN-IN-WITH = OR SIGN IN WITH
Or-you-can-try-to-get-a-clearer-photo-by-zooming-in-getting-closer = Or, you can try to get a clearer photo by zooming in, getting closer, or trying a different angle.
Organism-is-captive = Organism on vangistatud
Organisms-that-are-identified-to-species = Organisms that are identified to species rank or below
Other = Muu
OTHER-DATA = MUUD ANDMED
OTHER-SUGGESTIONS = TEISED PAKKUMISED
PASSWORD = SALASÕNA
PEOPLE--title = INIMESED
Photo-importer = Foto importija
PHOTO-LICENSING = FOTO LITSENTS
Photos = Fotod
Photos-you-take-will-appear-here = Sinu tehtud fotod ilmuvad siia
Please-allow-Camera-Access = Please allow Camera Access
Please-allow-Location-Access = Please allow Location Access
Please-allow-Microphone-Access = Please allow Microphone Access
Please-choose-a-different-password = Please choose a different password.
Please-Grant-Permission = Please Grant Permission
PLEASE-LOG-IN = PALUN LOGI SISSE
Please-make-sure-your-password-is-at-least-6-characters = Please make sure your password is at least 6 characters.
Please-try-again-when-you-are-connected-to-the-internet = Please try again when you are connected to the Internet.
Please-try-again-when-you-are-online = Please try again when you are online!
Point-the-camera-at-an-animal-plant-or-fungus = Point the camera at an animal, plant, or fungus
POTENTIAL-DISAGREEMENT = POTENTIAL DISAGREEMENT
Potential-disagreement-description = <0>Is the evidence enough to confirm this is </0><1></1><0>?<0>
Potential-disagreement-disagree = <0>No, but this is a member of </0><1></1>
Potential-disagreement-unsure = <0>I don't know but I am sure this is </0><1></1>
Previous-observation = Previous observation
Previous-slide = Previous slide
Privacy-Policy = Privaatsusreeglid
PRIVACY-POLICY = PRIVAATSUSPOLIITIKA
Private = Isiklik
PROJECT = PROJEKT
Project-Members-Only = Ainult projekti liikmed
PROJECT-REQUIREMENTS = PROJEKTI TINGIMUSED
project-start-time-datetime = Algus: { $datetime }
PROJECTS = PROJEKTID
Projects = Projektid
PROJECTS-X = PROJEKTID ({ $projectCount })
Pull-to-refresh-and-sync-observations = Pull to refresh and sync observations
Pull-to-refresh-notifications = Libista teadete värskendamiseks
QUALITY-GRADE = KVALITEEDIHINNANG
Quality-Grade = Kvaliteedihinnang
Quality-Grade-Casual--label = Kvaliteedihinnang: Juhuvaatlus
Quality-Grade-Needs-ID--label = Kvaliteedihinnang: Vajab määramist
Quality-Grade-Research--label = Kvaliteedihinnang: Teaduskõlbulik
Ranks-CLASS = CLASS
Ranks-Class = Klass
Ranks-COMPLEX = COMPLEX
Ranks-Complex = Liigikompleks
Ranks-EPIFAMILY = EPIFAMILY
Ranks-Epifamily = Episugukond
Ranks-FAMILY = FAMILY
Ranks-Family = Sugukond
Ranks-FORM = FORM
Ranks-Form = Vorm
Ranks-GENUS = GENUS
Ranks-Genus = Perekond
Ranks-GENUSHYBRID = GENUSHYBRID
Ranks-Genushybrid = Hübriidperekond
Ranks-HYBRID = HYBRID
Ranks-Hybrid = Hübriid
Ranks-INFRACLASS = INFRACLASS
Ranks-Infraclass = Infraklass
Ranks-INFRAHYBRID = INFRAHYBRID
Ranks-Infrahybrid = Alamhübriid
Ranks-INFRAORDER = INFRAORDER
Ranks-Infraorder = Infraselts
Ranks-KINGDOM = KINGDOM
Ranks-Kingdom = Riik
Ranks-ORDER = ORDER
Ranks-Order = Järjestus
Ranks-PARVORDER = PARVORDER
Ranks-Parvorder = Parvklass
Ranks-PHYLUM = PHYLUM
Ranks-Phylum = Hõimkond
Ranks-SECTION = SECTION
Ranks-Section = Sektsioon
Ranks-SPECIES = LIIGID
Ranks-Species = Liigid
Ranks-Statefmatter = Mateeria
Ranks-STATEOFMATTER = STATE OF MATTER
Ranks-SUBCLASS = SUBCLASS
Ranks-Subclass = Alamklass
Ranks-SUBFAMILY = SUBFAMILY
Ranks-Subfamily = Alamsugukond
Ranks-SUBGENUS = SUBGENUS
Ranks-Subgenus = Alamperekond
Ranks-SUBKINGDOM = SUBKINGDOM
Ranks-Subkingdom = Alamriik
Ranks-SUBORDER = SUBORDER
Ranks-Suborder = Alamselts
Ranks-SUBPHYLUM = SUBPHYLUM
Ranks-Subphylum = Alamhõimkond
Ranks-SUBSECTION = SUBSECTION
Ranks-Subsection = Alamsektsioon
Ranks-SUBSPECIES = SUBSPECIES
Ranks-Subspecies = Alamliik
Ranks-SUBTERCLASS = SUBTERCLASS
Ranks-Subterclass = Subterklass
Ranks-SUBTRIBE = SUBTRIBE
Ranks-Subtribe = Alamtriibus
Ranks-SUPERCLASS = SUPERCLASS
Ranks-Superclass = Ülemklass
Ranks-SUPERFAMILY = SUPERFAMILY
Ranks-Superfamily = Ülemsugukond
Ranks-SUPERORDER = SUPERORDER
Ranks-Superorder = Ülemselts
Ranks-SUPERTRIBE = SUPERTRIBE
Ranks-Supertribe = Ülemtriibus
Ranks-TRIBE = TRIBE
Ranks-Tribe = Triibus
Ranks-VARIETY = VARIETY
Ranks-Variety = Teisend
Ranks-ZOOSECTION = ZOOSECTION
Ranks-Zoosection = Zooloogiline sektsioon
Ranks-ZOOSUBSECTION = ZOOSUBSECTION
Ranks-Zoosubsection = Zooloogiline alamsektsioon
Read-more-on-Wikipedia = Loe edasi Vikipeediast
Reason--flag = Reason
Record-a-sound = Salvesta heli
Record-animal-sounds = Record animal sounds
RECORD-NEW-SOUND = SALVESTA UUS HELI
RECORD-SOUND = SALVESTA HELI
Record-verb = Salvesta
Recording-sound = Salvestan heli
Recording-stopped-Tap-to-play-the-current-recording = Recording stopped. Tap to play the current recording.
REDO-SEARCH-IN-MAP-AREA = OTSI UUESTI KAARDI PIIRKONNAS
Remove-agreement = Eemalda nõustumine
Remove-disagreement = Eemalda mittenõustumine
Remove-favorite = Eemalda lemmikutest
Remove-identification = Eemalda määratlus
Remove-Photos = Eemalda foto
Remove-project-filter = Eemalda projekti filter
Remove-taxon-filter = Eemalda taksoni filter
Remove-user-filter = Eemalda kasutaja filter
Removes-this-observations-taxon = Eemaldab sellev aatluse taksoni
Removes-your-vote-of-agreement = Eemaldab sinu nõustumise
Removes-your-vote-of-disagreement = Eemaldab sinu mittenõustumise
Research-Grade--quality-grade = Teaduskõlbulik
RESEARCH-GRADE--quality-grade = RESEARCH GRADE
Research-Grade-Status = Research Grade Status
RESET-PASSWORD = LÄHTESTA SALASÕNA
RESET-RECORDING = LÄHTESTA SALVESTUS
RESET-SEARCH = LÄHTESTA OTSING
RESET-SOUND-header = LÄHTESTAN SALVESTUSE?
Reset-verb = Tühjenda
RESTART-APP = TÄISKÄIVITA RAKENDUS
Restore = Taasta
Reveal = Näita
REVIEW-INATURALIST = ARVUSTA INATURALISTI
REVIEWED = REVIEWED
Reviewed-observations-only = Reviewed observations only
Satellite--map-type = Satelliit
SAVE = SALVESTA
Save = Salvesta
SAVE-ALL = SALVESTA KÕIK
Save-all-observations = Salvesta kõik vaatlused
SAVE-CHANGES = SALVESTA MUUTUSED
SAVE-FOR-LATER = SÄILITA HILISEMAKS
SAVE-LOCATION = SALVESTA ASUKOHT
SAVE-PHOTOS = SALVESTA FOTOD
Save-photos-to-your-library = Save photos to your library
Saved-Observation = Salvestatud vaatlused, mis ootavad üleslaadimist
Scientific-Name = Teaduslik nimi
Scientific-Name-Common-Name = Scientific Name (Common Name)
SEARCH = OTSING
Search = Otsi
Search-for-a-project = Otsi projekti
SEARCH-FOR-A-TAXON = OTSI TAKSONIT
Search-for-a-taxon = Otsi taksonit
SEARCH-LOCATION = OTSI ASUKOHTA
SEARCH-PROJECTS = OTSI PROJEKTI
Search-suggestions-with-location = Asukohaga otsingusoovitused
Search-suggestions-without-location = Asukohata otsingusoovitused
SEARCH-TAXA = OTSI TAKSONIT
SEARCH-USERS = OTSI KASUTAJAT
See-observations-by-this-user-in-Explore = See observations by this user in Explore
See-observations-of-this-taxon-in-explore = See observations of this taxon in explore
See-project-members = See project members
See-species-observed-by-this-user-in-Explore = See species observed by this user in Explore
Select-a-date-and-time-for-observation = Select a date and time for observation
Select-captive-or-cultivated-status = Select captive or cultivated status
Select-geoprivacy-status = Select geoprivacy status
Select-or-drag-media = Select or drag media
Select-photo = Select photo
SELECT-THIS-TAXON = SELECT THIS TAXON
Select-user = Select user
Selects-iconic-taxon-X-for-identification = Selects iconic taxon { $iconicTaxon } for identification.
Separate-Photos = Separate Photos
September = september
SETTINGS = SETTINGS
Share = Jaga
SHARE-DEBUG-LOGS = SHARE DEBUG LOGS
Share-location = Jaga asukohta
Share-map = Share map
Share-your-observation-where-it-can-help-scientists = Share your observation, where it can help scientists across the world better understand biodiversity.
SHOP-INATURALIST-MERCH = SHOP INATURALIST MERCH
Show-observation-options = Show observation options.
Showing-offline-search-results--taxa = Showing offline search results. To search for more species, try again when connected to the Internet.
Shows-identification-suggestions = Shows identification suggestions
Shows-iNaturalist-bird-logo = Shows iNaturalist bird logo.
Shows-observation-creation-options = Shows observation creation options
Sign-in-with-Apple = Sign in with Apple
Sign-in-with-Apple-Failed = Apple'i abil sisselogimine ebaõnnestus
Sign-in-with-Google = Sign in with Google
Sign-in-with-Google-Failed = Sign in with Google Failed
Skip-additional-suggestions = Skip additional suggestions
Skip-for-now = Skip for now
Something-went-wrong = Something went wrong.
Sorry-this-observation-was-deleted = Vabandust, see vaatlus on kustutatud
Sorry-we-dont-know-how-to-open-that-URL = Vabandust, me ei oska seda aadressi avada: { $url }
SORT-BY = SORTEERI
Sort-by = Sorteeri
sound-playback-separator = /
Sound-recorder = Helisalvesti
sound-recorder-help-A-recording-of = Määratlejaid aitab kõige paremini 5-15 sekundi pikkune salvestus.
sound-recorder-help-Get-as-close-as-you-can = Mine organismile nii lähedale kui turvaliselt võimalik.
sound-recorder-help-Get-closer = Mine lähemale
sound-recorder-help-Keep-it-short = Las olla lühike
sound-recorder-help-Make-sure = Ära lase endae liigutuste helil organismi tekitatavat heli summutada.
sound-recorder-help-One-organism = Üks organism
sound-recorder-help-Stop-moving = Ära liiguta
sound-recorder-help-Try-to-isolate = Try to isolate the sound of a single organism. If you can’t, make sure to leave a note of which organism you’re recording.
Sounds = Helid
Source-List = <0>(Source List: </0><1>{ $source }</1><0>)</0>
Spam = Rämpspost
Spam-Examples = Ärilisi teateid, katkiseid linke, jne.
Species = Liigid
Species-View = Species View
SPECIES-WITHOUT-NUMBER =
    { $count ->
        [one] SPECIES
       *[other] SPECIES
    }
Standard--map-type = Normaalne
Start-must-be-before-end = Alguskuupäev peab olema lõppkuupäevast varasem.
Start-upload = Alusta üles laadimist
Starts-recording-sound = Alustab heli salvestamist
Stay-on-this-screen = Stay on this screen while your location loads.
Still-need-help = Still need help? You can file a support request here.
Stop-upload = Katkesta üleslaadimine
Stop-verb = Peata
Stops-recording-sound = Lõpetab heli salvestamise
SUBMIT = SAADA
SUBMIT-ID-SUGGESTION = PAKU MÄÄRATLUS
SUGGEST-ID = PAKU MÄÄRATLUS
supporting--identification = Toetab
Switches-to-tab = Läheb sakki { $tab }
Sync-observations = Sünkroniseeri vaatlused
Syncing = Sünkroniseerin...
Take-multiple-photos-of-a-single-organism = Tee ühest organismist mitu fotot
Take-photo = Pildista
Taxa = Taksonid
TAXON = TAKSON
TAXON-NAMES-DISPLAY = TAKSONITE KUVAMINE
TAXONOMIC-RANKS = TAKSONOOMIA TASEMED
TAXONOMY-header = TAKSONOOMIA
TEAM = MEESKOND
Terms-of-Use = Kasutustingimused
TERMS-OF-USE = KASUTUSTINGIMUSED
Thank-you-for-sharing-your-feedback = Thank you for sharing your feedback to help us improve!
Thanks-for-using-any-suggestions = Thanks for using this app! Do you have any suggestions for the people who make it?
That-email-is-already-associated-with-an-account = That email is already associated with an account.
That-user-profile-doesnt-exist = Selle kasutaja profiili ei eksisteeri
That-username-is-unavailable = That username is unavailable
The-AI-is-not-confident-It-may-be-one-of-the-IDs-below = The AI is not confident. It may be one of the IDs below.
The-AI-is-not-confident-Upload-to-ask-the-community = The AI is not confident. Upload to ask the community.
The-exact-location-will-be-hidden = The exact location will be hidden publicly, and instead generalized to a larger area. (Threatened and endangered species are automatically obscured).
The-iNaturalist-community-will-help-verify-and-refine-identifications = The iNaturalist community will help verify and refine identifications on your observations to create Research Grade data for science and conservation.
The-iNaturalist-Network = The iNaturalist network is a collection of localized websites that are fully connected to the global iNaturalist community. Network sites are supported by local institutions that promote local use and facilitate the use of data from iNaturalist to benefit local biodiversity.
The-location-will-not-be-visible-to-others = The location will not be visible to others, which might make the observation impossible to identify
The-models-that-suggest-species = The models that suggest species based on visual similarity and location are thanks in part to collaborations with Sara Beery, Tom Brooks, Elijah Cole, Christian Lange, Oisin Mac Aodha, Pietro Perona, and Grant Van Horn.
This-is-a-wild-organism = This is a wild organism and wasn't placed in this location by humans.
This-is-how-taxon-names-will-be-displayed = This is how all taxon names will be displayed to you across iNaturalist:
This-is-your-identification-other-people-may-help-confirm-it = This is your identification. Other people may help confirm it!
This-may-take-a-few-seconds = This may take a few seconds.
This-observation-has-no-comments-or-identifications-yet = Sel vaatlusel pole veel kommentaar või määratlusi.
This-observation-has-not-met-the-conditions-required-to-meet-Research-Grade = See vaatlus ei vasta veel teaduskõlbulikuks kuulutamise tingimustele
This-observation-is-not-eligible-for-research-grade-status = This observation is not eligible for research grade status. Learn more in the Data Quality Assessment below.
This-observation-is-research-grade-and-can-be-used-by-scientists = This observation is research grade and can be used by scientists!
This-observation-needs-more-identifications = See vaatlus vajab teaduskõlbulikuks kuulutamiseks rohkem määratlusi
This-observation-needs-more-identifications-to-become-research-grade = This observation needs more identifications to become research grade.
This-observer-has-opted-out-of-the-Community-Taxon = This observer has opted out of the Community Taxon
This-organism-was-placed-by-humans = This organism was placed in this location by humans. This applies to things like garden plants, pets, and zoo animals.
To-sync-your-observations-to-iNaturalist = Enda vaatluste iNaturalistiga sünkroniseerimiseks logi sisse.
To-view-nearby-organisms-please-enable-location = Läheduses asuvate organismide nägemiseks lülita oma asukoht sisse.
To-view-nearby-projects-please-enable-location = Läheduses asuvate projektide nägemiseks lülita oma asukoht sisse.
Toggle-map-type = Muuda kaardi tüüpi
TOP-ID-SUGGESTION = PARIM MÄÄRATLUS
Traditional-Project = Tavaprojekt
Umbrella-Project = Ülemprojekt
UNFOLLOW = LÕPETA JÄLGIMINE
UNFOLLOW-USER = LÕPETA KASUTAJA JÄLGIMINE?
Unknown--rank = Teadmata
Unknown--taxon = Teadmata
Unknown--user = Teadmata
Unknown-error = Teadmata viga
Unknown-organism = Tundmatu organism
Unreviewed-observations-only = Unreviewed observations only
Upload-Complete = Üleslaadimine lõpetatud
Upload-in-progress = Üleslaadimine kestab
UPLOAD-NOW = LAE ÜLES
Upload-photos-from-your-photo-library = Upload multiple photos from your photo library
Upload-Progress = Üleslaadimine { $uploadProgress } protsenti valmis
UPLOAD-TO-INATURALIST = LAE INATURALISTI
Upload-x-observations =
    Lae üles { $count ->
        [one] 1 vaatlus
       *[other] { $count } vaatlust
    }
Upload-your-observations-to-contribute-data-to-help-save-species = Upload your observations to contribute data to help save species.
Uploaded-via-application = Allikas: { $application }
Uploading-x-of-y = Uploading { $currentUploadCount } of { $total }
Uploading-x-of-y-observations =
    { $total ->
        [one] Uploading { $currentUploadCount } observation
       *[other] Uploading { $currentUploadCount } of { $total } observations
    }
Use-iNaturalist-to-identify-any-living-thing = Use iNaturalist to identify any living thing
Use-iNaturalists-AI-Camera = Use iNaturalist's AI Camera to identify organisms in real time
USE-LOCATION = KASUTA ASUKOHTA
Use-the-devices-other-camera = Kasuta seadme teist kaamerat
Use-the-iNaturalist-camera-to-see-real-time-identifications-and-take-photos = Use the iNaturalist camera to see real-time identifications and take photos!
Use-your-devices-microphone-to-record-animal-sounds-and-share-them = Use your device’s microphone to record animal sounds and share them to get identifications and contribute to science!
USER = KASUTAJA
User = Kasutaja { $userHandle }
USERNAME-OR-EMAIL = KASUTAJATUNNUS VÕI E-POST
Users = Kasutajad
Using-location = Using location
Verified-IDs-are-used-for-science-and-conservation = Verified IDs are used for science and conservation
Version-app-build = Versioon { $appVersion } ({ $buildVersion })
VIEW-ALL-X-PLACES = VAATA { $count } KOHTA
VIEW-ALL-X-PROJECTS = VAATA { $count } PROJEKTI
VIEW-ALL-X-TAXA = VAATA { $count } TAKSONIT
VIEW-ALL-X-USERS = VIEW ALL { $count } USERS
VIEW-CHILDREN-TAXA = VIEW CHILDREN TAXA
VIEW-DATA-QUALITY-ASSESSMENT = VIEW DATA QUALITY ASSESSMENT
VIEW-EDUCATORS-GUIDE = VIEW EDUCATOR'S GUIDE
VIEW-FOLLOWERS = VIEW FOLLOWERS
VIEW-FOLLOWING = VIEW FOLLOWING
View-in-browser = Kuva veebilehitsejas
VIEW-IN-EXPLORE = VIEW IN EXPLORE
VIEW-INATURALIST-HELP = VIEW INATURALIST HELP
View-photo = View photo
View-photo-licensing-info = View photo licensing info
VIEW-PROJECT-REQUIREMENTS = VIEW PROJECT REQUIREMENTS
VIEW-PROJECTS = VIEW PROJECTS
View-suggestions = Vaata soovitusi
Watch-your-notifications-for-identifications = Watch your notifications for identifications!
We-are-not-confident-enough-to-make-a-top-ID-suggestion = We’re not confident enough to make a top ID suggestion, but here are some other suggestions:
Welcome-back = Welcome back!
WHAT-IS-INATURALIST = MIS ON INATURALIST?
Whats-more-by-recording = What's more, by recording and sharing your observations, you'll create research-quality data for scientists working to better understand and protect nature. So if you like recording your findings from the outdoors, or if you just like learning about life, join us!
When-tapping-the-green-observation-button = When tapping the green observation button, open:
WIKIPEDIA = VIKIPEEDIA
Wild = Metsik
WILD-STATUS = STAATUSEGA
Withdraw = Võta tagasi
WITHDRAW-ID = WITHDRAW ID
WITHDRAW-ID-QUESTION = WITHDRAW ID?
Withdraws-identification = Withdraws identification
Worldwide = Globaalselt
WORLDWIDE = MAAILMAS
Would-you-like-to-discard-your-current-recording-and-start-over = Would you like to discard your current recording and start over?
Would-you-like-to-suggest-the-following-identification = Soovid seda määratlust pakkuda?
x-comments =
    { $count ->
        [one] { $count } kommentaar
       *[other] { $count } kommentaari
    }
x-failed =
    { $count ->
        [one] { $count } failed
       *[other] { $count } failed
    }
X-FOLLOWERS =
    { $count ->
        [one] { $count } JÄLGIJA
       *[other] { $count } JÄLGIJAT
    }
X-Identifications =
    { $count ->
        [one] { $count } määratlus
       *[other] { $count } määratlust
    }
x-identifications =
    { $count ->
        [one] { $count } määratlus
       *[other] { $count } määratlust
    }
X-Identifiers =
    { $count ->
        [one] { $count } määratleja
       *[other] { $count } määratlejat
    }
X-MEMBERS = { $count } LIIGET
X-Observations =
    { $count ->
        [one] 1 vaatlus
       *[other] { $count } vaatlust
    }
X-OBSERVATIONS--below-number =
    { $count ->
        [one] OBSERVATION
       *[other] OBSERVATIONS
    }
X-observations-deleted =
    { $count ->
        [one] 1 vaatlus kustutatud
       *[other] { $count } vaatlust kustutatud
    }
X-observations-uploaded =
    { $count ->
        [one] 1 vaatlus üles laetud
       *[other] { $count } vaatlust üles laetud
    }
X-Observers =
    { $count ->
        [one] { $count } vaatleja
       *[other] { $count } vaatlejat
    }
X-of-Y =
    { $x ->
        [one] 1
       *[other] { $x }
    } { $y ->
        [one] / { $y }
       *[other] / { $y }
    }
X-percent = { $count }%
X-percent-confidence = { $count }% confidence
X-PHOTOS =
    { $photoCount ->
        [one] 1 FOTO
       *[other] { $photoCount } FOTOT
    }
X-PHOTOS-X-OBSERVATIONS =
    { $photoCount ->
        [one] 1 FOTO
       *[other] { $photoCount } FOTOT
    }, { $observationCount ->
        [one] 1 VAATLUS
       *[other] { $observationCount } VAATLUST
    }
X-PHOTOS-Y-SOUNDS =
    { $photoCount ->
        [one] 1 FOTO
       *[other] { $photoCount } FOTOT
    }, { $soundCount ->
        [one] 1 HELI
       *[other] { $soundCount } HELI
    }
X-PROJECTS = { $projectCount } PROJEKTI
x-saved =
    { $count ->
        [one] { $count } saved
       *[other] { $count } saved
    }
X-SOUNDS =
    { $count ->
        [one] 1 HELI
       *[other] { $count } HELI
    }
X-Species =
    { $count ->
        [one] { $count } liik
       *[other] { $count } liiki
    }
X-SPECIES--below-number =
    { $count ->
        [one] SPECIES
       *[other] SPECIES
    }
x-uploaded =
    { $count ->
        [one] { $count } uploaded
       *[other] { $count } uploaded
    }
x-uploading =
    { $count ->
        [one] { $count } uploading
       *[other] { $count } uploading
    }
x-uploads-failed =
    { $count ->
        [one] { $count } üleslaadimine ebaõnnestus
       *[other] { $count } üleslaadimist ebaõnnestus
    }
You-are-offline = Internetiühendus puudub
You-are-offline-Tap-to-reload = You are offline. Tap to reload.
You-are-offline-Tap-to-try-again = You are offline. Tap to try again.
You-can-add-up-to-20-media = You can add up to 20 photos and 20 sounds per observation.
You-can-also-check-out-merchandise = You can also check out merchandise for iNaturalist and Seek at our store below!
You-can-click-join-on-the-project-page = You can click “join” on the project page.
You-can-find-answers-on-our-help-page = You can find answers on our help page.
You-can-now-upload-your-observations-to-iNaturalist-and-contribute = You can now upload your observations to iNaturalist and contribute to global biodiversity research.
You-can-only-add-20-photos-per-observation = You can only add 20 photos per observation
You-can-still-share-the-file = You can still share the file with another app. If you can email it, please send it to { $email }
You-can-upload-this-observation-to-our-community = You can upload this observation to our community to get an identification from a real person, and help our AI improve its identifications in the future
You-changed-filters-will-be-discarded = You changed filters, but they were not applied to your explore search results.
You-have-opted-out-of-the-Community-Taxon = You have opted out of the Community Taxon
You-havent-joined-any-projects-yet = You haven’t joined any projects yet!
You-havent-observed-any-species-yet = You haven't observed any species yet.
You-likely-observed-a-new-species = You likely observed a new species!
You-likely-observed-a-species = You likely observed a species
You-likely-observed-an-organism-in-this-group = You likely observed an organism in this group
You-may-have-observed-a-new-species = You may have observed a new species!
You-may-have-observed-a-species = You may have observed a species
You-may-have-observed-an-organism-in-this-group = You may have observed an organism in this group
You-may-notice-changes-to-how-things-look-and-flow = You may notice changes to how things look and flow. You can control your options in the settings.
You-must-be-logged-in-to-view-messages = You must be logged in to view messages
You-must-install-Google-Play-Services-to-sign-in-with-Google = You must install Google Play Services to sign in with Google.
You-need-an-Internet-connection-to-do-that = You need an Internet connection to do that.
You-need-log-in-to-do-that = You need to log in to do that.
You-observed-a-new-species = You observed a new species!
You-observed-a-species = You observed a species
You-observed-an-organism-in-this-group = You observed an organism in this group
You-will-see-notifications = Teavitusi näed peale sisse logimist ja vaatluste üles laadimist.
Your-donation-to-iNaturalist = Your donation to iNaturalist supports the improvement and stability of the mobile apps and website that connects millions of people to nature and enables the protection of biodiversity worldwide!
Your-email-is-confirmed = Your email is confirmed! Please log in to continue.
Your-location-uncertainty-is-over-x-km = Your location uncertainty is over { $x } km, which is too high to be helpful to identifiers. Edit the location and zoom in until the accuracy circle turns green and is centered on where you observed the organism.
Your-observations-can-help-science = Your observations can help science!
Youre-ready-to-share-your-observations = You’re ready to share your observations!
Youve-denied-permission-prompt = You’ve denied permission. Please grant permission in the settings app.
Youve-previously-denied-camera-permissions = You've previously denied camera permissions, so please enable them in settings.
Youve-previously-denied-location-permissions = You’ve previously denied location permissions, so please enable them in settings.
Youve-previously-denied-microphone-permissions = You’ve previously denied microphone permissions, so please enable them in settings.
Zoom-in-as-much-as-possible-to-improve = Zoom in as much as possible to improve location accuracy and get better identifications.
Zoom-to-current-location = Zoom to current location
zoom-x = { $zoom }×
