### DO NOT EDIT THIS FILE!
###
### This file came from Crowdin and was normalized by ftl.js.
### It will be overwritten during the next translation sync. To add
### translations, go to https://crowdin.com/editor/inaturalistios/724
###

A-global-community-for-nature = A global community for nature
ABOUT = ჩვენზე
ABOUT-COLLECTION-PROJECTS = ABOUT COLLECTION PROJECTS
ABOUT-INATURALIST = ABOUT INATURALIST
ABOUT-THE-DQA = ABOUT THE DQA
About-the-DQA-description = The Quality Grade summarizes the accuracy, precision, completeness, relevance, and appropriateness of an iNaturalist observation as biodiversity data. Some attributes are automatically determined, while others are subject to a vote by iNat users. iNaturalist shares licensed "Research Grade" observations with a number of data partners for use in science and conservation.
ABOUT-TRADITIONAL-PROJECTS = ABOUT TRADITIONAL PROJECTS
ABOUT-UMBRELLA-PROJECTS = ABOUT UMBRELLA PROJECTS
accessible-comname-sciname = { $commonName } ({ $scientificName })
accessible-sciname-comname = { $scientificName } ({ $commonName })
Account-Deleted = Account Deleted
ACCOUNT-SETTINGS = ACCOUNT SETTINGS
ACTIVITY = ACTIVITY
Add-agreement = Add agreement
ADD-AN-ID = ADD AN ID
Add-an-ID-Later = Add an ID Later
ADD-COMMENT = ADD COMMENT
Add-Date-Time = Add Date/Time
Add-disagreement = Add disagreement
ADD-EVIDENCE = ADD EVIDENCE
Add-evidence = Add evidence
Add-favorite = Add favorite
Add-Location = ადგილმდებარეობის დამატება
ADD-LOCATION-FOR-BETTER-IDS = უკეთესი ID-ებისთვის დაამატეთ ადგილმდებარეობა
Add-location-to-refresh-suggestions = შეთავაზებების გასაახლებლად დაამატეთ ადგილმდებარეობა
Add-observations = Add observations
ADD-OPTIONAL-COMMENT = ADD OPTIONAL COMMENT
Add-optional-notes = სურვილისამებრ დაამატეთ ჩანაწერები
Adds-ID = Adds ID
Adds-your-vote-of-agreement = Adds your vote of agreement
Adds-your-vote-of-disagreement = Adds your vote of disagreement
Advanced-Mode = Advanced Mode
ADVANCED-SETTINGS = ADVANCED SETTINGS
Affiliation = Affiliation: { $site }
After-capturing-or-importing-photos-show = After capturing or importing photos, show:
Agree = ვეთანხმები
AGREE = ვეთანხმები
AGREE-WITH-ID = AGREE WITH ID?
Agree-with-ID-description = Would you like to agree with the ID and suggest the following identification?
AI-Camera = AI Camera
ALL = ყველა
All = ყველა
All-observation-options--list = All observation options: iNaturalist AI Camera, Standard Camera, Uploading from Photo Library, and Sound Recorder
All-observations = All observations
All-observations-need-a-date-and-location-to-be-used-for-science = სამეცნიერო მიზნით გამოყენებისთვის, ყველა დაკვირვებას სჭირდება თარიღი და ადგილმდებარეობა. გთხოვთ, ჩაასწოროთ დაკვირვებები, თუ მათ მეტი ინფორმაცია სჭირდებათ.
All-organisms = All organisms
all-rights-reserved = all rights reserved
All-taxa = All taxa
ALL-USERS-EXCEPT = ALL USERS EXCEPT
ALLOW-LOCATION-ACCESS = ადგილმდებარეობაზე წვდომის დაშვება
Already-have-an-iNaturalist-account = Already have an iNaturalist account?
An-Internet-connection-is-required = An Internet connection is required to load more observations.
Analyzing-for-the-best-identification = Analyzing for the best identification...
Any--date = Any
Any--establishment-means = Any
Any--media-type = Any
Any--project = Any
Any--quality-grade = Any
Any--user = Any
Anyone-using-iNaturalist-can-see = Anyone using iNaturalist can see where this species was observed, and scientists can most easily use it for research.
APP-LANGUAGE = APP LANGUAGE
apple-full-name = { JOIN($namePrefix, $givenName, $middleName, $nickname, $familyName, $nameSuffix, separator: " ") }
APPLY-FILTERS = APPLY FILTERS
Apply-filters = Apply filters
April = April
Are-you-an-educator = Are you an educator wanting to use iNaturalist with your students?
Are-you-sure-you-want-to-log-out = Are you sure you want to log out of your iNaturalist account? All observations that haven’t been uploaded to iNaturalist will be deleted.
attribution-cc-by = some rights reserved (CC BY)
attribution-cc-by-nc = some rights reserved (CC BY-NC)
attribution-cc-by-nc-nd = some rights reserved (CC BY-NC-ND)
attribution-cc-by-nc-sa = some rights reserved (CC BY-NC-SA)
attribution-cc-by-nd = some rights reserved (CC BY-ND)
attribution-cc-by-sa = some rights reserved (CC BY-SA)
August = August
BACK-TO-LOGIN = BACK TO LOGIN
Bulk-importer = Bulk importer
By-exiting-changes-not-saved = By exiting, changes to your observation will not be saved.
By-exiting-observation-not-saved = By exiting, your observation will not be saved.
By-exiting-your-observations-not-saved = By exiting, your observations will not be saved. You can save them to your device, or you can delete them.
By-exiting-your-photos-will-not-be-saved = By exiting, your photos will not be saved.
By-exiting-your-recorded-sound-will-not-be-saved = By exiting, your recorded sound will not be saved.
BY-ME = BY ME
By-uploading-your-observation-to-iNaturalist-you-can = By uploading your observation to iNaturalist, you can:
Camera = კამერა
CANCEL = CANCEL
Cancel = გაუქმება
Captive-Cultivated = ტყვეობაში/კულტივირებული
Casual--quality-grade = Casual
CC-BY = CC BY
CC-BY-NC = CC BY-NC
CC-BY-NC-ND = CC BY-NC-ND
CC-BY-NC-SA = CC BY-NC-SA
CC-BY-ND = CC BY-ND
CC-BY-SA = CC BY-SA
CC0 = CC0
CHANGE-APP-LANGUAGE = CHANGE APP LANGUAGE
CHANGE-DATE = CHANGE DATE
Change-date = Change date
CHANGE-END-DATE = CHANGE END DATE
Change-end-date = Change end date
Change-observations-sort-order = Change observations sort order
Change-project = Change project
Change-species-sort-order = Change species sort order
CHANGE-START-DATE = CHANGE START DATE
Change-start-date = Change start date
Change-taxon = Change taxon
Change-taxon-filter = Change taxon filter
Change-user = Change user
Change-zoom = Change zoom
CHECK-YOUR-EMAIL = CHECK YOUR EMAIL!
CHOOSE-A-USERNAME = CHOOSE A USERNAME
Choose-taxon = Choose taxon
Choose-top-taxon = Choose top taxon
Clear = Clear
Close = დახურვა
Close-permission-request-screen = Close permission request screen
Close-search = Close search
Closes-explanation = Closes explanation
Closes-introduction = Closes introduction
Closes-withdraw-id-sheet = Closes "Withdraw ID" sheet
COLLABORATORS = COLLABORATORS
Collection-Project = საკოლექციო პროექტი
Combine-Photos = Combine Photos
COMMENT = COMMENT
Comment-options = Comment options
Common-Name-Scientific-Name = Common Name (Scientific Name)
Community-Discussion = Community Discussion
Community-Guidelines = თემის წესები
COMMUNITY-GUIDELINES = თემის წესები
Confidence--label = Confidence
CONFIRM = CONFIRM
Congratulations-You-made-your-first-observation = Congratulations! You made your first observation!
Connect-with-expert-naturalists = Connect with expert naturalists
Connect-with-other-naturalists = Connect with other naturalists and engage in conversations.
Connection-problem-Please-try-again-later = Connection problem. Please try again later.
CONTACT-SUPPORT = CONTACT SUPPORT
CONTINUE = CONTINUE
Coordinates-copied-to-clipboard = Coordinates copied to clipboard
Copy-coordinates = Copy Coordinates
Copyright = Copyright
Could-not-find-a-camera-on-this-device = Could not find a camera on this device
Couldnt-create-comment = Couldn't create comment
Couldnt-create-identification-error = Couldn't create identification { $error }
Couldnt-create-identification-unknown-error = Couldn't create identification, unknown error.
CREATE-AN-ACCOUNT = CREATE AN ACCOUNT
Create-observation-with-no-evidence = Create observation with no evidence
DATA-QUALITY = DATA QUALITY
DATA-QUALITY-ASSESSMENT = DATA QUALITY ASSESSMENT
Data-Quality-Assessment = Data Quality Assessment
Data-quality-assessment-can-taxon-still-be-confirmed-improved-based-on-the-evidence = Based on the evidence, can the Community Taxon still be improved?
Data-quality-assessment-community-taxon-species-level-or-lower = Community taxon at species level or lower
Data-quality-assessment-date-is-accurate = თარიღი ზუსტია
Data-quality-assessment-date-specified = Date specified
Data-quality-assessment-description-casual = This observation has not met the conditions for Research Grade status.
Data-quality-assessment-description-needs-id = This observation has not yet met the conditions for Research Grade status:
Data-quality-assessment-description-research = It can now be used for research and featured on other websites.
Data-quality-assessment-evidence-of-organism = Evidence of organism
Data-quality-assessment-has-photos-or-sounds = Has Photos or Sounds
Data-quality-assessment-id-supported-by-two-or-more = Has ID supported by two or more
Data-quality-assessment-location-is-accurate = ადგილმდებარეობა ზუსტია
Data-quality-assessment-location-specified = ადგილმდებარეობა მითითებულია
Data-quality-assessment-organism-is-wild = Organism is wild
Data-quality-assessment-recent-evidence-of-organism = Recent evidence of an organism
Data-quality-assessment-single-subject = Evidence related to a single subject
Data-quality-assessment-title-casual = This observation is Casual Grade
Data-quality-assessment-title-needs-id = ეს დაკვირვება საჭიროებს ID-ს
Data-quality-assessment-title-research = This observation is Research Grade!
DATE = DATE
Date = თარიღი
date-format-long = PP
date-format-month-day = MMM d
date-format-month-year = MMM yyyy
date-format-short = M/d/yy
DATE-OBSERVED = DATE OBSERVED
Date-observed = Date observed
Date-observed-header-short = Observed
DATE-OBSERVED-NEWEST = DATE OBSERVED - NEWEST TO OLDEST
DATE-OBSERVED-OLDEST = DATE OBSERVED - OLDEST TO NEWEST
Date-Range = Date Range
DATE-RANGE = DATE RANGE
date-to-date = { $d1 } - { $d2 }
DATE-UPLOADED = DATE UPLOADED
Date-uploaded = Date uploaded
Date-uploaded-header-short = Uploaded
DATE-UPLOADED-NEWEST = DATE UPLOADED - NEWEST TO OLDEST
DATE-UPLOADED-OLDEST = DATE UPLOADED - OLDEST TO NEWEST
Date-uploaded-on-header-short = Uploaded on:
datetime-difference-days = { $count }d
datetime-difference-hours = { $count }h
datetime-difference-minutes = { $count }m
datetime-difference-weeks = { $count }w
datetime-format-long = Pp
datetime-format-long-with-zone = Pp (zzz)
datetime-format-short = M/d/yy h:mm a
datetime-format-short-with-zone = M/d/yy h:mm a zzz
December = December
DELETE = DELETE
Delete-all-observations = Delete all observations
Delete-comment = Delete comment
DELETE-COMMENT--question = DELETE COMMENT?
Delete-current-observation = Delete current observation
Delete-observation = დაკვირვების წაშლა
DELETE-OBSERVATION--question = DELETE OBSERVATION?
Delete-photo = ფოტოს წაშლა
Delete-sound = Delete sound
Deletes-entered-text = Deletes entered text
Deleting-x-of-y--observations =
    Deleting { $currentDeleteCount } { $total ->
        [one] of { $total }
       *[other] of { $total } observations
    }
Deleting-x-of-y-observations-2 =
    Deleting { $currentDeleteCount } { $total ->
        [one] observation
       *[other] of { $total } observations
    }
Details = Details
DETAILS = DETAILS
Device-storage-full = Device storage full
Device-storage-full-description = iNaturalist may not be able to save your photos or may crash.
Disable-flash = Disable flash
Disable-location = ადგილმდებარეობის გამორთვა
Disagreement = *@{ $username } disagrees this is <0/>
DISCARD = DISCARD
DISCARD-ALL = DISCARD ALL
DISCARD-CHANGES = DISCARD CHANGES
DISCARD-FILTER-CHANGES = DISCARD FILTER CHANGES
DISCARD-MEDIA--question = DISCARD MEDIA?
DISCARD-OBSERVATION = DISCARD OBSERVATION
DISCARD-PHOTOS--question = DISCARD PHOTOS?
DISCARD-RECORDING = DISCARD RECORDING
DISCARD-SOUND--question = DISCARD SOUND?
DISCARD-X-OBSERVATIONS =
    { $count ->
        [one] DISCARD OBSERVATION
       *[other] DISCARD { $count } OBSERVATIONS
    }
DISCOVER-NATURE-AROUND-YOU = DISCOVER NATURE AROUND YOU
Dismiss-announcement = Dismiss announcement
Do-you-know-what-group-this-is-in = Do you know what group this is in?
DONATE = DONATE
DONATE-TO-INATURALIST = DONATE TO INATURALIST
DONE = DONE
Dont-have-an-account = <0>Don't have an account? </0><1>Sign up</1>
During-app-start-no-model-found = During app start there was no computer vision model found. There will be no AI camera.
Edit = შეცვლა
EDIT-COMMENT = EDIT COMMENT
Edit-comment = Edit comment
Edit-identification = Edit identification
EDIT-LOCATION = ადგილმდებარეობის შეცვლა
Edit-location = ადგილმდებარეობის შეცვლა
Edit-Observation = დაკვირვების რედაქტირება
Edit-your-profile-change-your-settings = Edit your profile, change your notifications settings, and manage all other parts of your account.
Edits-this-observations-taxon = Edits this observation's taxon
EDUCATORS = EDUCATORS
EMAIL = EMAIL
EMAIL-DEBUG-LOGS = EMAIL DEBUG LOGS
Enable-flash = Enable flash
Enable-location = ადგილმდებარეობის ჩართვა
Enable-notifications = Enable notifications
Endemic = Endemic
Endemic-to-place = Endemic to { $place }
Error = შეცდომა
ERROR = ERROR
ERROR-LOADING-DQA = ERROR LOADING IN DQA
Error-title = შეცდომა
ERROR-VOTING-IN-DQA = ERROR VOTING IN DQA
Error-voting-in-DQA-description = Your vote may not have been cast in the DQA. Check your internet connection and try again.
Establishment = Establishment
ESTABLISHMENT-MEANS = ESTABLISHMENT MEANS
Every-observation-needs = ყველა დაკვირვებას სჭირდება ადგილმდებარეობა, თარიღი და დრო, რათა იდენტიფიკატორებისთვის სასარგებლო იყოს. თქვენ შეგიძლიათ შეცვალოთ გეოკონფიდენციალურობა, თუ წუხთ ადგილმდებარეობის კონფიდენციალურობაზე.
Every-time-a-collection-project = Every time a collection project's page is loaded, iNaturalist will perform a quick search and display all observations that match the project's requirements. It is an easy way to display a set of observations, such as for a class project, a park, or a bioblitz without making participants take the extra step of manually adding their observations to a project.
EVIDENCE = EVIDENCE
Exact-Date = ზუსტი თარიღი
EXACT-DATE = EXACT DATE
except = except
EXPAND-MAP = EXPAND MAP
Experts-help-verify-and-improve-IDs = Experts help verify and improve IDs
Explore = გამოიკვლიეთ
EXPLORE = EXPLORE
Explore-Filters = Explore Filters
EXPLORE-IDENTIFIERS = EXPLORE IDENTIFIERS
EXPLORE-OBSERVATIONS = EXPLORE OBSERVATIONS
EXPLORE-OBSERVERS = EXPLORE OBSERVERS
EXPLORE-SPECIES = EXPLORE SPECIES
Failed-to-delete-sound = Failed to delete sound
Failed-to-log-in = Failed to log in
FEATURED = FEATURED
February = February
FEEDBACK = FEEDBACK
Feedback-Submitted = Feedback Submitted
Fetching-location = მიმდინარეობს ადგილმდებარეობის დადგენა...
Filter = Filter
FILTER-BY-A-PROJECT = FILTER BY A PROJECT
FILTER-BY-A-USER = FILTER BY A USER
Filter-by-observed-between-dates = Filter by observations observed between two specific dates
Filter-by-observed-during-months = Filter by observations observed during specific months
Filter-by-observed-on-date = Filter by observations observed on a specific date
Filter-by-uploaded-between-dates = Filter by observations uploaded between two specific dates
Filter-by-uploaded-on-date = Filter by observations uploaded on a specific date
Filters = ფილტრები
Flagged = Flagged
Flash = Flash
Flip-camera = Flip camera
FOLLOW = FOLLOW
FOLLOWING-X-PEOPLE =
    { $count ->
        [one] FOLLOWING { $count } PERSON
       *[other] FOLLOWING { $count } PEOPLE
    }
Forgot-Password = Forgot Password
GEOPRIVACY = GEOPRIVACY
Geoprivacy-status = Geoprivacy: { $status }
Get-an-instant-ID-of-any-plant-animal-fungus = Get an instant ID of any plant, animal, or fungus
Get-feedback-from-naturalists-and-experts-who-will-help-verify = Get feedback from naturalists and experts who will help verify and refine your identifications.
Get-your-identification-verified-by-real-people = Get your identification verified by real people in the iNaturalist community
Go-back = უკან
Google-Play-Services-Not-Installed = Google Play Services Not Installed
GRANT-PERMISSION = GRANT PERMISSION
Grant-Permission-title = Grant Permission
Group-Photos = Group Photos
Group-photos-onboarding = Group photos into observations– make sure there is only one species per observation
HELP = HELP
Help-create-Research-Grade-data-used-in-science-and-conservation = Help create Research Grade data used in science and conservation.
Help-protect-species = Help protect species
Help-us-translate-the-app = Help us translate the app!
Hide = Hide
Highest = Highest
HIGHEST-RANK = HIGHEST RANK
I-agree-to-the-Terms-of-Use = <0>ვეთანხმები გამოყენების პირობებსა და კონფიდენციალურობის პოლიტიკას და გავეცანი თემის წესებს (</0><1>სავალდებულოა</1><0>).</0>
Iconic-taxon-name = Iconic taxon name: { $iconicTaxon }
ID-in-Camera = ID in Camera
ID-Suggestions = ID-ის შეთავაზებები
ID-Withdrawn = ID Withdrawn
IDENTIFICATION = IDENTIFICATION
Identification-options = Identification options
IDENTIFICATIONS-WITHOUT-NUMBER =
    { $count ->
        [one] IDENTIFICATION
       *[other] IDENTIFICATIONS
    }
Identifiers = იდენთიფიკატორები
Identifiers-View = Identifiers View
IDENTIFY = IDENTIFY
Identify-organisms-in-real-time-with-your-camera = Identify organisms in real time with your camera
Identify-species-anywhere = Identify species anywhere
If-an-account-with-that-email-exists = If an account with that email exists, we've sent password reset instructions to your email.
If-you-have-an-existing-account-try-sign-in-reset = If you have an existing iNat account, try signing in with your username and password, or try resetting your password using the email address associated with your account.
If-you-leave-x-of-your-observations-removed =
    If you leave this traditional project, { $count ->
        [one] 1 of your observations
       *[other] { $count } of your observations
    } will also be removed from this project.
If-you-save-this-observation-and-upload-it-to-iNaturalist = If you save this observation and upload it to iNaturalist, other people may be able to help identify it.
If-you-want-to-collate-compare-promote = If you want to collate, compare, or promote a set of existing projects, then an Umbrella project is what you should use. For example the 2018 City Nature Challenge, which collated over 60 projects, made for a great landing page where anyone could compare and contrast each city's observations. Both Collection and Traditional projects can be used in an Umbrella project, and up to 500 projects can be collated by an Umbrella project.
If-youre-an-experienced-user-try-switching-to-Advanced-Mode = You have uploaded more than 100 observations. Try Advanced Mode for more ways to add and manage observations.
If-youre-seeing-this-error = If you're seeing this and you're online, iNat staff have already been notified. Thanks for finding a bug! If you're offline, please take a screenshot and send us an email when you're back on the Internet.
IGNORE-LOCATION = ᲐᲓᲒᲘᲚᲛᲓᲔᲑᲐᲠᲔᲝᲑᲘᲡ ᲘᲒᲜᲝᲠᲘᲠᲔᲑᲐ
Ignore-notifications = Ignore notifications
Ignoring-location = ადგილმდებარეობის იგნორირება
Import-Photos-From = Import Photos From
IMPORT-X-OBSERVATIONS =
    IMPORT { $count ->
        [one] 1 OBSERVATION
       *[other] { $count } OBSERVATIONS
    }
Improve-suggestions-by-using-your-location = გააუმჯობესეთ შეთავაზებები თქვენი ადგილმდებარეობის გამოყენებით
IMPROVE-THESE-SUGGESTIONS-BY-USING-YOUR-LOCATION = ᲒᲐᲐᲣᲛᲯᲝᲑᲔᲡᲔᲗ ᲔᲡ ᲨᲔᲗᲐᲕᲐᲖᲔᲑᲔᲑᲘ ᲗᲥᲕᲔᲜᲘ ᲐᲓᲒᲘᲚᲛᲓᲔᲑᲐᲠᲔᲝᲑᲘᲡ ᲒᲐᲛᲝᲧᲔᲜᲔᲑᲘᲗ
improving--identification = Improving
INATURALIST-ACCOUNT-SETTINGS = INATURALIST ACCOUNT SETTINGS
iNaturalist-AI-Camera = iNaturalist AI Camera
iNaturalist-can-use-your-location-to-give-you-better-identification-suggestions = iNaturalist-ს შეუძლია გამოიყენოს თქვენი ადგილმდებარეობა, რათა მოგაწოდოთ იდენტიფიკაციის უკეთესი შეთავაზებები. ჩვენ მას ასევე ვიყენებთ, რათა დაგეხმაროთ სიახლოვეს დაფიქსირებული სახეობების პოვნაში. თქვენი ადგილმდებარეობის გაზიარება ამარტივებს მეცნიერებისთვის სასარგებლო მონაცემების შექმნას.
INATURALIST-COMMUNITY = INATURALIST COMMUNITY
INATURALIST-FORUM = INATURALIST FORUM
iNaturalist-has-no-ID-suggestions-for-this-photo = iNaturalist-ს ამ ფოტოსთვის ID-ის შეთავაზებები არ აქვს.
INATURALIST-HELP-PAGE = INATURALIST HELP PAGE
iNaturalist-helps-you-identify = iNaturalist helps you identify the plants and animals around you while generating data for science and conservation. Get connected with a community of millions scientists and naturalists who can help you learn more about nature!
iNaturalist-identification-suggestions-are-based-on = iNaturalist-ის იდენტიფიკაციის შეთავაზებები ეფუძნება iNaturalist-ის თემის მიერ გაკეთებულ დაკვირვებებსა და იდენტიფიკაციებს, მათ შორის { $user1 }, { $user2 }, { $user3 } და მრავალი სხვისას.
iNaturalist-is-a-501 = iNaturalist is a 501(c)(3) non-profit in the United States of America (Tax ID/EIN 92-1296468).
iNaturalist-is-loading-ID-suggestions = iNaturalist ტვირთავს ID-ის შეთავაზებებს...
iNaturalist-is-supported-by = iNaturalist is supported by an independent, 501(c)(3) nonprofit organization based in the United States of America. The iNaturalist platform includes this app, Seek by iNaturalist, the iNaturalist website, and more.
iNaturalist-is-supported-by-our-community = iNaturalist is supported by our amazing community. From everyday naturalists who add observations and identifications, to curators who manage our taxonomy and help with moderation, to the volunteer translators who make iNaturalist more accessible to worldwide audiences, to our community-based donors, we are extraordinarily grateful to all the people in our community who make iNaturalist the platform it is.
iNaturalist-mission-is-to-connect = iNaturalist's mission is to connect people to nature and advance biodiversity science and conservation.
INATURALIST-MISSION-VISION = INATURALIST'S MISSION & VISION
INATURALIST-NETWORK = INATURALIST NETWORK
INATURALIST-SETTINGS = INATURALIST SETTINGS
INATURALIST-STAFF = { $inaturalist } STAFF
INATURALIST-STORE = INATURALIST STORE
INATURALIST-TEAM = INATURALIST TEAM
iNaturalist-users-who-have-left-an-identification = iNaturalist users who have left an identification on another user's observation
iNaturalist-users-who-have-observed = iNaturalist users who have observed a particular taxon at a particular time and place
iNaturalists-apps-are-designed-and-developed-3 = iNaturalist's apps are designed, developed, and supported by the iNaturalist team: Yaron Budowski, Amanda Bullington, Tony Iwane, Johannes Klein, Patrick Leary, Joanne Lin, Scott Loarie, Abhas Misraraj, Sylvain Morin, Carrie Seltzer, Alex Shepard, Thea Skaff, Angie Ta, Ken-ichi Ueda, Kirk van Gorkom, Jason Walthall, & Jane Weeden.
iNaturalists-vision-is-a-world = iNaturalist's vision is a world where everyone can understand and sustain biodiversity through the practice of observing wild organisms and sharing information about them.
Individual-encounters-with-organisms = ცალკეულ ორგანიზმებთან შეხვედრები კონკრეტულ დროსა და ადგილმდებარეობაზე, როგორც წესი, მტკიცებულებებთან ერთად
Internet-Connection-Required = Internet Connection Required
Intl-number = { $val }
Introduced = Introduced
Introduced-to-place = Introduced to { $place }
It-can-now-be-shared-for-use-in-research = It can now be shared for use in research
It-may-take-up-to-an-hour-to-remove-content = It may take up to an hour to completely delete all associated content
It-might-also-be = It might also be
It-might-be-one-of-these = It might be one of these
January = January
JOIN = შეერთება
Join-a-global-community-for-nature = Join a global community for nature
JOIN-PROJECT = JOIN PROJECT
JOIN-PROJECT--question = JOIN PROJECT?
JOINED = შეერთებული
Joined-date = Joined: { $date }
JOINED-X-PROJECTS =
    { $count ->
        [one] JOINED { $count } PROJECT
       *[other] JOINED { $count } PROJECTS
    }
JOURNAL-POSTS-WITHOUT-NUMBER =
    { $count ->
        [one] JOURNAL POST
       *[other] JOURNAL POSTS
    }
July = ივლისი
June = ივნისი
Just-make-sure-the-organism-is-wild = Just make sure the organism is wild (not a pet, zoo animal, or garden plant)
Last-Active-date = Last Active: { $date }
Lat-Lon = { NUMBER($latitude, maximumFractionDigits: 6) }, { NUMBER($longitude, maximumFractionDigits: 6) }
Lat-Lon-Acc = Lat: { NUMBER($latitude, maximumFractionDigits: 6) }, Lon: { NUMBER($longitude, maximumFractionDigits: 6) }, Acc: { $accuracy }
leading--identification = წამყვანი
Learn-from-people-who-verify-and-refine-your-identifications = Learn from people who verify and refine your identifications.
Learn-More = შეიტყვეთ მეტი
LEARN-MORE-ABOUT-THIS-GROUP = LEARN MORE ABOUT THIS GROUP
LEARN-MORE-ABOUT-THIS-SPECIES = LEARN MORE ABOUT THIS SPECIES
Least-Observed = Least Observed
LEAVE = LEAVE
LEAVE-PROJECT = LEAVE PROJECT
LEAVE-PROJECT--question = LEAVE PROJECT?
LEAVE-US-A-REVIEW = LEAVE US A REVIEW!
Lets-reset-your-password = Let’s reset your password.
Loading-iNaturalists-AI-Camera = Loading iNaturalist's AI Camera
Loads-content-that-requires-an-Internet-connection = Loads content that requires an Internet connection
LOCATION = ᲐᲓᲒᲘᲚᲛᲓᲔᲑᲐᲠᲔᲝᲑᲐ
Location = ადგილმდებარეობა
Location-accuracy-is-too-imprecise = ადგილმდებარეობის სიზუსტე არასაკმარისია იდენტიფიკატორების დასახმარებლად. გთხოვთ, მოაახლოვოთ.
LOCATION-TOO-IMPRECISE = ᲖᲔᲓᲛᲔᲢᲐᲓ ᲐᲠᲐᲖᲣᲡᲢᲘ ᲐᲓᲒᲘᲚᲛᲓᲔᲑᲐᲠᲔᲝᲑᲐ
LOG-IN = LOG IN
LOG-IN-TO-INATURALIST = LOG IN TO INATURALIST
Log-in-to-iNaturalist = Log in to iNaturalist
LOG-OUT = LOG OUT
LOG-OUT--question = LOG OUT?
Lowest = Lowest
LOWEST-RANK = LOWEST RANK
MAP = MAP
Map-Area = Map Area
March = March
Match-Screen = Match Screen
maverick--identification = Maverick
May = მაისი
MEDIA = MEDIA
Media-Type = Media Type
MEMBERS-WITHOUT-NUMBER =
    { $count ->
        [one] MEMBER
       *[other] MEMBERS
    }
Menu = მენიუ
Missing-Date = Missing Date
MISSING-EVIDENCE = MISSING EVIDENCE
Monthly-Donor = Monthly Donor
Months = თვეები
MONTHS = MONTHS
More = More
More-info = More info
MOST-FAVED = MOST FAVED
Most-faved = Most faved
Most-Observed-Default = Most Observed (Default)
MY-CONTENT--notifications = MY CONTENT
My-Observations = My Observations
My-Observations--bottom-tab = Me
Native = Native
Native-to-place = Native to { $place }
Navigates-to-AI-camera = Navigates to AI camera
Navigates-to-bulk-importer = Navigates to bulk importer
Navigates-to-camera = Navigates to camera
Navigates-to-explore = Navigates to explore
Navigates-to-log-in-screen = Navigates to log in screen
Navigates-to-main-menu = Navigates to main menu.
Navigates-to-notifications = Navigates to notifications
Navigates-to-observation-details = Navigates to observation details screen
Navigates-to-observation-edit-screen = Navigate to observation edit screen
Navigates-to-photo-importer = Navigates to photo importer
Navigates-to-previous-screen = Navigates to previous screen
Navigates-to-project-details = Navigates to project details
Navigates-to-sound-recorder = Navigates to sound recorder
Navigates-to-suggest-identification = Navigates to suggest identification
Navigates-to-taxon-details = Navigates to taxon details
Navigates-to-user-profile = Navigates to user profile
Navigates-to-your-observations = Navigates to your observations
NEARBY = ᲐᲮᲚᲝᲛᲓᲔᲑᲐᲠᲔ
Nearby = ᲐᲮᲚᲝᲛᲓᲔᲑᲐᲠᲔ
Needs-ID--quality-grade = საჭიროებს ID-ს
New-Observation = ახალი დაკვირვება
Newest-to-oldest = Newest to oldest
Next-observation = Next observation
Next-slide = Next slide
No-Camera-Available = No Camera Available
No-email-app-installed = No email app installed
No-email-app-installed-body = If you have another way of sending email, the address is { $address }
No-Location = ადგილმდებარეობა უცნობია
No-Media = No Media
No-model-found = No model found
No-projects-match-that-search = No projects match that search
No-results-found-for-that-search = No results found for that search.
No-results-found-try-different-search = No results found. Try a different search or adjust your filters.
no-rights-reserved-cc0 = no rights reserved (CC0)
none--accuracy = none
NONE--ranks = NONE
NOT-BY-ME = NOT BY ME
Not-enough-space-left-on-device = Not enough space left on device
Not-enough-space-left-on-device-try-again = There is not enough storage space left on your device to do that. Please free up some space and try again.
NOTES = ᲩᲐᲜᲐᲬᲔᲠᲔᲑᲘ
Notes = ჩანაწერები
NOTIFICATIONS = NOTIFICATIONS
Notifications--bottom-tab = Activity
notifications-user-added-comment-to-observation-by-you = <0>{ $userName }</0> added a comment to an observation by you
notifications-user-added-identification-to-observation-by-you = <0>{ $userName }</0> added an identification to an observation by you
notifications-user1-added-comment-to-observation-by-user2 = <0>{ $user1 }</0> added a comment to an observation by { $user2 }
notifications-user1-added-identification-to-observation-by-user2 = <0>{ $user1 }</0> added an identification to an observation by { $user2 }
November = November
Obervations-must-be-manually-added = Observations must be manually added to a traditional project, either during the upload stage or after the observation has been shared to iNaturalist. A user must also join a traditional project in order to add their observations to it.
Obscured = გაბუნდოვანება
Observation = Observation
Observation-Attribution = Observation: © { $userName } · { $restrictions }
Observation-Copyright = Observation Copyright: © { $userName } · { $restrictions }
Observation-has-no-photos-and-no-sounds = This observation has no photos and no sounds.
Observation-location-obscured-randomized-point = ამ დაკვირვების ადგილმდებარეობა ბუნდოვანია. თქვენ ხედავთ შემთხვევით შერჩეულ წერტილს დაფარვის პოლიგონის ფარგლებში.
Observation-location-obscured-you-can-see-your-own = ამ დაკვირვების ადგილმდებარეობა ბუნდოვანია. თქვენ ყოველთვის შეგიძლიათ ნახოთ თქვენი საკუთარი დაკვირვებების ადგილმდებარეობა.
Observation-location-obscured-you-have-permission = ამ დაკვირვების ადგილმდებარეობა ბუნდოვანია. თქვენ გაქვთ ამ ადგილმდებარეობის ნახვის ნებართვა.
Observation-options = Observation options
OBSERVATION-WAS-DELETED = OBSERVATION WAS DELETED
Observation-with-no-evidence = Observation with no evidence
Observations = დაკვირვებები
Observations-need-location-date--warning = iNaturalist-ის დაკვირვებებს სჭირდება ადგილმდებარეობა და თარიღი, რათა მეცნიერებისთვის სასარგებლო იყოს. გთხოვთ, ატვირთვამდე შეამოწმოთ ამ ხატულის მქონე დაკვირვებები.
Observations-View = Observations View
OBSERVATIONS-WITHOUT-NUMBER =
    { $count ->
        [one] OBSERVATION
       *[other] OBSERVATIONS
    }
OBSERVE-ORGANISMS = OBSERVE ORGANISMS
OBSERVED-AT--label = OBSERVED AT
OBSERVED-IN--label = OBSERVED IN
Observers = Observers
Observers-View = Observers View
October = October
Offline-DQA-description = The DQA may not be accurate. Check your internet connection and try again.
Offline-suggestions-may-differ-from-online = ოფლაინ შეთავაზებები შეიძლება განსხვავდებოდეს ონლაინ შეთავაზებებისგან, ხოლო ტაქსონის სურათები და საერთო სახელწოდებები შეიძლება არ ჩაიტვირთოს.
OK = კაი
Oldest-to-newest = Oldest to newest
Once-you-create-and-upload-observations = Once you create & upload observations, other members of our community can add identifications to help your observations reach research grade.
Open = გახსნა
OPEN-EMAIL = OPEN EMAIL
Open-menu = Open menu.
OPEN-SETTINGS = OPEN SETTINGS
Opens-add-comment-form = Opens add comment form.
Opens-AI-camera = Opens AI camera.
Opens-edit-comment-form = Opens edit comment form.
Opens-location-permission-prompt = ხსნის ადგილმდებარეობის ნებართვის მოთხოვნას
OR-SIGN-IN-WITH = OR SIGN IN WITH
Or-you-can-try-to-get-a-clearer-photo-by-zooming-in-getting-closer = Or, you can try to get a clearer photo by zooming in, getting closer, or trying a different angle.
Organism-is-captive = ორგანიზმი ტყვეობაშია
Organisms-that-are-identified-to-species = Organisms that are identified to species rank or below
OTHER-DATA = OTHER DATA
OTHER-SUGGESTIONS = ᲡᲮᲕᲐ ᲨᲔᲗᲐᲕᲐᲖᲔᲑᲔᲑᲘ
OTHERS--notifications = OTHERS
PASSWORD = PASSWORD
PEOPLE--title = PEOPLE
Photo-importer = Photo importer
PHOTO-LICENSING = PHOTO LICENSING
Photos = Photos
Photos-you-take-will-appear-here = Photos you take will appear here
Please-allow-Camera-Access = Please allow Camera Access
Please-allow-Location-Access = გთხოვთ, დაუშვათ ადგილმდებარეობაზე წვდომა
Please-allow-Microphone-Access = Please allow Microphone Access
Please-choose-a-different-password = Please choose a different password.
Please-Grant-Permission = Please Grant Permission
PLEASE-LOG-IN = PLEASE LOG IN
Please-log-in-again = Please log in again. We occasionally need to refresh your session to clear cached data and make sure the app is working its best.
Please-make-sure-your-password-is-at-least-6-characters = Please make sure your password is at least 6 characters.
Please-try-again-when-you-are-connected-to-the-internet = Please try again when you are connected to the Internet.
Please-try-again-when-you-are-online = Please try again when you are online!
Point-the-camera-at-an-animal-plant-or-fungus = Point the camera at an animal, plant, or fungus
POTENTIAL-DISAGREEMENT = POTENTIAL DISAGREEMENT
Potential-disagreement-description = <0>Is the evidence enough to confirm this is </0><1></1><0>?<0>
Potential-disagreement-disagree = <0>No, but this is a member of </0><1></1>
Potential-disagreement-unsure = <0>I don't know but I am sure this is </0><1></1>
Press-and-hold-to-view-more-options = Press and hold to view more options
Previous-observation = Previous observation
Previous-slide = Previous slide
Privacy-Policy = კონფიდენციალურობის პოლიტიკა
PRIVACY-POLICY = PRIVACY POLICY
Private = პირადი
PROJECT = PROJECT
Project-Members-Only = Project Members Only
PROJECT-REQUIREMENTS = PROJECT REQUIREMENTS
project-start-time-datetime = Start time: { $datetime }
PROJECTS = PROJECTS
Projects = პროექტები
PROJECTS-X = PROJECTS ({ $projectCount })
Pull-to-refresh-and-sync-observations = Pull to refresh and sync observations
Pull-to-refresh-notifications = Pull to refresh notifications
QUALITY-GRADE = QUALITY GRADE
Quality-Grade = Quality Grade
Quality-Grade-Casual--label = Quality Grade: Casual
Quality-Grade-Needs-ID--label = ხარისხის დონე: საჭიროებს ID-ს
Quality-Grade-Research--label = Quality Grade: Research
Ranks-CLASS = CLASS
Ranks-Class = კლასი
Ranks-COMPLEX = COMPLEX
Ranks-Complex = Complex
Ranks-EPIFAMILY = EPIFAMILY
Ranks-Epifamily = Epifamily
Ranks-FAMILY = FAMILY
Ranks-Family = ოჯახი
Ranks-FORM = FORM
Ranks-Form = ფორმა
Ranks-GENUS = GENUS
Ranks-Genus = გვარი
Ranks-GENUSHYBRID = GENUSHYBRID
Ranks-Genushybrid = Genushybrid
Ranks-HYBRID = HYBRID
Ranks-Hybrid = ჰიბრიდი
Ranks-INFRACLASS = INFRACLASS
Ranks-Infraclass = ინფრაკლასი
Ranks-INFRAHYBRID = INFRAHYBRID
Ranks-Infrahybrid = ინფრაჰიბრიდი
Ranks-INFRAORDER = INFRAORDER
Ranks-Infraorder = ინფრარიგი
Ranks-KINGDOM = KINGDOM
Ranks-Kingdom = Kingdom
Ranks-ORDER = ORDER
Ranks-Order = რიგი
Ranks-PARVORDER = PARVORDER
Ranks-Parvorder = პარვრიგი
Ranks-PHYLUM = PHYLUM
Ranks-Phylum = Phylum
Ranks-SECTION = SECTION
Ranks-Section = Section
Ranks-SPECIES = სახეობა
Ranks-Species = სახეობა
Ranks-Statefmatter = State of matter
Ranks-STATEOFMATTER = STATE OF MATTER
Ranks-SUBCLASS = SUBCLASS
Ranks-Subclass = Subclass
Ranks-SUBFAMILY = SUBFAMILY
Ranks-Subfamily = Subfamily
Ranks-SUBGENUS = SUBGENUS
Ranks-Subgenus = Subgenus
Ranks-Subkingdom = Subkingdom
Ranks-SUBORDER = SUBORDER
Ranks-Suborder = Suborder
Ranks-SUBPHYLUM = SUBPHYLUM
Ranks-Subphylum = Subphylum
Ranks-SUBSECTION = SUBSECTION
Ranks-Subsection = Subsection
Ranks-SUBSPECIES = SUBSPECIES
Ranks-Subspecies = Subspecies
Ranks-SUBTERCLASS = SUBTERCLASS
Ranks-Subterclass = Subterclass
Ranks-SUBTRIBE = SUBTRIBE
Ranks-Subtribe = Subtribe
Ranks-SUPERCLASS = SUPERCLASS
Ranks-Superclass = Superclass
Ranks-SUPERFAMILY = SUPERFAMILY
Ranks-Superfamily = Superfamily
Ranks-SUPERORDER = SUPERORDER
Ranks-Superorder = Superorder
Ranks-SUPERTRIBE = SUPERTRIBE
Ranks-Supertribe = Supertribe
Ranks-TRIBE = TRIBE
Ranks-Tribe = ტრიბა
Ranks-VARIETY = VARIETY
Ranks-Variety = Variety
Ranks-ZOOSECTION = ZOOSECTION
Ranks-Zoosection = Zoosection
Ranks-ZOOSUBSECTION = ZOOSUBSECTION
Ranks-Zoosubsection = Zoosubsection
Read-more-on-Wikipedia = Read more on Wikipedia
Record-a-sound = Record a sound
Record-animal-sounds = Record animal sounds
RECORD-NEW-SOUND = RECORD NEW SOUND
RECORD-SOUND = RECORD SOUND
Record-verb = Record
Recording-sound = Recording sound
Recording-stopped-Tap-to-play-the-current-recording = Recording stopped. Tap to play the current recording.
REDO-SEARCH-IN-MAP-AREA = REDO SEARCH IN MAP AREA
Remove-agreement = Remove agreement
Remove-disagreement = Remove disagreement
Remove-favorite = Remove favorite
Remove-identification = Remove identification
Remove-Photos = Remove Photos
Remove-project-filter = Remove project filter
Remove-taxon-filter = Remove taxon filter
Remove-user-filter = Remove user filter
Removes-this-observations-taxon = Removes this observation's taxon
Removes-your-vote-of-agreement = Removes your vote of agreement
Removes-your-vote-of-disagreement = Removes your vote of disagreement
Research-Grade--quality-grade = Research Grade
RESEARCH-GRADE--quality-grade = RESEARCH GRADE
Research-Grade-Status = Research Grade Status
RESET-PASSWORD = RESET PASSWORD
RESET-RECORDING = RESET RECORDING
RESET-SEARCH = RESET SEARCH
RESET-SOUND-header = RESET SOUND?
Reset-verb = ჩამოყრა
RESTART-APP = RESTART APP
Restore = აღდგენა
Reveal = Reveal
REVIEW-INATURALIST = REVIEW INATURALIST
REVIEWED = REVIEWED
Reviewed-observations-only = Reviewed observations only
Satellite--map-type = სატელიტი
SAVE = შენახვა
SAVE-ALL = SAVE ALL
Save-all-observations = Save all observations
SAVE-CHANGES = SAVE CHANGES
SAVE-FOR-LATER = SAVE FOR LATER
SAVE-LOCATION = ᲐᲓᲒᲘᲚᲛᲓᲔᲑᲐᲠᲔᲝᲑᲘᲡ ᲨᲔᲜᲐᲮᲕᲐ
Saved-Observation = Saved observation, in queue to upload
Scientific-Name = სამეცნიერო სახელწოდება
Scientific-Name-Common-Name = Scientific Name (Common Name)
SEARCH = SEARCH
Search = ძებნა
Search-for-a-project = Search for a project
SEARCH-FOR-A-TAXON = SEARCH FOR A TAXON
Search-for-a-taxon = Search for a taxon
SEARCH-LOCATION = ᲐᲓᲒᲘᲚᲛᲓᲔᲑᲐᲠᲔᲝᲑᲘᲡ ᲫᲘᲔᲑᲐ
SEARCH-PROJECTS = SEARCH PROJECTS
Search-suggestions-with-location = შეთავაზებების ძიება ადგილმდებარეობით
Search-suggestions-without-location = შეთავაზებების ძიება ადგილმდებარეობის გარეშე
SEARCH-TAXA = SEARCH TAXA
SEARCH-USERS = SEARCH USERS
See-observations-by-this-user-in-Explore = See observations by this user in Explore
See-observations-of-this-taxon-in-explore = See observations of this taxon in explore
See-project-members = See project members
See-species-observed-by-this-user-in-Explore = See species observed by this user in Explore
Select-a-date-and-time-for-observation = Select a date and time for observation
Select-captive-or-cultivated-status = აირჩიეთ დატყვევებულის ან კულტივირებულის სტატუსი
Select-geoprivacy-status = Select geoprivacy status
Select-or-drag-media = Select or drag media
Select-photo = Select photo
SELECT-THIS-TAXON = SELECT THIS TAXON
Select-user = Select user
Selects-iconic-taxon-X-for-identification = Selects iconic taxon { $iconicTaxon } for identification.
Separate-Photos = Separate Photos
September = September
SETTINGS = SETTINGS
Share = გაზიარება
SHARE-DEBUG-LOGS = SHARE DEBUG LOGS
Share-location = ადგილმდებარეობის გაზიარება
Share-map = Share map
Share-your-observation-where-it-can-help-scientists = Share your observation, where it can help scientists across the world better understand biodiversity.
SHOP-INATURALIST-MERCH = SHOP INATURALIST MERCH
Show-observation-options = Show observation options.
Showing-offline-search-results--taxa = Showing offline search results. To search for more species, try again when connected to the Internet.
Shows-identification-suggestions = აჩვენებს საიდენტიფიკაციო შეთავაზებებს
Shows-observation-creation-options = Shows observation creation options
Sign-in-with-Apple = Sign in with Apple
Sign-in-with-Apple-Failed = Sign in with Apple Failed
Sign-in-with-Google = Sign in with Google
Sign-in-with-Google-Failed = Sign in with Google Failed
Skip-for-now = Skip for now
Something-went-wrong = Something went wrong.
Sorry-this-observation-was-deleted = Sorry, this observation was deleted
Sorry-we-dont-know-how-to-open-that-URL = Sorry, we don't know how to open that URL: { $url }
SORT-BY = SORT BY
Sort-by = Sort by
SORT-SPECIES = SORT SPECIES
sound-playback-separator = /
Sound-recorder = Sound recorder
sound-recorder-help-A-recording-of = A recording of 5-15 seconds is best to help identifiers.
sound-recorder-help-Get-as-close-as-you-can = Get as close as you safely can to record the organism.
sound-recorder-help-Get-closer = Get closer
sound-recorder-help-Keep-it-short = Keep it short
sound-recorder-help-Make-sure = Make sure the sound of your own movement doesn’t cover up the sound of the organism.
sound-recorder-help-One-organism = One organism
sound-recorder-help-Stop-moving = Stop moving
sound-recorder-help-Try-to-isolate = შეეცადეთ, გამოყოთ ერთი ორგანიზმის ხმა. თუ ამას ვერ შეძლებთ, აუცილებლად დატოვეთ ჩანაწერი იმის შესახებ, თუ რომელ ორგანიზმს იწერთ.
Sounds = Sounds
Source-List = <0>(Source List: </0><1>{ $source }</1><0>)</0>
Species = სახეობა
Species-View = Species View
Species-with-the-least-observations-appear-first = Species with the least observations appear first
Species-with-the-most-observations-appear-first = Species with the most observations appear first
SPECIES-WITHOUT-NUMBER =
    { $count ->
        [one] SPECIES
       *[other] SPECIES
    }
Standard--map-type = Standard
Start-must-be-before-end = The start date must be before the end date.
Start-upload = Start upload
Starts-recording-sound = Starts recording sound
Stay-on-this-screen = დარჩით ამ გვერდზე, სანამ თქვენი ადგილმდებარეობა იტვირთება.
Still-loading = Still loading...
Still-need-help = Still need help? You can file a support request here.
Stop-upload = Stop upload
Stop-verb = შეჩერება
Stops-recording-sound = Stops recording sound
SUBMIT = SUBMIT
SUBMIT-ID-SUGGESTION = ID-ᲘᲡ ᲨᲔᲗᲐᲕᲐᲖᲔᲑᲘᲡ ᲒᲐᲒᲖᲐᲕᲜᲐ
SUGGEST-ID = SUGGEST ID
supporting--identification = მხარდამჭერი
Switches-to-tab = Switches to { $tab } tab.
Sync-observations = Sync observations
Syncing = სინქრონიზაცია...
Take-photo = Take photo
Take-photos = Take photos
Tap-here-to-switch-to-Advanced-Mode = Tap here to switch to Advanced Mode
Taxa = Taxa
TAXON = TAXON
TAXON-NAMES-DISPLAY = TAXON NAMES DISPLAY
TAXONOMIC-RANKS = TAXONOMIC RANKS
TAXONOMY-header = TAXONOMY
TEAM = TEAM
Terms-of-Use = Terms of Use
TERMS-OF-USE = TERMS OF USE
Thank-you-for-sharing-your-feedback = Thank you for sharing your feedback to help us improve!
Thanks-for-using-any-suggestions = გმადლობთ ამ აპლიკაციის გამოყენებისთვის! ხომ არ გაქვთ რაიმე რჩევა მისი შემქმნელებისთვის?
That-email-is-already-associated-with-an-account = That email is already associated with an account.
That-user-profile-doesnt-exist = That user profile doesn't exist
That-username-is-unavailable = That username is unavailable
The-AI-is-not-confident-It-may-be-one-of-the-IDs-below = The AI is not confident. It may be one of the IDs below.
The-AI-is-not-confident-Upload-to-ask-the-community = The AI is not confident. Upload to ask the community.
The-exact-location-will-be-hidden = ზუსტი ადგილმდებარეობა საჯაროდ დაიმალება და მის ნაცვლად განზოგადდება უფრო დიდ არეალზე. (საფრთხის ქვეშ და გადაშენების პირას მყოფი სახეობები ავტომატურად ბუნდოვანი ხდება).
The-iNaturalist-community-will-help-verify-and-refine-identifications = The iNaturalist community will help verify and refine identifications on your observations to create Research Grade data for science and conservation.
The-iNaturalist-Network = The iNaturalist network is a collection of localized websites that are fully connected to the global iNaturalist community. Network sites are supported by local institutions that promote local use and facilitate the use of data from iNaturalist to benefit local biodiversity.
The-location-will-not-be-visible-to-others = ადგილმდებარეობა არ იქნება ხილული სხვებისთვის, რამაც შეიძლება შეუძლებელი გახადოს დაკვირვების იდენტიფიცირება.
The-models-that-suggest-species = მოდელები, რომლებიც სახეობებს ვიზუალური მსგავსებისა და ადგილმდებარეობის მიხედვით გვთავაზობენ, ნაწილობრივ შექმნილია Sara Beery-სთან, Tom Brooks-თან, Elijah Cole-თან, Christian Lange-სთან, Oisin Mac Aodha-სთან, Pietro Perona-სა და Grant Van Horn-თან თანამშრომლობის წყალობით.
This-is-a-wild-organism = ეს ველური ორგანიზმია და ამ ადგილმდებარეობაზე ადამიანების მიერ არ არის მოთავსებული.
This-is-how-taxon-names-will-be-displayed = This is how all taxon names will be displayed to you across iNaturalist:
This-is-your-identification-other-people-may-help-confirm-it = This is your identification. Other people may help confirm it!
This-may-take-a-few-seconds = This may take a few seconds.
This-observation-has-no-comments-or-identifications-yet = This observation has no comments or identifications yet.
This-observation-has-not-met-the-conditions-required-to-meet-Research-Grade = This observation has not met the conditions required to meet Research Grade status
This-observation-is-not-eligible-for-research-grade-status = This observation is not eligible for research grade status. Learn more in the Data Quality Assessment below.
This-observation-is-research-grade-and-can-be-used-by-scientists = This observation is research grade and can be used by scientists!
This-observation-needs-more-identifications = This observation needs more identifications to reach Research Grade status
This-observation-needs-more-identifications-to-become-research-grade = This observation needs more identifications to become research grade.
This-observer-has-opted-out-of-the-Community-Taxon = This observer has opted out of the Community Taxon
This-organism-was-placed-by-humans = ეს ორგანიზმი ამ ადგილმდებარეობაზე ადამიანების მიერ არის მოთავსებული. ეს ეხება ისეთებს, როგორიცაა ბაღის მცენარეები, შინაური და ზოოპარკის ცხოველები.
This-user-has-no-followers = This user has no followers.
This-user-has-not-joined-any-projects = This user has not joined any projects.
This-user-is-not-following-anyone = This user is not following anyone.
To-sync-your-observations-to-iNaturalist = To sync your observations to iNaturalist, please log in.
To-view-nearby-organisms-please-enable-location = ახლომდებარე ორგანიზმების სანახავად, გთხოვთ, ჩართოთ ადგილმდებარეობა.
To-view-nearby-projects-please-enable-location = ახლომდებარე პროექტების სანახავად, გთხოვთ, ჩართოთ ადგილმდებარეობა.
Toggle-map-type = Toggle map type
TOP-ID-SUGGESTION = ID-ᲘᲡ ᲡᲐᲣᲙᲔᲗᲔᲡᲝ ᲨᲔᲗᲐᲕᲐᲖᲔᲑᲐ
Traditional-Project = Traditional Project
Umbrella-Project = Umbrella Project
UNFOLLOW = UNFOLLOW
UNFOLLOW-USER = UNFOLLOW USER?
Unknown--rank = უცნობია
Unknown--taxon = უცნობია
Unknown--user = უცნობია
Unknown-error = უცნობი შეცდომა
Unknown-organism = Unknown organism
Unreviewed-observations-only = Unreviewed observations only
Upload-Complete = Upload Complete
Upload-in-progress = Upload in progress
UPLOAD-NOW = UPLOAD NOW
Upload-photos = Upload photos
Upload-Progress = Upload { $uploadProgress } percent complete
UPLOAD-TO-INATURALIST = UPLOAD TO INATURALIST
Upload-x-observations =
    Upload { $count ->
        [one] 1 observation
       *[other] { $count } observations
    }
Upload-your-observations-to-contribute-data-to-help-save-species = Upload your observations to contribute data to help save species.
Uploaded-via-application = Uploaded via: { $application }
Uploading-x-of-y = Uploading { $currentUploadCount } of { $total }
Uploading-x-of-y-observations =
    { $total ->
        [one] Uploading { $currentUploadCount } observation
       *[other] Uploading { $currentUploadCount } of { $total } observations
    }
Use-iNaturalist-to-identify-any-living-thing = Use iNaturalist to identify any living thing
USE-LOCATION = ᲐᲓᲒᲘᲚᲛᲓᲔᲑᲐᲠᲔᲝᲑᲘᲡ ᲒᲐᲛᲝᲧᲔᲜᲔᲑᲐ
Use-the-devices-other-camera = Use the device's other camera.
Use-the-iNaturalist-camera-to-see-real-time-identifications-and-take-photos = Use the iNaturalist camera to see real-time identifications and take photos!
Use-your-devices-microphone-to-record-animal-sounds-and-share-them = Use your device’s microphone to record animal sounds and share them to get identifications and contribute to science!
USER = USER
User = User { $userHandle }
USERNAME-OR-EMAIL = USERNAME OR EMAIL
Users = Users
Using-location = მიმდინარეობს ადგილმდებარეობის გამოყენება
Verified-IDs-are-used-for-science-and-conservation = Verified IDs are used for science and conservation
Version-app-build = Version { $appVersion } ({ $buildVersion })
VIEW-ALL-X-PLACES = VIEW ALL { $count } PLACES
VIEW-ALL-X-PROJECTS = VIEW ALL { $count } PROJECTS
VIEW-ALL-X-TAXA = VIEW ALL { $count } TAXA
VIEW-ALL-X-USERS = VIEW ALL { $count } USERS
VIEW-CHILDREN-TAXA = VIEW CHILDREN TAXA
VIEW-DATA-QUALITY-ASSESSMENT = VIEW DATA QUALITY ASSESSMENT
VIEW-EDUCATORS-GUIDE = მასწავლებლის გზამკვლევის ნახვა
VIEW-FOLLOWERS = VIEW FOLLOWERS
VIEW-FOLLOWING = VIEW FOLLOWING
View-in-browser = ბრაუზერში ნახვა
VIEW-IN-EXPLORE = VIEW IN EXPLORE
VIEW-INATURALIST-HELP = VIEW INATURALIST HELP
View-photo = View photo
View-photo-licensing-info = View photo licensing info
VIEW-PROJECT-REQUIREMENTS = VIEW PROJECT REQUIREMENTS
VIEW-PROJECTS = VIEW PROJECTS
View-suggestions = შეთავაზებების ნახვა
Watch-your-notifications-for-identifications = Watch your notifications for identifications!
We-are-not-confident-enough-to-make-a-top-ID-suggestion = ჩვენ არ ვართ საკმარისად დარწმუნებული საუკეთესო ID-ის შეთავაზებისთვის, თუმცა აი რამდენიმე სხვა შეთავაზება:
Welcome-back = Welcome back!
WHAT-IS-INATURALIST = WHAT IS INATURALIST?
Whats-more-by-recording = What's more, by recording and sharing your observations, you'll create research-quality data for scientists working to better understand and protect nature. So if you like recording your findings from the outdoors, or if you just like learning about life, join us!
When-tapping-the-green-observation-button = When tapping the green observation button, open:
WIKIPEDIA = WIKIPEDIA
Wild = Wild
WILD-STATUS = WILD STATUS
Withdraw = Withdraw
WITHDRAW-ID = WITHDRAW ID
WITHDRAW-ID-QUESTION = WITHDRAW ID?
Withdraws-identification = Withdraws identification
Worldwide = Worldwide
WORLDWIDE = WORLDWIDE
Would-you-like-to-discard-your-current-recording-and-start-over = Would you like to discard your current recording and start over?
Would-you-like-to-suggest-the-following-identification = Would you like to suggest the following identification?
x-comments =
    { $count ->
        [one] { $count } comment
       *[other] { $count } comments
    }
x-failed =
    { $count ->
        [one] { $count } failed
       *[other] { $count } failed
    }
X-FOLLOWERS =
    { $count ->
        [one] { $count } FOLLOWER
       *[other] { $count } FOLLOWERS
    }
X-Identifications =
    { $count ->
        [one] { $count } Identification
       *[other] { $count } Identifications
    }
x-identifications =
    { $count ->
        [one] { $count } identification
       *[other] { $count } identifications
    }
X-Identifiers =
    { $count ->
        [one] { $count } Identifier
       *[other] { $count } Identifiers
    }
X-MEMBERS =
    { $count ->
        [one] { $count } MEMBER
       *[other] { $count } MEMBERS
    }
X-Observations =
    { $count ->
        [one] 1 Observation
       *[other] { $count } Observations
    }
X-OBSERVATIONS--below-number =
    { $count ->
        [one] OBSERVATION
       *[other] OBSERVATIONS
    }
X-observations-deleted =
    { $count ->
        [one] 1 observation deleted
       *[other] { $count } observations deleted
    }
X-observations-uploaded =
    { $count ->
        [one] 1 observation uploaded
       *[other] { $count } observations uploaded
    }
X-Observers =
    { $count ->
        [one] { $count } Observer
       *[other] { $count } Observers
    }
X-of-Y =
    { $x ->
        [one] 1
       *[other] { $x }
    } { $y ->
        [one] of { $y }
       *[other] of { $y }
    }
X-percent = { $count }%
X-percent-confidence = { $count }% confidence
X-PHOTOS =
    { $photoCount ->
        [one] 1 PHOTO
       *[other] { $photoCount } PHOTOS
    }
X-PHOTOS-X-OBSERVATIONS =
    { $photoCount ->
        [one] 1 PHOTO
       *[other] { $photoCount } PHOTOS
    }, { $observationCount ->
        [one] 1 OBSERVATION
       *[other] { $observationCount } OBSERVATIONS
    }
X-PHOTOS-Y-SOUNDS =
    { $photoCount ->
        [one] 1 PHOTO
       *[other] { $photoCount } PHOTOS
    }, { $soundCount ->
        [one] 1 SOUND
       *[other] { $soundCount } SOUNDS
    }
X-PROJECTS = { $projectCount } PROJECTS
x-saved =
    { $count ->
        [one] { $count } saved
       *[other] { $count } saved
    }
X-SOUNDS =
    { $count ->
        [one] 1 SOUND
       *[other] { $count } SOUNDS
    }
X-Species =
    { $count ->
        [one] { $count } Species
       *[other] { $count } Species
    }
X-SPECIES--below-number =
    { $count ->
        [one] SPECIES
       *[other] SPECIES
    }
x-uploaded =
    { $count ->
        [one] { $count } uploaded
       *[other] { $count } uploaded
    }
x-uploading =
    { $count ->
        [one] { $count } uploading
       *[other] { $count } uploading
    }
x-uploads-failed =
    { $count ->
        [one] { $count } upload failed
       *[other] { $count } uploads failed
    }
You-are-offline = You are offline
You-are-offline-Tap-to-reload = You are offline. Tap to reload.
You-are-offline-Tap-to-try-again = You are offline. Tap to try again.
You-can-add-up-to-20-media = You can add up to 20 photos and 20 sounds per observation.
You-can-also-check-out-merchandise = You can also check out merchandise for iNaturalist and Seek at our store below!
You-can-click-join-on-the-project-page = You can click “join” on the project page.
You-can-find-answers-on-our-help-page = You can find answers on our help page.
You-can-now-upload-your-observations-to-iNaturalist-and-contribute = You can now upload your observations to iNaturalist and contribute to global biodiversity research.
You-can-only-add-20-photos-per-observation = You can only add 20 photos per observation
You-can-still-share-the-file = You can still share the file with another app. If you can email it, please send it to { $email }
You-can-upload-this-observation-to-our-community = You can upload this observation to our community to get an identification from a real person, and help our AI improve its identifications in the future
You-changed-filters-will-be-discarded = You changed filters, but they were not applied to your explore search results.
You-have-no-notifications-get-started-by-creating-your-own-observations = You have no notifications! Get started by creating your own observations.
You-have-no-notifications-you-will-see-updates-to-obs-you-have-left-IDs-or-comments-on = You have no notifications! You will see updates to observations you have left IDs or comments on here.
You-have-opted-out-of-the-Community-Taxon = You have opted out of the Community Taxon
You-havent-joined-any-projects-yet = You haven’t joined any projects yet!
You-havent-observed-any-species-yet = You haven't observed any species yet.
You-likely-observed-a-species-in-this-group = You likely observed a species in this group
You-likely-observed-this-species = You likely observed this species
You-may-have-observed-a-species-in-this-group = You may have observed a species in this group
You-may-have-observed-this-species = You may have observed this species
You-may-notice-changes-to-how-things-look-and-flow = You may notice changes to how things look and flow. You can control your options in the settings.
You-must-install-Google-Play-Services-to-sign-in-with-Google = You must install Google Play Services to sign in with Google.
You-need-an-Internet-connection-to-do-that = You need an Internet connection to do that.
You-need-log-in-to-do-that = You need to log in to do that.
You-observed-a-species-in-this-group = You observed a species in this group
You-observed-this-species = You observed this species
You-will-see-notifications = You’ll see notifications here once you log in & upload observations.
Your-donation-to-iNaturalist = Your donation to iNaturalist supports the improvement and stability of the mobile apps and website that connects millions of people to nature and enables the protection of biodiversity worldwide!
Your-email-is-confirmed = Your email is confirmed! Please log in to continue.
Your-location-uncertainty-is-over-x-km = თქვენი ადგილმდებარეობის ცდომილება { $x } კმ-ზე მეტია, რაც ზედმეტად მაღალია იდენტიფიკატორების დასახმარებლად. შეცვალეთ ადგილმდებარეობა და მოაახლოვეთ, სანამ სიზუსტის წრე არ გამწვანდება და ცენტრში არ მოექცევა იქ, სადაც ორგანიზმი შენიშნეთ.
Your-observations-can-help-science = Your observations can help science!
Youre-ready-to-share-your-observations = You’re ready to share your observations!
Youve-denied-permission-prompt = You’ve denied permission. Please grant permission in the settings app.
Youve-previously-denied-camera-permissions = You've previously denied camera permissions, so please enable them in settings.
Youve-previously-denied-location-permissions = თქვენ ადრე უარყავით ადგილმდებარეობის ნებართვები, ამიტომ, გთხოვთ, ჩართოთ ისინი პარამეტრებში.
Youve-previously-denied-microphone-permissions = You’ve previously denied microphone permissions, so please enable them in settings.
Zoom-in-as-much-as-possible-to-improve = შეძლებისდაგვარად მოაახლოვეთ, რათა გააუმჯობესოთ ადგილმდებარეობის სიზუსტე და მიიღოთ უკეთესი იდენტიფიკაციები.
Zoom-to-current-location = მიმდინარე ადგილმდებარეობაზე მოახლოება
zoom-x = { $zoom }×
