### DO NOT EDIT THIS FILE!
###
### This file came from Crowdin and was normalized by ftl.js.
### It will be overwritten during the next translation sync. To add
### translations, go to https://crowdin.com/editor/inaturalistios/724
###

ABOUT = माहिती
Agree = सहमत
All = सर्व
All-observations = सर्व निरीक्षणे
all-rights-reserved = सर्व हक्क राखीव
All-taxa = सर्व वर्गीकरणे
Camera = कॅमेरा
Cancel = रद्द करा
Casual--quality-grade = अनौपचारिक
Close = बंद करा
Collection-Project = संग्रह प्रकल्प
Community-Guidelines = समुदाय मार्गदर्शक तत्वे
Date = दिनांक
Delete-observation = निरीक्षण खोडा
Delete-photo = छायाचित्र काढून टाका
Edit = दुरुस्ती किंवा बदल
Edit-Observation = निरीक्षण सुधारणा
Explore = आणखी पहा
improving--identification = सुधारणाशील
leading--identification = अग्रस्थानी
Learn-More = अधिक जाणून घ्या
Location = स्थान
maverick--identification = समूहविभक्त
Menu = मेनू
Nearby = जवळपास
Needs-ID--quality-grade = ओळख पटवा
No-Media = माध्यम नसलेली
Obscured = अस्पष्ट
OK = ठीक आहे
Open = खुली
Private = खासगी
Projects = प्रकल्प
Record-verb = नोंद
Research-Grade--quality-grade = संशोधन दर्जा
Reset-verb = पुन्हा पहिल्यासारखे करा
Satellite--map-type = उपग्रह
Search = शोधा
Share = शेअर करा
Stop-verb = थांबवा
supporting--identification = संमतीदर्शक
Taxa = प्रजाती
Traditional-Project = पारंपारिक प्रकल्प
Umbrella-Project = छत्र प्रकल्प
Unknown--rank = अज्ञात
Unknown--taxon = अज्ञात
Unknown--user = अज्ञात
View-in-browser = ब्राउझरमध्ये पहा
