### DO NOT EDIT THIS FILE!
###
### This file came from Crowdin and was normalized by ftl.js.
### It will be overwritten during the next translation sync. To add
### translations, go to https://crowdin.com/editor/inaturalistios/724
###

A-global-community-for-nature = Uma comunidade global para a natureza
ABOUT = SOBRE
ABOUT-COLLECTION-PROJECTS = SOBRE PROJETOS DE COLEÇÃO
ABOUT-INATURALIST = SOBRE INATURALIST
ABOUT-THE-DQA = SOBRE O DQA
About-the-DQA-description = A classificação de qualidade resume a exatidão, precisão, integridade, relevância e adequação de uma observação iNaturalist como dados de biodiversidade. Alguns atributos são determinados automaticamente, enquanto outros estão sujeitos a voto por usuários iNat. iNaturalist compartilha observações licenciadas de "grau de pesquisa" com vários parceiros para uso em ciência e conservação.
ABOUT-TRADITIONAL-PROJECTS = SOBRE PROJETOS TRADICIONAIS
ABOUT-UMBRELLA-PROJECTS = SOBRE PROJETOS GUARDA-CHUVA
accessible-comname-sciname = { $commonName }({ $scientificName })
accessible-sciname-comname = { $scientificName } ({ $commonName })
Account-Deleted = Conta Deletada
ACCOUNT-SETTINGS = CONFIGURAÇÕES DE CONTA
ACTIVITY = ATIVIDADE
Add-agreement = Adicionar acordo
ADD-AN-ID = Adicionar um ID
Add-an-ID-Later = Adicionar um ID mais tarde
ADD-COMMENT = Adicionar um comentário
Add-Date-Time = Adicionar Data/Hora
Add-disagreement = Adicionar Desacordo
ADD-EVIDENCE = ADICIONAR EVIDÊNCIA
Add-evidence = Adicionar evidência
Add-favorite = Adicionar favorito
Add-Location = Adicionar Localização
ADD-LOCATION-FOR-BETTER-IDS = ADICIONAR LOCAL PARA MELHORES IDS
Add-location-to-refresh-suggestions = Adicionar localização para atualizar as sugestões
Add-observations = Adicionar observações
ADD-OPTIONAL-COMMENT = Adicionar COMENTÁRIO OPCIONAL
Add-optional-notes = Adicionar notas opcionais
Adds-ID = Adicionar ID
Adds-your-vote-of-agreement = Adiciona seu voto de concordância
Adds-your-vote-of-disagreement = Adiciona seu voto de desacordo
Advanced-Mode = Modo avançado
ADVANCED-SETTINGS = CONFIGURAÇÕES AVANÇADAS
Affiliation = Afiliação: { $site }
After-capturing-or-importing-photos-show = Após capturar ou importar fotos, exibir:
Agree = Concordar
AGREE = CONCORDO
AGREE-WITH-ID = CONCORDAR COM O ID?
Agree-with-ID-description = Você gostaria de concordar com o ID e sugerir a seguinte identificação?
AI-Camera = Câmera IA
ALL = TODOS
All = Todas
All-observation-options--list = Todas as opções de observação: câmera IA iNaturalist, câmera normal, carregar fotos da galeria, e gravador de som
All-observations = Todas as observações
All-observations-need-a-date-and-location-to-be-used-for-science = Todas as observações precisam de uma data e local para serem usadas para ciência. Por favor, edite as Notas, se precisar dar mais informações.
All-organisms = Todos os organismos
all-rights-reserved = todos os direitos reservados
All-taxa = Todos os táxons
ALL-USERS-EXCEPT = TODOS OS USUÁRIOS EXCETO
ALLOW-LOCATION-ACCESS = PERMITIR ACESSO DE LOCALIZAÇÃO
Already-have-an-iNaturalist-account = Já tem uma conta iNaturalist?
An-Internet-connection-is-required = Uma conexão com a internet é necessária para carregar mais observações.
Analyzing-for-the-best-identification = Analisando a melhor identificação...
Any--date = Qualquer
Any--establishment-means = Qualquer
Any--media-type = Todas
Any--project = Todos
Any--quality-grade = Qualquer
Any--user = Todos
Anyone-using-iNaturalist-can-see = Qualquer um utilizando iNaturalist consegue ver onde essa espécie foi observada e cientistas podem mais facilmente utilizá-la para pesquisa.
APP-LANGUAGE = IDIOMA DO APLICATIVO
apple-full-name = { JOIN($namePrefix, $givenName, $middleName, $nickname, $familyName, $nameSuffix, separator: " ") }
APPLY-FILTERS = APLICAR FILTROS
Apply-filters = Aplicar filtros
April = Abril
Are-you-an-educator = Você é um educador que quer usar o iNaturalist com seus alunos?
Are-you-sure-you-want-to-log-out = Você tem certeza que deseja sair da sua conta iNaturalist? Todas as obsevações que não foram enviadas para o iNaturalist serão deletadas.
attribution-cc-by = alguns direitos reservados (CC BY)
attribution-cc-by-nc = alguns direitos reservados (CC BY-NC)
attribution-cc-by-nc-nd = alguns direitos reservados (CC BY-NC-ND)
attribution-cc-by-nc-sa = alguns direitos reservados (CC BY-NC-SA)
attribution-cc-by-nd = alguns direitos reservados (CC BY-ND)
attribution-cc-by-sa = alguns direitos reservados (CC BY-SA)
August = Agosto
BACK-TO-LOGIN = VOLTAR PARA LOGIN
Bulk-importer = Importar em massa
By-exiting-changes-not-saved = Ao sair, as alterações de sua observação não serão salvas
By-exiting-observation-not-saved = Ao sair, sua observação não será salva.
By-exiting-your-observations-not-saved = Ao sair, suas observações não serão salvas. Você pode salvá-las em seu aparelho, ou você pode deletá-las.
By-exiting-your-photos-will-not-be-saved = Ao sair, suas fotos não serão salvas.
By-exiting-your-recorded-sound-will-not-be-saved = Ao sair, seu som gravado não será salvo.
BY-ME = POR MIM
By-uploading-your-observation-to-iNaturalist-you-can = Ao enviar sua observação ao iNaturalist, você pode:
Camera = Câmera
CANCEL = CANCELAR
Cancel = Cancelar
Captive-Cultivated = Cativo/Cultivado
Casual--quality-grade = Casual
CC-BY = CC BY
CC-BY-NC = CC BY-NC
CC-BY-NC-ND = CC BY-NC-ND
CC-BY-NC-SA = CC BY-NC-SA
CC-BY-ND = CC BY-ND
CC-BY-SA = CC BY-SA
CC0 = CC0
CHANGE-APP-LANGUAGE = ALTERAR IDIOMA DO APLICATIVO
CHANGE-DATE = ALTERAR DATA
Change-date = Alterar data
CHANGE-END-DATE = ALTERAR DATA FINAL
Change-end-date = Alterar data final
Change-observations-sort-order = Change observations sort order
Change-project = Alterar projeto
Change-species-sort-order = Change species sort order
CHANGE-START-DATE = ALTERAR DATA DE INÍCIO
Change-start-date = Alterar data de ínicio
Change-taxon = Alterar táxon
Change-taxon-filter = Alterar filtro de táxon
Change-user = Alterar usuário
Change-zoom = Alterar zoom
CHECK-YOUR-EMAIL = VERIFICE O SEU EMAIL!
CHOOSE-A-USERNAME = ESCOLHA UM NOME DE USUÁRIO
Choose-taxon = Escolha táxon
Choose-top-taxon = Escolha táxon principal
Clear = Limpar	
Close = Fechar
Close-permission-request-screen = Fechar tela de requisição de permissão
Close-search = Fechar pesquisa
Closes-explanation = Fecha explicação
Closes-introduction = Fechar introdução
Closes-withdraw-id-sheet = Fecha a aba "Retirar Identificação"
COLLABORATORS = COLABORADORES
Collection-Project = Projeto de Coleção
Combine-Photos = Combinar fotos
COMMENT = COMENTÁRIO
Comment-options = Opções de comentário
Common-Name-Scientific-Name = Nome Comum (Nome Científico)
Community-Discussion = Discussão da Comunidade
Community-Guidelines = Diretrizes da Comunidade
COMMUNITY-GUIDELINES = COMUNIDADE DE DIRETRIZES
Confidence--label = confiança
CONFIRM = CONFIRMAR
Congratulations-You-made-your-first-observation = Parabéns. Voce enviou sua primeira observação!
Connect-with-expert-naturalists = Conecte-se com naturalistas esperientes
Connect-with-other-naturalists = Conecte-se com outros naturalistas e participe de conversas.
Connection-problem-Please-try-again-later = Problema de conexão. Tente novamente mais tarde.
CONTACT-SUPPORT = CONTATE O SUPORTE
CONTINUE = CONTINUAR
Coordinates-copied-to-clipboard = Coordenadas copiada para a área de transferência
Copy-coordinates = Copiar Coordenadas
Copyright = Direitos Autorais
Could-not-find-a-camera-on-this-device = Não foi possível encontrar uma câmera neste dispositivo
Couldnt-create-comment = Não foi possível criar comentário
Couldnt-create-identification-error = Não foi possível criar identificação { $error }
Couldnt-create-identification-unknown-error = Não foi possível criar identificação, erro desconhecido.
CREATE-AN-ACCOUNT = CRIAR UMA CONTA
Create-observation-with-no-evidence = Create observation with no evidence
DATA-QUALITY = QUALIDADE DE DADOS
DATA-QUALITY-ASSESSMENT = AVALIAÇÃO DE QUALIDADE DE DADOS
Data-Quality-Assessment = Avaliação de qualidade dos dados
Data-quality-assessment-can-taxon-still-be-confirmed-improved-based-on-the-evidence = Com base nas evidências, a Comunidade do Táxon pode ainda ser melhorada?
Data-quality-assessment-community-taxon-species-level-or-lower = Comunidade do táxon ao nível de espécie ou inferior
Data-quality-assessment-date-is-accurate = Data correta
Data-quality-assessment-date-specified = Data especificada
Data-quality-assessment-description-casual = Esta observação não atendeu às condições para o nível da Classe de Pesquisa.
Data-quality-assessment-description-needs-id = Esta observação ainda não atendeu às condições para o nível da Classe de Pesquisa.
Data-quality-assessment-description-research = Agora pode ser utilizada para pesquisa e visualizada em outros sites.
Data-quality-assessment-evidence-of-organism = Evidência de organismo
Data-quality-assessment-has-photos-or-sounds = Possui fotos ou sons
Data-quality-assessment-id-supported-by-two-or-more = Possui ID suportado por dois ou mais
Data-quality-assessment-location-is-accurate = Localização correta
Data-quality-assessment-location-specified = Localização especificada
Data-quality-assessment-organism-is-wild = Organismo selvagem
Data-quality-assessment-recent-evidence-of-organism = Evidência recente de um organismo
Data-quality-assessment-single-subject = Evidencia relacionada a um único assunto
Data-quality-assessment-title-casual = Esta observação é de Classe Informal
Data-quality-assessment-title-needs-id = Esta observação necessita de identificação
Data-quality-assessment-title-research = Esta observação é Nível de Pesquisa!
DATE = DATA
Date = Data
date-format-long = PP
date-format-month-day = d MMM
date-format-month-year = MM yy
date-format-short = M/d/yy
DATE-OBSERVED = DATA OBSERVADA
Date-observed = Data de observação
Date-observed-header-short = Observado
DATE-OBSERVED-NEWEST = DATA OBSERVADA — MAIS NOVA PARA A MAIS ANTIGA
DATE-OBSERVED-OLDEST = DATA OBSERVADA — MAIS PARA MAIS RECENTE
Date-Range = Intervalo de datas
DATE-RANGE = INTERVALO DE DATA
date-to-date = { $d1 } - { $d2 }
DATE-UPLOADED = DATA DE UPLOAD
Date-uploaded = Data carregada
Date-uploaded-header-short = Enviado
DATE-UPLOADED-NEWEST = DATA ENVIADA — MAIS NOVA PARA A MAIS ANTIGA
DATE-UPLOADED-OLDEST = DATA ENVIADA — MAIS ANTIGA PARA A MAIS NOVA
Date-uploaded-on-header-short = Carregado em:
datetime-difference-days = { $count }d
datetime-difference-hours = { $count }h
datetime-difference-minutes = { $count }m
datetime-difference-weeks = { $count }s
datetime-format-long = PP
datetime-format-long-with-zone = Pp (zzz)
datetime-format-short = M/d/yy H:mm a
datetime-format-short-with-zone = M/d/yy h:mm a zzz
December = Dezembro
DELETE = EXCLUIR
Delete-all-observations = Excluir todas as observações
Delete-comment = Excluir comentário
DELETE-COMMENT--question = EXCLUIR COMENTÁRIO?
Delete-current-observation = Excluir observação atual
Delete-observation = Excluir observação
DELETE-OBSERVATION--question = EXCLUIR OBSERVAÇÃO?
Delete-photo = Excluir foto
Delete-sound = Excluir som
Deletes-entered-text = Excluir texto inserido
Deleting-x-of-y--observations =
    Apagando { $currentDeleteCount } { $total ->
        [one] de { $total }
       *[other] de { $total } observações
    }
Deleting-x-of-y-observations-2 =
    Apagando { $currentDeleteCount } { $total ->
        [one] observação
       *[other] de { $total } observações
    }
Details = Detalhes
DETAILS = DETALHES
Device-storage-full = Armazenamento do dispositivo cheio
Device-storage-full-description = iNaturalist pode não ser capaz de salvar suas fotos ou pode falhar.
Disable-flash = Desligar flash
Disable-location = Desativar localização
Disagreement = *@{ $username } discorda ser <0/>
DISCARD = DESCARTAR
DISCARD-ALL = DESCARTAR TUDO
DISCARD-CHANGES = DESCARTAR ALTERAÇÕES
DISCARD-FILTER-CHANGES = DESCARTAR ALTERAÇÕES DO FILTRO
DISCARD-MEDIA--question = DESCARTAR MÍDIA?
DISCARD-OBSERVATION = DESCARTAR OBSERVAÇÃO
DISCARD-PHOTOS--question = DESCARTAR FOTOS?
DISCARD-RECORDING = DESCARTAR GRAVAÇÃO
DISCARD-SOUND--question = DESCARTAR SOM?
DISCARD-X-OBSERVATIONS =
    { $count ->
        [um] DESCARTAR OBSERVAÇÃO
       *[outro] DESCARTAR { $count } OBSERVAÇÕES
    }
DISCOVER-NATURE-AROUND-YOU = DESCUBRA A NATUREZA AO SEU REDOR
DISMISS = DESCARTAR
Do-you-know-what-group-this-is-in = Sabe em que grupo isto está?
DONATE = Doar
DONATE-TO-INATURALIST = DOAR PARA INATURALISTA
DONE = CONCLUÍDO
Dont-have-an-account = <0>Não tem uma conta? </0><1>Cadastre-se</1>
During-app-start-no-model-found = Durante o início do aplicativo não havia nenhum modelo de visão computacional encontrado. Não haverá câmera IA.
Edit = Editar
EDIT-COMMENT = EDITAR COMENTÁRIO
Edit-comment = Editar comentário
Edit-identification = Editar identificação
EDIT-LOCATION = EDITAR LOCAL
Edit-location = Editar localização
Edit-Observation = Editar Observação
Edit-your-profile-change-your-settings = Edite seu perfil, altere suas configurações de notificações e gerencie todas as outras partes da sua conta.
Edits-this-observations-taxon = Edita estas observações do táxon
EDUCATORS = EDUCADORES
EMAIL = Endereço eletrônico
EMAIL-DEBUG-LOGS = REGISTROS DE DEPURAÇÃO DE ENDEREÇO ELETRÔNICO
Enable-flash = Habilitar luz
Enable-location = Ativar localização
Enable-notifications = Ativar notificações
Endemic = Endêmica
Endemic-to-place = Endêmico para { $place }
Error = Erro
ERROR = ERRO
ERROR-LOADING-DQA = ERRO AO CARREGAR NO DQA
Error-title = Erro
ERROR-VOTING-IN-DQA = ERRO AO VOTAR NO DQA
Error-voting-in-DQA-description = Seu voto pode não ter sido transmitido no DQA. Verifique sua conexão com a internet e tente novamente.
Establishment = Estabelecimento
ESTABLISHMENT-MEANS = MODOS DE ESTABELECIMENTO
Every-observation-needs = Toda observação precisa de uma localização, data e hora para ser útil para identificadores. Você pode editar a geoprivacidade se estiver preocupado com a privacidade da localização.
Every-time-a-collection-project = Cada vez que a página de um projeto de coleção é carregada, o iNaturalist irá realizar uma pesquisa rápida e exibir todas as observações que correspondem aos requisitos do projeto. É uma maneira fácil de exibir um conjunto de observações, como para um projeto de classe, um parque, ou uma bioblitz sem fazer os participantes darem o passo extra de adicionar manualmente suas observações em um projeto.
EVIDENCE = EVIDÊNCIA
Exact-Date = Data exata
EXACT-DATE = DATA DE EXACT
except = exceto
EXPAND-MAP = EXPANDIR MAPA
Experts-help-verify-and-improve-IDs = Especialistas ajudam a verificar e melhorar IDs
Explore = Explorar
EXPLORE = EXPLORAR
Explore-Filters = Explorar Filtros
EXPLORE-IDENTIFIERS = EXPLORAR IDENTIFICADORES
EXPLORE-OBSERVATIONS = EXPLORAR OBSERVAÇÕES
EXPLORE-OBSERVERS = EXPLORAR OBSERVADORES
EXPLORE-SPECIES = EXPLORAR ESPÉCIES
Failed-to-delete-sound = Falha ao excluir som
Failed-to-log-in = Falha ao iniciar sessão
FEATURED = EM DESTAQUE
February = Fevereiro
FEEDBACK = Avaliação
Feedback-Submitted = Feedback Enviado
Fetching-location = Buscando localização...
Filter = Filtrar
FILTER-BY-A-PROJECT = FILTRAR POR UM PROJETO
FILTER-BY-A-USER = FILTRAR POR UM USUÁRIO
Filter-by-observed-between-dates = Filtrar por observações observadas entre duas datas específicas
Filter-by-observed-during-months = Filtrar por observações observadas durante meses específicos
Filter-by-observed-on-date = Filtrar por observações observadas em uma data específica
Filter-by-uploaded-between-dates = Filtrar por observações carregadas entre duas datas específicas
Filter-by-uploaded-on-date = Filtrar por observações carregadas em uma data específica
Filters = Filtros
Flagged = Sinalizado
Flash = Lampejo
Flip-camera = Virar câmera
FOLLOW = SEGUIR
FOLLOWING-X-PEOPLE =
    { $count ->
        [one] SEGUINDO { $count } PESSOA
       *[other] SEGUINDO { $count } PESSOAS
    }
Forgot-Password = Esqueci a senha
GEOPRIVACY = GEOPRIVACIDADE
Geoprivacy-status = Geoprivacidade: { $status }
Get-an-instant-ID-of-any-plant-animal-fungus = Obtenha uma identificação instantânea de qualquer planta, animal ou fungo
Get-feedback-from-naturalists-and-experts-who-will-help-verify = O feedback de naturalistas e especialistas o ajudarão a verificar e refinar suas identificações.
Get-your-identification-verified-by-real-people = Obtenha sua identificação verificada por pessoas reais na comunidade iNaturalist
Go-back = Voltar
Google-Play-Services-Not-Installed = Serviços do Google Play não instalados
GRANT-PERMISSION = CONCEDER PERMISSÃO
Grant-Permission-title = Conceder Permissão
Group-Photos = Fotos de Grupos
Group-photos-onboarding = Agrupe fotos em observações - verifique se há apenas uma espécie por observação
HELP = AJUDA
Help-create-Research-Grade-data-used-in-science-and-conservation = Ajude a criar dados de grau de pesquisa a serem usados para ciência e conservação.
Help-protect-species = Ajude a proteger espécies
Hide = Ocultar
Highest = Mais Alto
HIGHEST-RANK = RANQUE MAIS ALTO
I-agree-to-the-Terms-of-Use = <0>Concordo com os Termos de Uso e Política de Privacidade e revisei as Diretrizes da Comunidade (</0><1>obrigatório</1><0>).</0>
Iconic-taxon-name = Nome do táxon icônico: { $iconicTaxon }
ID-in-Camera = ID in Camera
ID-Suggestions = Sugestões de ID
ID-Withdrawn = ID retirada
IDENTIFICATION = IDENTIFICAÇÃO
Identification-options = Opções de identificação
IDENTIFICATIONS-WITHOUT-NUMBER =
    { $count ->
        [um] IDENTIFICAÇÃO
       *[outro] IDENTIFICAÇÕES
    }
Identifiers = Identificadores
Identifiers-View = Visualização dos identificadores
IDENTIFY = IDENTIFY
Identify-organisms-in-real-time-with-your-camera = Identifique organismos em tempo real com sua câmera
Identify-species-anywhere = Identifique espécies em qualquer lugar
If-an-account-with-that-email-exists = Se existe uma conta com esse endereço eletrônico, enviamos instruções de redefinição de senha para o seu endereço eletrônico.
If-you-have-an-existing-account-try-sign-in-reset = Se você já tiver uma conta iNat, tente entrar com seu nome de usuário e senha, ou tente redefinir sua senha usando o endereço de e-mail associado à sua conta.
If-you-leave-x-of-your-observations-removed =
    Se você deixar este projeto tradicional, { $count ->
        [one] 1 de suas observações
       *[other] { $count } de suas observações
    } também serão removidas deste projeto.
If-you-save-this-observation-and-upload-it-to-iNaturalist = Se você salvar esta observação e enviá-la para o iNaturalist, outras pessoas poderão ajudar a identificá-la.
If-you-want-to-collate-compare-promote = Se você quiser reunir, comparar ou promover um conjunto de projetos existentes, então você deve utilizar um Projeto Global. Um exemplo foi o Desafio da Natureza Urbana 2018, o qual reuniu mais de 60 projetos, e foi produzido para uma excelente página de destino onde qualquer um poderia comparar e contrastar as observações de cada cidade. Tanto os projetos de Coleção quanto os Tradicionais podem ser utilizados em um projeto Global, e até 500 projetos podem ser reunidos por um projeto Global.
If-youre-seeing-this-error = Se você está vendo isto e está conectado na Internet, a equipe inaturalista já foi notificada. Obrigado por encontrar um erro! Se você não está conectado, por favor faça uma captura de tela e nos envie através de nosso endereço eletrônico assim que você estiver novamente conectado na Internet.
IGNORE-LOCATION = IGNORAR LOCALIZAÇÃO
Ignore-notifications = Ignorar notificações
Ignoring-location = Ignorando localização
Import-Photos-From = Importar fotos de...
IMPORT-X-OBSERVATIONS =
    IMPORTAR { $count ->
        [uma] 1 OBSERVAÇÃO
       *[outra] { $count } OBSERVAÇÕES
    }
Improve-suggestions-by-using-your-location = Melhore as sugestões usando sua localização
IMPROVE-THESE-SUGGESTIONS-BY-USING-YOUR-LOCATION = MELHORE ESTAS SUGESTÕES UTILIZANDO SUA LOCALIZAÇÃO
improving--identification = Melhorando
INATURALIST-ACCOUNT-SETTINGS = CONFIGURAÇÕES DA CONTA INATURALISTA
iNaturalist-AI-Camera = Câmera IA do inaturalista
iNaturalist-can-save-photos-you-take-in-the-app-to-your-devices-library = iNaturalist pode salvar as fotos que você tira no aplicativo na galeria do seu dispositivo.
iNaturalist-can-use-your-location-to-give-you-better-identification-suggestions = iNaturalist pode usar sua localização para lhe dar sugestões de identificação melhores. Também usamos para ajudá-lo a encontrar espécies vistas nas proximidades. Compartilhar sua localização facilita a criação de dados úteis para ciência.
INATURALIST-COMMUNITY = COMUNIDADE INATURALISTA
INATURALIST-FORUM = FÓRUM INATURALISTA
iNaturalist-has-no-ID-suggestions-for-this-photo = O inaturalista não tem sugestões de identificação para esta foto.
INATURALIST-HELP-PAGE = PÁGINA DE AJUDA INATURALISTA
iNaturalist-helps-you-identify = O inaturalista ajuda você a identificar as plantas e animais ao seu redor enquanto gera dados para a ciência e sua conservação. Conecte-se com uma comunidade de milhões de cientistas e naturalistas que podem ajudá-lo a aprender mais sobre a natureza!
iNaturalist-identification-suggestions-are-based-on = As sugestões de identificação do inaturalista baseiam-se em observações e identificações feitas pela comunidade inaturalista, incluindo { $user1 }, { $user2 }, { $user3 }e muitas outras.
iNaturalist-is-a-501 = Inaturalista é uma organização sem fins lucrativos dos Estados Unidos da América (ID/EIN 92–1 296 468).
iNaturalist-is-loading-ID-suggestions = Inaturalista está carregando sugestões de identificação...
iNaturalist-is-supported-by = O INATURALISTA é apoiado por uma organização independente, 501(c)(3) sem fins lucrativos, baseada nos Estados Unidos da América. A plataforma Inaturalista inclui este aplicativo, Procure por inaturalista, site, e muito mais.
iNaturalist-is-supported-by-our-community = iNaturalist é apoiada pela nossa incrível comunidade. Estamos extraordinariamente gratos a todas as pessoas da nossa comunidade que fazem do iNaturalist a plataforma que ela é, aos naturalistas que adicionam observações e identificações, aos curadores que ajudam na curadoria da taxonomia e moderação, aos tradutores voluntários que tornam iNaturalist mais acessível para o público mundial e também aos nossos doadores comunitários.
iNaturalist-mission-is-to-connect = A missão do inaturalista é conectar as pessoas à natureza e promover a ciência e a conservação da biodiversidade.
INATURALIST-MISSION-VISION = MISSÃO e VISSÃO DA INATURALISTA
INATURALIST-NETWORK = REDE INATURALISTA
INATURALIST-SETTINGS = CONFIGURAÇÕES DA CONTA INATURALISTA
INATURALIST-STAFF = { $inaturalist } EQUIPE
INATURALIST-STORE = LOJA INATURALISTA
INATURALIST-TEAM = TIME INATURALISTA
iNaturalist-users-who-have-left-an-identification = Usuários inaturalista que deixaram uma identificação em observações de outro usuário
iNaturalist-users-who-have-observed = Usuários do inaturalista que observaram um táxon particular em determinado momento e local
iNaturalists-apps-are-designed-and-developed-3 = Os aplicativos do iNaturalist são projetados, desenvolvidos e apoiados pelo time do iNaturalist: Yaron Budowski, Amanda Bullington, Tony Iwane, Johannes Klein, Patrick Leary, Joanne Lin, Scott Loarie, Abhas Misraraj, Sylvain Morin, Carrie Seltzer, Alex Shepard, Thea Skaff, Angie Ta, Ken-ichi Ueda, Kirk van Gorkom, Jason Walthall e Jane Weeden.
iNaturalists-vision-is-a-world = A visão do inaturalista é um mundo onde todos podem entender e sustentar a biodiversidade através da prática de observação dos organismos selvagens e compartilhamento das informações sobre eles.
Individual-encounters-with-organisms = Encontros individuais com organismos em determinado momento e local, geralmente com evidências
Internet-Connection-Required = Necessária conexão com Internet
Intl-number = { $val }
Introduced = Introduzido
Introduced-to-place = Introduzido para  { $place }
It-can-now-be-shared-for-use-in-research = Agora pode ser compartilhado para uso em pesquisas
It-may-take-up-to-an-hour-to-remove-content = Pode levar até uma hora para apagar completamente todo o conteúdo associado
It-might-also-be = Poderia também ser
It-might-be-one-of-these = Pode ser um desses
January = Janeiro
JOIN = JUNTE-SE
Join-a-global-community-for-nature = Junte-se a uma comunidade global pela natureza
JOIN-PROJECT = JUNTE-SE AO PROJETO
JOIN-PROJECT--question = JUNTAR-SE AO PROJETO?
JOINED = A QUE ADERIU
Joined-date = Entrou:  { $date }
JOINED-X-PROJECTS =
    { $count ->
        [one] PARTICIPANDO DE { $count } PROJETO
       *[other] PARTICIPANDO DE { $count } PROJETOS
    }
JOURNAL-POSTS-WITHOUT-NUMBER =
    { $count ->
        [one] PUBLICAÇÃO DE BOLETIM
       *[other] PUBLICAÇÕES DE BOLETIM
    }
July = Julho
June = Junho
Just-make-sure-the-organism-is-wild = Apenas se certifique de que o organismo é selvagem (não um animal de estimação, animal de zoológico ou planta de jardim)
Last-Active-date = Última vez ativo: { $date }
Lat-Lon = { NUMBER($latitude, maximumFractionDigits: 6) }, { NUMBER($longitude, maximumFractionDigits: 6) }
Lat-Lon-Acc = Lat: { NUMBER($latitude, maximumFractionDigits: 6) }, Lon: { NUMBER($longitude, maximumFractionDigits: 6) }, Prec: { $accuracy }
leading--identification = Liderando
Learn-from-people-who-verify-and-refine-your-identifications = Aprenda com pessoas que verificam e refinam suas identificações.
Learn-More = Saiba mais
LEARN-MORE-ABOUT-THIS-GROUP = SAIBA MAIS SOBRE ESTE GRUPO
LEARN-MORE-ABOUT-THIS-SPECIES = SAIBA MAIS SOBRE ESTA ESPÉCIE
Least-Observed = Least Observed
LEAVE = DEIXAR
LEAVE-PROJECT = DEIXAR PROJETO
LEAVE-PROJECT--question = DEIXAR PROJETO?
LEAVE-US-A-REVIEW = DEIXE UMA AVALIACAO!
Lets-reset-your-password = Vamos redefinir sua senha.
Loading-iNaturalists-AI-Camera = Carregando Câmera IA do iNaturalist
Loads-content-that-requires-an-Internet-connection = Carrega conteúdo que requer uma conexão com a internet
LOCATION = LOCALIZAÇÃO
Location = Localização
Location-accuracy-is-too-imprecise = A precisão da localização está muito baixa para auxiliar na identificação. Por favor, aumente o zoom.
LOCATION-TOO-IMPRECISE = LOCALIZAÇÃO MUITO IMPRECISA
LOG-IN = ENTRAR
LOG-IN-TO-INATURALIST = ENTRAR NO INATURALIST
Log-in-to-iNaturalist = Entrar no iNaturalist
LOG-OUT = SAIR
LOG-OUT--question = SAIR?
Lowest = Mais baixa
LOWEST-RANK = CLASSIFICAÇÃO MAIS BAIXA
MAP = MAPA
Map-Area = Área do mapa
March = Março
Match-Screen = Match Screen
maverick--identification = Em desacordo
May = Mai
MEDIA = MÍDIA
Media-Type = Tipo de media
MEMBERS-WITHOUT-NUMBER =
    { $count ->
        [one] MEMBRO
       *[other] MEMBROS
    }
Menu = Menu
Missing-Date = Data faltando
MISSING-EVIDENCE = EVIDÊNCIA AUSENTE
Monthly-Donor = Doador Mensal
Months = Meses
MONTHS = MESES
More = Mais
More-info = Mais informações
MOST-FAVED = MAIS FAVORITADOS
Most-faved = Mais favoritados
Most-Observed-Default = Most Observed (Default)
MY-CONTENT--notifications = MEU CONTEÚDO
My-Observations = Minhas Observações
My-Observations--bottom-tab = Minhas
Native = Nativa
Native-to-place = Nativo de { $place }
Navigates-to-AI-camera = Navegar para a Câmera IA
Navigates-to-bulk-importer = Navegar para o importador em massa
Navigates-to-camera = Navegar para a câmera
Navigates-to-explore = Navegue para o explorar
Navigates-to-log-in-screen = Navigates to log in screen
Navigates-to-main-menu = Navigates to main menu.
Navigates-to-match-screen = Navegar por coincidir com a tela
Navigates-to-notifications = Navegar para notificações
Navigates-to-observation-details = Navegar para a tela de detalhes da observação
Navigates-to-observation-edit-screen = Navegar para a tela de edição de observação
Navigates-to-photo-importer = Navegar para o importador de fotos
Navigates-to-previous-screen = Navegar para a tela anterior
Navigates-to-project-details = Navegar para os detalhes do projeto
Navigates-to-sound-recorder = Navegar para o gravador de som
Navigates-to-suggest-identification = Navegar para o sugestor de identificação
Navigates-to-taxon-details = Navegar para detalhes do táxon
Navigates-to-user-profile = Navegar para o perfil do usuário
Navigates-to-your-observations = Navegar para suas observações
NEARBY = NAS PROXIMIDADES
Nearby = Nas redondezas
Needs-ID--quality-grade = Precisa de Identificação
New-Observation = Nova observação
Newest-to-oldest = Do mais novo para o mais antigo
Next-observation = Próxima observação
Next-slide = Próximo
No-Camera-Available = Câmera indisponível
No-email-app-installed = Nenhum aplicativo de endereço eletrônico instalado
No-email-app-installed-body = Se você tiver outra forma de enviar endereço eletrônico, o endereço é { $address }
No-email-app-installed-body-check-other = Tente verificar seu endereço eletrônico em um navegador da rede ou em outro dispositivo.
No-Location = Sem localização
No-Media = Nenhuma mídia
No-model-found = Nenhum modelo encontrado
No-Notifications-Found = Você não tem notificações! Comece criando suas próprias observações.
No-projects-match-that-search = Nenhum projeto corresponde a esta pesquisa
No-results-found-for-that-search = Nenhum resultado encontrado para essa pesquisa.
No-results-found-try-different-search = Nenhum resultado encontrado. Tente uma pesquisa diferente ou ajuste seus filtros.
no-rights-reserved-cc0 = nenhum direito reservado (CC0)
none--accuracy = sem dado
NONE--ranks = sem dado
NOT-BY-ME = POR OUTROS
Not-enough-space-left-on-device = Sem espaço para armazenamento no seu dispositivo
Not-enough-space-left-on-device-try-again = Sem espaço de armazenamento no seu dispositivo para esta operação. Por favor, libere espaço e tente novamente.
NOTES = NOTAS
Notes = Anotações
NOTIFICATIONS = NOTIFICAÇÕES
Notifications--bottom-tab = Atividades
notifications-user-added-comment-to-observation-by-you = <0>{ $userName }</0> adicionou um comentário a uma observação sua
notifications-user-added-identification-to-observation-by-you = <0>{ $userName }</0> adicionou um comentário a uma observação sua
notifications-user1-added-comment-to-observation-by-user2 = <0>{ $user1 }</0> adicionou um comentário a uma observação de { $user2 }
notifications-user1-added-identification-to-observation-by-user2 = <0>{ $user1 }</0> adicionou uma identificação a uma observação de { $user2 }
November = Novembro
Obervations-must-be-manually-added = Observações devem ser adicionadas manualmente a um projeto tradicional, seja durante a fase de upload ou após a observação ter sido compartilhada com o iNaturalist. Um usuário também deve participar de um projeto tradicional para adicionar suas observações a ele.
Obscured = Oculta
Observation = Observação
Observation-Attribution = Observação: ©️ { $userName } · { $restrictions }
Observation-Copyright = Direitos de autor da observação: © { $userName } · { $restrictions }
Observation-has-no-photos-and-no-sounds = Esta observação não possui fotos ou sons.
Observation-location-obscured-randomized-point = A localização desta observação está oculta. Você está vendo um local aleatório no polígono de ocultação.
Observation-location-obscured-you-can-see-your-own = A localização desta observação está oculta. Você pode sempre ver a localização de suas próprias observações.
Observation-location-obscured-you-have-permission = A localização desta observação está oculta. Você tem permissão para ver esta localização.
Observation-options = Opções de observação
OBSERVATION-WAS-DELETED = OBSERVAÇÃO FOI EXCLUÍDA
Observation-with-no-evidence = Observação sem nenhuma evidência
Observations = Observações
Observations-need-location-date--warning = As observações do iNaturalist precisam de uma localização e de uma data para serem úteis aos cientistas. Por favor, verifique as observações com este ícone antes de fazer o upload.
Observations-View = Visualizar observações
OBSERVATIONS-WITHOUT-NUMBER =
    IMPORTAR { $count ->
        [uma] 1 OBSERVAÇÃO
       *[outra] { $count } OBSERVAÇÕES
    }
OBSERVE-ORGANISMS = OBSERVAR ORGANISMOS
OBSERVED-AT--label = OBSERVADO EM
OBSERVED-IN--label = OBSERVADO EM
Observers = Observadores
Observers-View = Visualizar observações
October = Outubro
Offline-DQA-description = O DQA pode não ser preciso. Verifique sua conexão com a rede e tente novamente.
Offline-suggestions-may-differ-from-online = Offline pode ser diferente de online porque os taxon images e common names se calhar não aparecem.
OK = Ok
Oldest-to-newest = Da mais antiga à mais recente
Once-you-create-and-upload-observations = Assim que você criar e enviar suas observações, outros membros da nossa comunidade podem adicionar identificações para ajudar suas observações a chegarem ao nível de pesquisa.
Open = Aberta
OPEN-EMAIL = ABRIR ENDEREÇO ELETRÔNICO
Open-menu = Abrir ementa
OPEN-SETTINGS = ABRIR AJUSTES
Opens-add-comment-form = Abre campo de comentário
Opens-AI-camera = Abre a câmera IA.
Opens-edit-comment-form = Abre formato de edição
Opens-location-permission-prompt = Abre pergunta de permissão de localização
OR-SIGN-IN-WITH = OU ENTRE COMO
Or-you-can-try-to-get-a-clearer-photo-by-zooming-in-getting-closer = Ou, você pode tentar obter uma foto melhor fazendo zoom, se aproximando ou tentando um ângulo diferente.
Organism-is-captive = O organismo é capturado
Organisms-that-are-identified-to-species = Organismos identificados na classificação de espécies ou abaixo
OTHER-DATA = OUTRAS INFORMAÇÕES
OTHER-SUGGESTIONS = OUTRAS SUGESTÕES
OTHERS--notifications = OUTROS
PASSWORD = SENHA
PEOPLE--title = PESSOAS
Photo-importer = Importador de fotos
PHOTO-LICENSING = LICENCIAMENTO DE FOTO
Photos = FOTOS
Photos-you-take-will-appear-here = As fotos que você tirar irão aparecer aqui
Please-allow-Camera-Access = Por favor, permita o acesso à câmera
Please-allow-Location-Access = Por favor, permita o acesso à localização
Please-allow-Microphone-Access = Por favor, permita o acesso ao microfone
Please-choose-a-different-password = Por favor escolha uma outra senha
Please-Grant-Permission = Por favor conceda permissão
PLEASE-LOG-IN = POR FAVOR ENTRE
Please-make-sure-your-password-is-at-least-6-characters = Por favor certifique-se de que sua senha tenha pelo menos 6 caracteres
Please-try-again-when-you-are-connected-to-the-internet = Por favor tente novamente quando estiver conectado à Internet
Please-try-again-when-you-are-online = Por favor tente novamente quando estiver online!
Point-the-camera-at-an-animal-plant-or-fungus = Aponte a câmera para um animal, planta ou fungo
POTENTIAL-DISAGREEMENT = POTENCIAL DESACORDO
Potential-disagreement-description = <0>A evidência é suficiente para confirmar que esta é </0><1></1><0>?<0>
Potential-disagreement-disagree = <0>Não, mas este é um membro de </0><1></1>
Potential-disagreement-unsure = <0>Eu não sei, mas tenho certeza que isto é </0><1></1>
Press-and-hold-to-view-more-options = Pressione e segure para ver mais opções
Previous-observation = Observação anterior
Previous-slide = Anterior
Privacy-Policy = Política de Privacidade
PRIVACY-POLICY = POLÍTICA DE PRIVACIDADE
Private = Privado
PROJECT = PROJETO
Project-Members-Only = Apenas membros do projeto
PROJECT-REQUIREMENTS = REQUISITOS DO PROJETO
project-start-time-datetime = Horário de início: { $datetime }
PROJECTS = PROJETOS
Projects = Projetos
PROJECTS-X = PROJETOS ({ $projectCount })
Pull-to-refresh-and-sync-observations = Deslize para atualizar e sincronizar observações
Pull-to-refresh-notifications = Puxe para atualizar as notificações
QUALITY-GRADE = GRAU DE QUALIDADE
Quality-Grade = Grau de Qualidade
Quality-Grade-Casual--label = Nível de qualidade: Casual
Quality-Grade-Needs-ID--label = Nível de qualidade: Precisa de identificação
Quality-Grade-Research--label = Nível de qualidade: Pesquisa
Ranks-CLASS = CLASSE
Ranks-Class = Classe
Ranks-COMPLEX = COMPLEXO
Ranks-Complex = Complexo
Ranks-EPIFAMILY = EPIFAMÍLIA
Ranks-Epifamily = Epifamília
Ranks-FAMILY = FAMÍLIA
Ranks-Family = Família
Ranks-FORM = FORMULÁRIO
Ranks-Form = Forma
Ranks-GENUS = GÊNERO
Ranks-Genus = Gênero
Ranks-GENUSHYBRID = GENÊRO HÍBRIDO
Ranks-Genushybrid = Gênero híbrido
Ranks-HYBRID = HÍBRIDO
Ranks-Hybrid = Híbrido
Ranks-INFRACLASS = INFRACLASSE
Ranks-Infraclass = Infraclasse
Ranks-INFRAHYBRID = INFRAHIBRIDO
Ranks-Infrahybrid = Infra-híbrido
Ranks-INFRAORDER = INFRAORDEM
Ranks-Infraorder = Infraordem
Ranks-KINGDOM = REINO
Ranks-Kingdom = Reino
Ranks-ORDER = ORDEM
Ranks-Order = Ordem
Ranks-PARVORDER = PARVORDEM
Ranks-Parvorder = Parvordem
Ranks-PHYLUM = FILO
Ranks-Phylum = Filo
Ranks-SECTION = SEÇÃO
Ranks-Section = Seção
Ranks-SPECIES = ESPÉCIES
Ranks-Species = Espécie
Ranks-Statefmatter = Estado da matéria
Ranks-STATEOFMATTER = ESTADO DA MATÉRIA
Ranks-SUBCLASS = SUB-CLASSE
Ranks-Subclass = Subclasse
Ranks-SUBFAMILY = SUB FAMÍLIA
Ranks-Subfamily = Subfamília
Ranks-SUBGENUS = SUB-GÊNERO
Ranks-Subgenus = Subgênero
Ranks-Subkingdom = Subreino
Ranks-SUBORDER = SUB-ORDEM
Ranks-Suborder = Subordem
Ranks-SUBPHYLUM = SUBPHYLUM
Ranks-Subphylum = Subfilo
Ranks-SUBSECTION = SUB-SEÇÃO
Ranks-Subsection = Subseção
Ranks-SUBSPECIES = SUB-ESPÉCIE
Ranks-Subspecies = Subespécie
Ranks-SUBTERCLASS = SUBTERCLASSE
Ranks-Subterclass = Subterclasse
Ranks-SUBTRIBE = SUBTRIBO
Ranks-Subtribe = Subtribo
Ranks-SUPERCLASS = SUPERCLASSE
Ranks-Superclass = Superclasse
Ranks-SUPERFAMILY = SUPERFAMÍLIA
Ranks-Superfamily = Superfamília
Ranks-SUPERORDER = SUPERORDEM
Ranks-Superorder = Superordem
Ranks-SUPERTRIBE = SUPERTRIBO
Ranks-Supertribe = Supertribo
Ranks-TRIBE = TRIBO
Ranks-Tribe = Tribo
Ranks-VARIETY = VARIEDADE
Ranks-Variety = Variedade
Ranks-ZOOSECTION = ZOOSEÇÃO
Ranks-Zoosection = Seção
Ranks-ZOOSUBSECTION = ZOOSUBSEÇÃO
Ranks-Zoosubsection = Subseção
Read-more-on-Wikipedia = Leia mais na Wikipédia
Record-a-sound = Gravar um som
Record-animal-sounds = Gravar sons de animais
RECORD-NEW-SOUND = REGISTRAR NOVO SOM
RECORD-SOUND = GRAVAR SOM
Record-verb = Registro
Recording-sound = Gravando som
Recording-stopped-Tap-to-play-the-current-recording = Recording stopped. Tap to play the current recording.
REDO-SEARCH-IN-MAP-AREA = REFAZER PESQUISA NO ÁREA DO MAPA
Remove-agreement = Remover contrato
Remove-disagreement = Remover distrato
Remove-favorite = Remover favorito
Remove-identification = Remover identificação
Remove-Photos = Remover fotos
Remove-project-filter = Remover filtro de projeto
Remove-taxon-filter = Alterar filtro de táxon
Remove-user-filter = Remover filtro do observador
Removes-this-observations-taxon = Remove estas observações do táxon
Removes-your-vote-of-agreement = Remove seu voto de concordância
Removes-your-vote-of-disagreement = Remove seu voto de discordância
Research-Grade--quality-grade = Nível de Pesquisa
RESEARCH-GRADE--quality-grade = GRAU DE PESQUISA
Research-Grade-Status = Nível de pesquisa
RESET-PASSWORD = REDEFINIR SENHA
RESET-RECORDING = REDEFINIR REGISTROS
RESET-SEARCH = REDEFINIR PESQUISA
RESET-SOUND-header = REDEFINIR SOM?
Reset-verb = Reset
RESTART-APP = REINICIAR APLICATIVO
Restore = Restaurar
Reveal = Revelar
REVIEW-INATURALIST = AVALIAR INATURALISTA
REVIEWED = AVALIADO
Reviewed-observations-only = Apenas observações revisadas
Satellite--map-type = Satélite
SAVE = SALVAR
SAVE-ALL = SALVAR TUDO
Save-all-observations = Salvar todas as observações
SAVE-CHANGES = SALVAR ALTERAÇÕES
SAVE-FOR-LATER = SALVAR PARA MAIS TARDE
SAVE-LOCATION = SALVAR LOCALIZAÇÃO
SAVE-PHOTOS = SALVAR FOTOS
Save-photos-to-your-library = Salvar fotos na sua galeria
Saved-Observation = Observação salva, na fila para carregar
Scientific-Name = Nome Científico
Scientific-Name-Common-Name = Nome Científico (Nome Comum)
SEARCH = PESQUISAR
Search = Pesquisar
Search-for-a-project = Pesquisar um projeto
SEARCH-FOR-A-TAXON = PESQUISAR UM TÁXON
Search-for-a-taxon = Buscar uma taxa
SEARCH-LOCATION = PESQUISAR LOCALIZAÇÃO
SEARCH-PROJECTS = PESQUISAR PROJETOS
Search-suggestions-with-location = Pesquisar sugestões com localização
Search-suggestions-without-location = Pesquisar sugestões sem localização
SEARCH-TAXA = BUSCAR TAXA
SEARCH-USERS = PROCURAR USUÁRIOS
See-observations-by-this-user-in-Explore = Ver observações deste usuário em Explorar
See-observations-of-this-taxon-in-explore = Ver observações deste táxon em explorar
See-project-members = Ver membros do projeto
See-species-observed-by-this-user-in-Explore = Ver espécies observadas por este usuário em Explorar
Select-a-date-and-time-for-observation = Selecione uma data e hora para a observação
Select-captive-or-cultivated-status = Selecione o status cativo ou cultivado
Select-geoprivacy-status = Selecione o status de geoprivacidade
Select-or-drag-media = Selecionar ou arrastar mídias
Select-photo = Selecionar foto
SELECT-THIS-TAXON = SELECIONAR ESTE TÁXON
Select-user = Selecionar usuário
Selects-iconic-taxon-X-for-identification = Seleciona táxon icônico { $iconicTaxon } para identificação.
Separate-Photos = Fotos Separadas
September = Setembro
SETTINGS = CONFIGURAÇÕES
Share = Compartilhar
SHARE-DEBUG-LOGS = COMPARTILHAR REGISTROS DE DEPURAÇÃO
Share-location = Compartilhar localização
Share-map = Compartilhar mapa
Share-your-observation-where-it-can-help-scientists = Compartilhe a sua observação, onde ela pode ajudar os cientistas de todo o mundo a compreenderem melhor a biodiversidade.
SHOP-INATURALIST-MERCH = COMPRAR MERCADORIA INATURALISTA
Show-observation-options = Mostrar opções de observação.
Showing-offline-search-results--taxa = Mostrando resultados de pequisa sem conexão. Para pesquisar mais espécies, tente novamente quando conectado à internet.
Shows-identification-suggestions = Mostrar sugestões de identificação
Shows-observation-creation-options = Mostrar opções de criação de observação
Sign-in-with-Apple = Entrar com Apple
Sign-in-with-Apple-Failed = Falha ao entrar com Apple
Sign-in-with-Google = Entrar com o Google
Sign-in-with-Google-Failed = Falha ao entrar com o Google
Skip-additional-suggestions = Pular sugestões adicionais
Skip-for-now = Ignorar por enquanto
Something-went-wrong = Houve algum problema.
Sorry-this-observation-was-deleted = Desculpe, esta observação foi apagada
Sorry-we-dont-know-how-to-open-that-URL = Desculpe, não sabemos como abrir a URL: { $url }
SORT-BY = ORDENAR POR
Sort-by = Ordenar por
SORT-SPECIES = SORT SPECIES
sound-playback-separator = /
Sound-recorder = Gravador de som
sound-recorder-help-A-recording-of = Uma gravação de 5-15 segundos é a melhor opção para ajudar com identificadores.
sound-recorder-help-Get-as-close-as-you-can = Chegue o mais próximo que puder com segurança para gravar o organismo.
sound-recorder-help-Get-closer = Aproxime-se
sound-recorder-help-Keep-it-short = Seja breve
sound-recorder-help-Make-sure = Certifique-se de que o som do seu próprio movimento não cubra o som do organismo.
sound-recorder-help-One-organism = Um organismo
sound-recorder-help-Stop-moving = Parar de se mover
sound-recorder-help-Try-to-isolate = Tente isolar o som de um único organismo. Se não conseguir, certifique-se de deixar uma nota de qual organismo você está gravando.
Sounds = Sons
Source-List = <0>(Lista de fonte(s): </0><1>{ $source }</1><0>)</0>
Species = Espécie
Species-View = Visualização de espécies
Species-with-the-least-observations-appear-first = Species with the least observations appear first
Species-with-the-most-observations-appear-first = Species with the most observations appear first
SPECIES-WITHOUT-NUMBER =
    { $count ->
        [one] ESPÉCIE
       *[other] ESPÉCIES
    }
Standard--map-type = Padrão
Start-must-be-before-end = A data de início deve ser anterior à data de término.
Start-upload = Iniciar upload
Starts-recording-sound = Iniciar gravação de som
Stay-on-this-screen = Fique nesta tela enquanto sua localização carrega.
Still-need-help = Ainda precisa de ajuda? Você pode registrar uma solicitação de suporte aqui.
Stop-upload = Parar o carregamento
Stop-verb = Cancelar
Stops-recording-sound = Interrompe o som de gravação
SUBMIT = ENVIAR
SUBMIT-ID-SUGGESTION = ENVIAR SUGESTÃO DE IDENTIFICAÇÃO
SUGGEST-ID = IDENTIFICAÇÃO SUGERIDA
supporting--identification = Concordante
Switches-to-tab = Alterna para a guia { $tab }
Sync-observations = Sincronizar observações
Syncing = Sincronizando...
Take-photo = Tirar foto
Take-photos = Take photos
Taxa = Táxons
TAXON = TÁXON
TAXON-NAMES-DISPLAY = EXIBIR NOMES DOS TÁXON
TAXONOMIC-RANKS = CLASSIFICAÇÕES TAXONÔMICAS
TAXONOMY-header = TAXONOMIA
TEAM = GRUPO
Terms-of-Use = Termos de Utilização
TERMS-OF-USE = TERMOS DE USO
Thank-you-for-sharing-your-feedback = Obrigado por compartilhar seus comentários e nos ajudar a melhorar!
Thanks-for-using-any-suggestions = Obrigado por usar este aplicativo! Você tem alguma sugestão para as pessoas que o desenvolveram?
That-email-is-already-associated-with-an-account = Este e-mail já está associado a uma conta.
That-user-profile-doesnt-exist = Este perfil de usuário não existe
That-username-is-unavailable = Este nome de usuário não está disponível
The-AI-is-not-confident-It-may-be-one-of-the-IDs-below = A IA não está segura, pode ser uma das IDs abaixo
The-AI-is-not-confident-Upload-to-ask-the-community = A IA não está segura. Fazer upload para consultar a comunidade.
The-exact-location-will-be-hidden = A localização exata será ocultada publicamente, e em vez disso será generalizada para uma área maior. (Espécies ameaçadas e em perigo de extinção são automaticamente ocultadas).
The-iNaturalist-community-will-help-verify-and-refine-identifications = A comunidade iNaturalist ajudará a verificar e refinar as identificações das suas observações para criar dados de grau de pesquisa para ciência e conservação.
The-iNaturalist-Network = A rede inaturalista é uma coleção de sites localizados que estão totalmente conectados à comunidade global da inaturalista. Os sites da rede são apoiados por instituições locais que promovem o uso local e facilitam a utilização dos dados da inaturalista para beneficiar a biodiversidade local.
The-location-will-not-be-visible-to-others = A localização não será visível para outras pessoas, o que pode tornar a identificação da observação impossível
The-models-that-suggest-species = Os modelos que sugerem espécies com base na semelhança visual e localização são em parte graças às colaborações com Sara Beery, Tom Brooks, Elijah Cole, Christian Lange, Oisin Mac Aodha, Pietro Perona e Grant Van Horn.
There-was-an-error-that-might-be-fixed-by-logging-in-again = Ocorreu um erro que pode ser corrigido fazendo login novamente.
This-is-a-wild-organism = Este é um organismo selvagem e não foi colocado nesse local por seres humanos.
This-is-how-taxon-names-will-be-displayed = É assim que todos os nomes de táxon serão exibidos para você ao longo do inaturalista.
This-is-your-identification-other-people-may-help-confirm-it = Esta é a sua identificação. Outras pessoas podem ajudar a confirmar!
This-may-take-a-few-seconds = Isso pode levar alguns segundos.
This-observation-has-no-comments-or-identifications-yet = Esta observação ainda não tem comentários ou identificações.
This-observation-has-not-met-the-conditions-required-to-meet-Research-Grade = Esta observação não atingiu as condições necessárias para atender ao status de Nível de Pesquisa
This-observation-is-not-eligible-for-research-grade-status = Esta observação não tem os requisitos para atingir o nível de pesquisa. Saiba mais na Avaliação de Qualidade de Dados abaixo.
This-observation-is-research-grade-and-can-be-used-by-scientists = Esta observação tem nível de pesquisa e pode ser usada por cientistas!
This-observation-needs-more-identifications = Esta observação precisa de mais identificações para alcançar o status de Nível de Pesquisa
This-observation-needs-more-identifications-to-become-research-grade = Esta observação necessita de mais identificações para alcançar o nível de pesquisa
This-observer-has-opted-out-of-the-Community-Taxon = Este observador optou por não participar da Comunidade do Táxon
This-organism-was-placed-by-humans = Este organismo foi colocado neste local pelos seres humanos. Isto se aplica a outras situações, plantas de jardim, animais de estimação e de zoológico.
This-user-has-no-followers = This user has no followers.
This-user-has-not-joined-any-projects = This user has not joined any projects.
This-user-is-not-following-anyone = This user is not following anyone.
To-sync-your-observations-to-iNaturalist = Para sincronizar suas observações com o inaturalista, por favor acesse.
To-view-nearby-organisms-please-enable-location = Para ver organismos próximos, por favor ative a localização.
To-view-nearby-projects-please-enable-location = Para ver projetos próximos, por favor ative a localização.
Toggle-map-type = Alternar categoria de mapa
TOP-ID-SUGGESTION = SUGESTÃO DE IDENTIFICAÇÃO SUPERIOR
Traditional-Project = Projeto Tradicional
Umbrella-Project = Projeto Guarda-chuva
UNFOLLOW = DEIXAR DE SEGUIR
UNFOLLOW-USER = DEIXAR DE SEGUIR USUÁRIO?
Unknown--rank = Desconhecido
Unknown--taxon = Desconhecido
Unknown--user = Desconhecido
Unknown-error = Erro desconhecido
Unknown-organism = Organismo desconhecido
Unreviewed-observations-only = Apenas observações não revisadas
Upload-Complete = Envio concluído
Upload-in-progress = Envio em progresso
UPLOAD-NOW = ENVIAR AGORA
Upload-photos = Upload photos
Upload-Progress = Taxa de envio { $uploadProgress } completa
UPLOAD-TO-INATURALIST = ENVIAR PARA INATURALISTA
Upload-x-observations =
    Envie { $count ->
        [uma] 1 observação
       *[outras] { $count } observações
    }
Upload-your-observations-to-contribute-data-to-help-save-species = Carregue suas observações para contribuir com dados para ajudar a salvar as espécies.
Uploaded-via-application = Enviado via: { $application }
Uploading-x-of-y = Enviando { $currentUploadCount } de { $total }
Uploading-x-of-y-observations =
    { $total ->
        [uma] Enviando { $currentUploadCount } observation
       *[outra] Enviando { $currentUploadCount } de { $total } observações
    }
Use-iNaturalist-to-identify-any-living-thing = Use o iNaturalist para identificar qualquer coisa viva
USE-LOCATION = USAR LOCALIZAÇÃO
Use-the-devices-other-camera = Use a outra câmera do dispositivo.
Use-the-iNaturalist-camera-to-see-real-time-identifications-and-take-photos = Use a camêra do iNaturalist para ver identificações em tempo real e fazer fotos!
Use-your-devices-microphone-to-record-animal-sounds-and-share-them = Use o microfone do seu dispositivo para gravar sons feitos por organismos e compartilhá-los com nossa comunidade para obter identificações e contribuir para a ciência!
USER = USUÁRIO
User = Usuário { $userHandle }
USERNAME-OR-EMAIL = USUÁRIO OU EMAIL
Users = Usuários
Using-location = Usando a localização
Verified-IDs-are-used-for-science-and-conservation = IDs verificadas são utilizadas pela ciência e para conservação
Version-app-build = Versão { $appVersion } ({ $buildVersion })
VIEW-ALL-X-PLACES = VISUALIZAR TODOS OS { $count } LOCAIS
VIEW-ALL-X-PROJECTS = VISUALIZAR TODOS OS { $count } PROJETOS
VIEW-ALL-X-TAXA = VISUALIZAR TODOS OS { $count } TAXA
VIEW-ALL-X-USERS = VISUALIZAR TODOS OS { $count } USUÁRIOS
VIEW-CHILDREN-TAXA = VISUALIZAR TAXA INFANTIL
VIEW-DATA-QUALITY-ASSESSMENT = VISUALIZAR AVALIAÇÃO DA QUALIDADE DE DADOS
VIEW-EDUCATORS-GUIDE = VISUALIZAR GUIA DE EDUCADOR
VIEW-FOLLOWERS = VISUALIZAR SEGUIDORES
VIEW-FOLLOWING = VER SEGUINDO
View-in-browser = Ver no navegador
VIEW-IN-EXPLORE = VER NO EXPLORAR
VIEW-INATURALIST-HELP = VER AJUDA DO INATURALIST
View-photo = Ver foto
View-photo-licensing-info = Ver informações sobre licenciamento de fotos
VIEW-PROJECT-REQUIREMENTS = VER REQUISITOS DO PROJETO
VIEW-PROJECTS = VER PROJETOS
View-suggestions = Ver sugestões
Watch-your-notifications-for-identifications = Acompanhe as suas notificações para identificações!
We-are-not-confident-enough-to-make-a-top-ID-suggestion = Não temos confiança suficiente para sugerir uma identificação precisa, mas aqui estão algumas outras sugestões:
Welcome-back = Bem vindo de volta!
WHAT-IS-INATURALIST = O QUE É INATURALIST?
Whats-more-by-recording = Além disso, ao gravar e compartilhar suas observações, você criará dados de qualidade de pesquisa para cientistas que trabalham para melhor entender e proteger a natureza. Portanto, se você gosta de registrar suas descobertas ao ar livre ou se simplesmente gosta de aprender sobre a vida, junte-se a nós!
When-tapping-the-green-observation-button = Quando clicar o botão de observação verde, abra:
WIKIPEDIA = WIKIPEDIA
Wild = Selvagem
WILD-STATUS = ESTADO SILVESTRE
Withdraw = Retirar
WITHDRAW-ID = REMOVER IDENTIFICAÇÃO
WITHDRAW-ID-QUESTION = REMOVER IDENTIFICAÇÃO?
Withdraws-identification = Remove a identificação
Worldwide = Global
WORLDWIDE = GLOBAL
Would-you-like-to-discard-your-current-recording-and-start-over = Você gostaria de descartar o registro atual e recomeçar?
Would-you-like-to-suggest-the-following-identification = Você gostaria de sugerir a seguinte identificação?
x-comments =
    { $count ->
        [one] { $count } comentário
       *[other] { $count } comentários
    }
x-failed =
    { $count ->
        [one] { $count } falhou
       *[other] { $count } falharam
    }
X-FOLLOWERS =
    { $count ->
        [one] { $count } SEGUIDOR
       *[other] { $count } SEGUIDORES
    }
X-Identifications =
    { $count ->
        [one] { $count } Identificação
       *[other] { $count } Identificações
    }
x-identifications =
    { $count ->
        [one] { $count } identificação
       *[other] { $count } identificações
    }
X-Identifiers =
    { $count ->
        [one] { $count } Identificador
       *[other] { $count } Identificadores
    }
X-MEMBERS =
    { $count ->
        [one] { $count } MEMBRO
       *[other] { $count } MEMBROS
    }
X-Observations =
    { $count ->
        [one] 1 Observação
       *[other] { $count } Observações
    }
X-OBSERVATIONS--below-number =
    { $count ->
        [one] OBSERVAÇÃO
       *[other] OBSERVAÇÕES
    }
X-observations-deleted =
    { $count ->
        [one] 1 observação excluída
       *[other] { $count } observações excluídas
    }
X-observations-uploaded =
    { $count ->
        [one] 1 observação enviada
       *[other] { $count } observações enviadas
    }
X-Observers =
    { $count ->
        [one] { $count } Observador
       *[other] { $count } Observadores
    }
X-of-Y =
    { $x ->
        [one] 1
       *[other] { $x }
    } { $y ->
        [one] de { $y }
       *[other] de { $y }
    }
X-percent = { $count }%
X-percent-confidence = { $count }% de confiança
X-PHOTOS =
    { $photoCount ->
        [one] 1 FOTO
       *[other] { $photoCount } FOTOS
    }
X-PHOTOS-X-OBSERVATIONS =
    { $photoCount ->
        [one] 1 FOTO
       *[other] { $photoCount } FOTOS
    }, { $observationCount ->
        [one] 1 OBSERVAÇÃO
       *[other] { $observationCount } OBSERVAÇÕES
    }
X-PHOTOS-Y-SOUNDS =
    { $photoCount ->
        [one] 1 FOTO
       *[other] { $photoCount } FOTOS
    }, { $soundCount ->
        [one] 1 SOM
       *[other] { $soundCount } SONS
    }
X-PROJECTS = { $projectCount } PROJETOS
x-saved =
    { $count ->
        [one] { $count } salva
       *[other] { $count } salvas
    }
X-SOUNDS =
    { $count ->
        [one] 1 SOM
       *[other] { $count } SONS
    }
X-Species =
    { $count ->
        [one] { $count } Espécie
       *[other] { $count } Espécies
    }
X-SPECIES--below-number =
    { $count ->
        [one] ESPÉCIE
       *[other] ESPÉCIES
    }
x-uploaded =
    { $count ->
        [one] { $count } enviada
       *[other] { $count } enviadas
    }
x-uploading =
    { $count ->
        [one] { $count } enviando
       *[other] { $count } enviados
    }
x-uploads-failed =
    { $count ->
        [one] { $count } upload falhou
       *[other] { $count } uploads falharam
    }
You-are-offline = Você está offline
You-are-offline-Tap-to-reload = Você está offline. Toque para recarregar.
You-are-offline-Tap-to-try-again = Você está offline. Toque para tentar novamente.
You-can-add-up-to-20-media = Você pode adicionar até 20 fotos e 20 sons por observação.
You-can-also-check-out-merchandise = Você também pode conferir os produtos da iNaturalist e procurar em nossa loja abaixo!
You-can-click-join-on-the-project-page = Você pode clicar em "juntar-se" na página do projeto.
You-can-find-answers-on-our-help-page = Você pode encontrar respostas na nossa página de ajuda.
You-can-now-upload-your-observations-to-iNaturalist-and-contribute = Agora você pode enviar suas observações para o iNaturalist e contribuir para a pesquisa sobre a biodiversidade global.
You-can-only-add-20-photos-per-observation = Você só pode adicionar 20 fotos por observação
You-can-still-share-the-file = Você ainda pode compartilhar o arquivo com outro aplicativo. Se você puder enviá-lo por correio eletrônico, envie-o para { $email }
You-can-upload-this-observation-to-our-community = Você pode enviar esta observação à nossa comunidade para obter uma identificação de uma pessoa real, e ajudar nossa IA a melhorar suas identificações no futuro
You-changed-filters-will-be-discarded = Você alterou os filtros, mas eles não foram aplicados aos resultados da pesquisa de exploração.
You-have-opted-out-of-the-Community-Taxon = Você optou por sair da Comunidade do Táxon
You-havent-joined-any-projects-yet = Você ainda não se juntou a nenhum projeto!
You-havent-observed-any-species-yet = Você ainda não observou nenhuma espécie.
You-likely-observed-a-species-in-this-group = Você provavelmente observou uma espécie nesse grupo
You-likely-observed-this-species = Você provavelmente observou esta espécie
You-may-have-observed-a-species-in-this-group = Você pode ter observado uma espécie neste grupo
You-may-have-observed-this-species = Você pode ter observado esta espécie
You-may-notice-changes-to-how-things-look-and-flow = Você pode perceber alterações sobre a aparência e o fluxo das coisas. Controle suas opções nas configurações.
You-must-install-Google-Play-Services-to-sign-in-with-Google = Você deve instalar o Google Play Services para fazer login com o Google.
You-need-an-Internet-connection-to-do-that = Você precisa de uma conexão com a ‘internet’ para fazer isso.
You-need-log-in-to-do-that = Você precisa fazer login para fazer isso.
You-observed-a-species-in-this-group = Você observou uma espécie nesse grupo
You-observed-this-species = Você observou esta espécie
You-will-see-notifications = Você verá notificações aqui quando entrar e carregar observações.
Your-donation-to-iNaturalist = A sua doação para o iNaturalist apoia a melhoria e a estabilidade dos aplicativos móveis e sites que conectam milhões de pessoas à natureza, e permitem a protecção da biodiversidade em todo o mundo!
Your-email-is-confirmed = Seu endereço eletrônico foi confirmado! Por favor, entre para continuar.
Your-location-uncertainty-is-over-x-km = Sua incerteza de localização é superior a { $x } km, muito alta para ser útil aos identificadores. Edite a localização e amplie até que o círculo de precisão fique verde e centralizado no local onde você observou o organismo.
Your-observations-can-help-science = Suas observações podem ajudar a ciência!
Youre-ready-to-share-your-observations = Você está pronto para compartilhar suas observações!
Youve-denied-permission-prompt = Você negou a permissão. Por favor, conceda permissão nas configurações do aplicativo.
Youve-previously-denied-camera-permissions = Você negou as permissões da câmera anteriormente, por favor, ative-as nas configurações.
Youve-previously-denied-location-permissions = Você negou as permissões de localização anteriormente, por favor habilite-as nas configurações.
Youve-previously-denied-microphone-permissions = Você negou as permissões de microfone anteriormente, por favor, habilite-as nas configurações.
Zoom-in-as-much-as-possible-to-improve = Amplie o máximo possível para melhorar a precisão da localização e obter melhores identificações.
Zoom-to-current-location = Zoom para a localização atual
zoom-x = { $zoom }×
