### DO NOT EDIT THIS FILE!
###
### This file came from Crowdin and was normalized by ftl.js.
### It will be overwritten during the next translation sync. To add
### translations, go to https://crowdin.com/editor/inaturalistios/724
###

ABOUT = О
ACCOUNT-SETTINGS = НАСТРОЙКИ АККАУНТА
Agree = Согласен
AGREE = СОГЛАСЕН
ALL = ВСЕ
All = Все
All-observations = Все наблюдения
all-rights-reserved = Все права защищены
All-taxa = Все таксоны
April = Апрель
August = Август
Camera = Камера
Cancel = Отмена
Casual--quality-grade = Случайный
Clear = Очистить
Close = Закрыть
Collection-Project = Коллекционный проект
Community-Guidelines = Правила сообщества
Coordinates-copied-to-clipboard = Координаты скопированы в буфер обмена
Data-quality-assessment-date-is-accurate = Дата является точной
Data-quality-assessment-date-specified = Указана дата
Data-quality-assessment-evidence-of-organism = Свидетельство существования организма
Data-quality-assessment-has-photos-or-sounds = С фото или со звуком
Data-quality-assessment-id-supported-by-two-or-more = Поддержка идентификации двумя или более участниками
Data-quality-assessment-location-is-accurate = Местоположение является точным
Data-quality-assessment-location-specified = Указано местоположение
Data-quality-assessment-organism-is-wild = Организм является диким
Data-quality-assessment-recent-evidence-of-organism = Свежие свидетельства существования организма
Data-quality-assessment-single-subject = Свидетельство, связанное с отдельным объектом
Data-quality-assessment-title-research = Это наблюдение достигло исследовательского уровня!
Date = Дата
date-format-month-day = d MMM
Date-observed = Дата наблюдения
Date-observed-header-short = Дата, время наблюдения
Date-Range = Диапазон дат
date-to-date = { $d1 } - { $d2 }
December = Декабрь
Delete-observation = Удалить наблюдения
Delete-photo = Удалить фото
Device-storage-full = Память вашего устройства хранения  заполнена
Device-storage-full-description = iNaturalist не может более сохранять ваши фото, может произойти сбой.
DONATE = Поддержать
Edit = Редактировать
Edit-location = Изменить местоположение
Edit-Observation = Редактировать наблюдение
Edit-your-profile-change-your-settings = Настройте ваш профиль, поменяйте при необходимости настройки уведомлений и управляйте другими  настройками вашего аккаунта
Endemic = Эндемичный
Error = Ошибка
Error-title = Ошибка
Establishment = Возникновение
Exact-Date = Точная дата
except = за исключением
Explore = Поиск
FEATURED = РЕКОМЕНДУЕМЫЕ
February = Февраль
Filter = Фильтр
Filters = Фильтры
Flag-An-Item = Отметить пункт
Flag-Item-Other-Description = Некоторые другие причины вы можете изложить ниже.
Flag-Item-Other-Input-Hint = Укажите причину, по которой вы помечаете этот элемент
Flagged = Помечено
FOLLOWING-X-PEOPLE =
    { $count ->
        [one] НА ВАС ПОДПИСАН { $count } ЧЕЛОВЕК
       *[other] НА ВАС ПОДПИСАНО { $count } ЧЕЛОВЕК
    }
Go-back = Назад
Hide = Скрыть
ID-Withdrawn = Отзыв идентификации
Identifiers = Эксперты
If-you-leave-x-of-your-observations-removed =
    Если вы покинете этот традиционный проект, { $count ->
        [one] 1 ваше наблюдение
       *[other] { $count } ваших наблюдений
    } также будут удалены из проекта.
improving--identification = Улучшающая
Introduced = Интродуцент
January = Январь
JOIN = ПРИСОЕДИНИТЬСЯ
JOIN-PROJECT--question = ПРИСОЕДИНИТЬСЯ К ПРОЕКТУ?
JOINED = ПРИСОЕДИНИЛИСЬ К
JOINED-X-PROJECTS =
    { $count ->
        [one] ПРИСОЕДИНИЛСЯ К ОДНОМУ { $count } ПРОЕКТУ
       *[other] ПРИСОЕДИНИЛСЯ К { $count } ПРОЕКТАМ
    }
July = Июль
June = Июнь
leading--identification = Ведущая
Learn-More = Узнать больше
LEAVE-PROJECT--question = ВЫЙТИ ИЗ ПРОЕКТА?
Location = Местоположение
Log-in = Вход
LOG-OUT = ВЫЙТИ
Map-Area = Карта области
March = Март
maverick--identification = Независимое мнение
May = Май
Media-Type = Тип медиафайла
Menu = Меню
Missing-Date = Отсутствует дата
Months = Месяцы
MY-OBSERVATIONS = МОИ НАБЛЮДЕНИЯ
Native = Естественный
NEARBY = ПОБЛИЗОСТИ
Nearby = Около
Needs-ID--quality-grade = Требуется идентификация
New-Observation = Новые наблюдения
No-Location = Местоположение не указано
No-Media = Нет медиа
Not-enough-space-left-on-device = На устройстве недостаточно места
Not-enough-space-left-on-device-try-again = Для данной операции на устройстве не хватает места. Пожалуйста, освободите место и попробуйте ещё раз
Notifications = Уведомления
November = Ноябрь
Obscured = Скрытое
Observation = Наблюдение
Observations = Наблюдения
Observe = Наблюдать
Observers = Наблюдатели
October = Октябрь
Offensive-Inappropriate = Оскорбительное / Неприемлемое
OK = ОК
Open = Открытое
Other = Другое
PEOPLE--title = ЛЮДИ
Privacy-Policy = Политика конфиденциальности
Private = Частный
Project-Members-Only = Только участники проекта
project-start-time-datetime = Время начала: { $datetime }
Projects = Проекты
PROJECTS-X = ПРОЕКТЫ ({ $projectCount })
Quality-Grade = Уровень наблюдения
Quality-Grade-Casual--label = Уровень качества: Обыкновенный
Quality-Grade-Needs-ID--label = Уровень качества: Требует идентификации
Quality-Grade-Research--label = Уровень качества: Исследовательский
Ranks-Class = Класс
Ranks-Complex = Комплекс
Ranks-Epifamily = Эписемейство
Ranks-Family = Семейство
Ranks-Form = Форма
Ranks-Genus = Род
Ranks-Genushybrid = Genus hybrid (GeoPlanet)
Ranks-Hybrid = Гибрид
Ranks-Infraclass = Инфракласс
Ranks-Infrahybrid = Инфрагибрид
Ranks-Infraorder = Инфраотряд
Ranks-Kingdom = Царство
Ranks-Order = Отряд / порядок
Ranks-Parvorder = Парвотряд
Ranks-Phylum = Тип / отдел
Ranks-Section = Секция
Ranks-SPECIES = ВИДЫ
Ranks-Species = Видов
Ranks-Statefmatter = Форма
Ranks-Subclass = Подкласс
Ranks-Subfamily = Подсемейство
Ranks-Subgenus = Подрод
Ranks-Subkingdom = Подцарство
Ranks-Suborder = Подотряд
Ranks-Subphylum = Подтип / подотдел
Ranks-Subsection = Подсекция
Ranks-Subspecies = Подвид
Ranks-Subterclass = Надкласс
Ranks-Subtribe = Подтриба
Ranks-Superclass = Надкласс
Ranks-Superfamily = Надсемейство
Ranks-Superorder = Надотряд
Ranks-Supertribe = Надтриба
Ranks-Tribe = Триба
Ranks-Variety = Разновидность
Ranks-Zoosection = Зоосекция
Ranks-Zoosubsection = Зооподсекция
Record-a-sound = Запишите аудио
Record-verb = Запись
Remove-identification = Удалить идентификацию
Remove-project-filter = Удалить фильтр по проекту
Research-Grade--quality-grade = Исследовательский статус
Reset-verb = Сброс
Restore = Восстановить
Satellite--map-type = Спутник
SAVE = СОХРАНИТЬ
Save = Сохранить
Scientific-Name = Научное название
Search = Поиск
See-project-members = Посмотреть список участников проекта
September = Сентябрь
Share = Поделиться
Share-location = Поделиться местоположением
Sounds = Звуки
Spam = Спам
Spam-Examples = Коммерческие предложения, ссылки в никуда и т. д.
Species = Видов
Standard--map-type = Стандартный
Stop-verb = Остановить
supporting--identification = Поддерживающая
Syncing = Синхронизация...
Take-multiple-photos-of-a-single-organism = Сделайте несколько фото отдельного организма
Taxa = Таксоны
Terms-of-Use = Условия использования
The-location-will-not-be-visible-to-others = Местоположение не будет видимым для других, это может препятствовать идентификации организма
The-models-that-suggest-species = Модели, предполагающие виды на основе визуального сходства и местоположения, были созданы отчасти благодаря сотрудничеству с Сарой Бири, Томом Бруксом, Элайджей Коулом, Кристианом Ланге, Ойсином Мак Аодой, Пьетро Пероной и Грантом Ван Хорном.
Traditional-Project = Традиционный проект
Umbrella-Project = Зонтичный проект
Unknown--rank = Неизвестно
Unknown--taxon = Неизвестно
Unknown--user = Неизвестно
Unknown-error = Неизвестная ошибка
Users = Пользователи
VIEW-FOLLOWERS = ПОСМОТРЕТЬ ТЕХ, КТО НА ВАС ПОДПИСАН
VIEW-FOLLOWING = ПОСМОТРЕТЬ ТЕХ, НА КОГО ВЫ ПОДПИСАНЫ
View-in-browser = Просмотр в браузере
View-suggestions = Посмотреть предложения
Welcome-to-iNaturalist = Добро пожаловать на iNaturalist!
Wild = Дикий
Withdraw = Отозвать
Worldwide = По всему миру
X-FOLLOWERS =
    { $count ->
        [one] { $count } ПОДПИСАВШИЙСЯ
       *[other] { $count } ПОДПИСАВШИХСЯ
    }
X-MEMBERS = { $count }  УЧАСТНИКОВ
X-of-Y =
    { $x ->
        [one] 1
       *[other] { $x }
    } { $y ->
        [one] of { $y }
       *[other] of { $y }
    }
X-PROJECTS =
    { $projectCount ->
        [one] { $projectCount } ПРОЕКТ
        [two] { $projectCount } ПРОЕКТА
        [few] { $projectCount } ПРОЕКТОВ
       *[other] { $projectCount } ПРОЕКТОВ
    }
X-SOUNDS =
    { $count ->
        [one] 1 АУДИО
       *[other] { $count } АУДИО
    }
X-Species =
    { $count ->
        [one] { $count } Вид
       *[other] { $count } Видов
    }
x-uploads-failed =
    { $count ->
        [one] { $count } выгрузка не удалась
       *[other] { $count } выгрузок не удалось
    }
Yes-license-my-photos = Да, предоставьте лицензию на мои фото, аудио и наблюдения, чтобы ученые могли использовать мои данные (рекомендуется).
You-are-offline = Вы не в сети
You-are-offline-Tap-to-reload = Вы не в сети. Нажмите для перезагрузки.
You-are-offline-Tap-to-try-again = Вы не в сети. Нажмите ещё раз для перезагрузки.
You-can-add-up-to-20-media = Вы можете добавлять до 20 фото и 20 аудио в одно наблюдение.
You-can-also-check-out-merchandise = Вы также можете посмотреть товары для iNaturalist и Seek в нашем магазине (ниже)!
You-can-also-explore-existing-observations = Вы также можете изучить имеющиеся наблюдения на iNaturalist, чтобы выяснить, что находится вокруг вас.
You-can-click-join-on-the-project-page = Вы можете нажать "присоединиться" на странице проекта.
You-can-find-answers-on-our-help-page = Ответы на вопросы можно найти на нашей страничке помощи.
You-can-only-add-20-photos-per-observation = Вы можете добавлять только 20 фото в одно наблюдение
You-can-search-observations-of-any-plant-or-animal = Через меню Поиск вы можете искать наблюдения любого растения или животного в любой точке мира!
You-can-still-share-the-file = Вы можете поделиться файлом с другим приложением. Если вы можете отправить его по электронной почте, пожалуйста, отправьте его на { $email }
You-can-upload-this-observation-to-our-community = Вы можете загрузить это наблюдение в наше сообщество, чтобы получить идентификацию от реального человека и помочь нашему ИИ улучшить свои идентификационные данные в будущем.
You-changed-filters-will-be-discarded = Вы изменили фильтры, но они не были применены к результатам поиска по запросу.
You-have-opted-out-of-the-Community-Taxon = Вы отказались от таксона сообщества
You-havent-joined-any-projects-yet = Вы еще не присоединились ни к каким проектам.
You-must-be-logged-in-to-view-messages = Вы должны войти в систему для просмотра ваших сообщений.
You-need-an-Internet-connection-to-do-that = Для этого необходимо подключение к Интернету.
You-need-log-in-to-do-that = Чтобы сделать это, авторизуйтесь
You-will-see-notifications = Как только войдете в систему и загрузите наблюдения, вы увидите здесь уведомления .
Your-donation-to-iNaturalist = Ваше пожертвование в пользу iNaturalist поможет улучшить и стабилизировать работу мобильных приложений и веб-сайта, которые связывают миллионы людей с природой и обеспечивают защиту биоразнообразия во всем мире!
Your-email-is-confirmed = Ваш адрес электронной почты подтвержден! Пожалуйста, войдите для продолжения.
Your-location-uncertainty-is-over-x-km = Неопределенность вашего местоположения превышает { $x } км, что слишком много, чтобы помочь экспертам. Отредактируйте местоположение и масштаб до тех пор, пока круг точности не приобретёт зеленый цвет и не центрируется на том  месте, где вы наблюдали за организмом.
Youre-always-in-control-of-the-location-privacy = Вы всегда контролируете конфиденциальность местоположения каждого создаваемого вами наблюдения.
Youve-denied-permission-prompt = Вам отказано в разрешении. Пожалуйста, задайте разрешение в настройках приложения.
Youve-previously-denied-camera-permissions = Вы ранее запретили доступ к камере, поэтому включите доступ к ней в настройках.
Youve-previously-denied-gallery-permissions = Вы ранее запретили доступ к галерее фото, поэтому включите доступ к ней в настройках.
Youve-previously-denied-location-permissions = Вы ранее запретили доступ к местоположению, поэтому включите доступ к нему в настройках.
Youve-previously-denied-microphone-permissions = Вы ранее запретили доступ к микрофону, поэтому включите доступ к нему в настройках.
Zoom-in-as-much-as-possible-to-improve = Увеличьте масштаб в максимально возможной степени, чтобы улучшить точность местоположения и улучшить идентификацию.
Zoom-to-current-location = Перейдите к текущему местоположению
zoom-x = { $zoom }×
