### DO NOT EDIT THIS FILE!
###
### This file came from Crowdin and was normalized by ftl.js.
### It will be overwritten during the next translation sync. To add
### translations, go to https://crowdin.com/editor/inaturalistios/724
###

ABOUT = ᱵᱟᱵᱚᱛ
Agree = ᱦᱮᱸᱥᱤᱭᱟᱹᱨ
All = ᱡᱷᱚᱛᱚ
Camera = ᱠᱮᱢᱮᱨᱟ
Cancel = ᱵᱟᱹᱰᱨᱟᱹ
Casual--quality-grade = ᱚᱝᱠᱟ ᱜᱮ
Collection-Project = ᱡᱟᱣᱨᱟ ᱯᱟᱱᱛᱷᱟ
Date = ᱢᱟᱹᱦᱤᱛ
Delete-observation = ᱧᱮᱞᱯᱚᱨᱚᱠ ᱢᱮᱴᱟᱣ ᱢᱮ
Delete-photo = ᱪᱤᱛᱟᱹᱨ ᱢᱮᱴᱟᱣ ᱢᱮ
Edit = ᱥᱟᱯᱲᱟᱣ
Edit-Observation = ᱧᱮᱞᱯᱚᱨᱚᱠᱷ ᱥᱟᱯᱲᱟᱣ ᱢᱮ
Error = ᱵᱷᱩᱞ
Error-title = ᱵᱷᱩᱞ
Explore = ᱥᱮᱸᱫᱽᱨᱟ
improving--identification = ᱥᱩᱫᱷᱨᱟᱹᱣ
leading--identification = ᱟᱹᱭᱩᱨ ᱤᱜᱼᱫᱤ
Learn-More = ᱰᱷᱮᱨ ᱪᱮᱫᱚᱜ
Location = ᱡᱟᱭᱜᱟ
maverick--identification = Maverick
Nearby = ᱥᱩᱨ ᱠᱚᱨᱤᱱ
Needs-ID--quality-grade = ID ᱫᱚᱨᱠᱟᱨ
No-Location = ᱡᱟᱭᱜᱟ ᱵᱟᱝ ᱧᱟᱢ ᱞᱮᱱᱟ
No-Media = ᱪᱮᱫ ᱢᱤᱰᱤᱭᱟ ᱵᱟᱹᱱᱩᱜᱼᱟ
Obscured = ᱫᱷᱩᱱᱫᱞᱟᱹ
OK = ᱴᱷᱤᱠ
Open = ᱡᱷᱤᱡᱽ
Private = ᱱᱤᱥᱚᱱ
Projects = ᱯᱟᱱᱛᱷᱟ ᱠᱚ
Research-Grade--quality-grade = ᱨᱤᱥᱚᱨᱪ ᱜᱽᱨᱮᱰ
Restore = ᱫᱚᱦᱰᱟ ᱡᱚᱜᱟᱣ
Satellite--map-type = ᱥᱮᱴᱮᱞᱟᱭᱤᱴ
Search = ᱥᱮᱸᱫᱽᱨᱟ
Share = ᱦᱟᱹᱴᱤᱧ
Stop-verb = ᱛᱷᱩᱢ
supporting--identification = ᱜᱚᱲᱚ
Syncing = ᱟᱹᱭᱩᱨ ᱢᱤᱫᱚᱜ ᱠᱟᱱᱟ ...
Taxa = ᱴᱮᱠᱥᱟ
Traditional-Project = ᱯᱚᱨᱚᱢᱯᱚᱨᱟ ᱯᱟᱱᱛᱷᱟ
Umbrella-Project = ᱪᱷᱚᱛᱟ ᱯᱟᱱᱛᱷᱟ
Unknown--rank = ᱵᱟᱝ ᱵᱟᱰᱟᱭ
Unknown--taxon = ᱵᱟᱝ ᱵᱟᱰᱟᱭ
Unknown--user = ᱵᱟᱝ ᱵᱟᱰᱟᱭ
View-in-browser = ᱵᱽᱨᱟᱣᱡᱚᱨ ᱨᱮ ᱧᱮᱞ ᱢᱮ
Withdraw = ᱚᱰᱚᱠ
