### DO NOT EDIT THIS FILE!
###
### This file came from Crowdin and was normalized by ftl.js.
### It will be overwritten during the next translation sync. To add
### translations, go to https://crowdin.com/editor/inaturalistios/724
###

A-global-community-for-nature = Doğa için küresel bir topluluk
ABOUT = HAKKINDA
ABOUT-COLLECTION-PROJECTS = KOLEKSİYON PROJELERİ HAKKINDA
ABOUT-INATURALIST = iNaturalist HAKKINDA
ABOUT-THE-DQA = DQA HAKKINDA
About-the-DQA-description = Kalite Derecesi, bir iNaturalist gözleminin biyolojik çeşitlilik verisi olarak doğruluğunu, hassasiyetini, tamamlanmışlığını, alakalılığını ve uygunluğunu özetler. Bazı özellikler otomatik olarak belirlenirken, diğerleri iNat kullanıcıları tarafından oylanır. iNaturalist, lisanslı "Araştırma Derecesi" gözlemleri, bilim ve koruma amacıyla kullanılmak üzere bir dizi veri ortağıyla paylaşır.
ABOUT-TRADITIONAL-PROJECTS = GELENEKSEL PROJELER HAKKINDA
ABOUT-UMBRELLA-PROJECTS = ŞEMSİYE PROJELERİ HAKKINDA
accessible-comname-sciname = { $commonName } ({ $scientificName })
accessible-sciname-comname = { $scientificName } ({ $commonName })
Account-Deleted = Hesap silindi
ACCOUNT-SETTINGS = HESAP AYARLARI
ACTIVITY = FAALİYET
Add-agreement = Anlaşma Ekle
ADD-AN-ID = Bir Kimlik Ekle
Add-an-ID-Later = Kimliği daha sonra ekle
ADD-COMMENT = YORUM EKLE
Add-Date-Time = Tarih/Saat ekle
Add-disagreement = Anlaşmazlık Ekle
ADD-EVIDENCE = Kanıt Ekle
Add-evidence = Kanıt ekle
Add-favorite = Favori ekle
Add-Location = Konum ekle
ADD-LOCATION-FOR-BETTER-IDS = DAHA İYİ TANIMLAMALAR İÇİN KONUM EKLE
Add-location-to-refresh-suggestions = Önerileri yenilemek için konum ekle
Add-observations = Gözlemleri ekle
ADD-OPTIONAL-COMMENT = İSTEĞE BAĞLI YORUM EKLE
Add-optional-notes = İsteğe bağlı not ekle
Adds-ID = Tanımlama ekler
Adds-your-vote-of-agreement = Onayınızı ekler
Adds-your-vote-of-disagreement = Katılmama oyunuzu ekler
Advanced-Mode = Gelişmiş Mod
ADVANCED-SETTINGS = GELİŞMİŞ AYARLAR
Affiliation = Üyelik: { $site }
After-capturing-or-importing-photos-show = Fotoğrafları çektikten veya içe aktardıktan sonra, göster:
Agree = Onayla
AGREE = ONAYLA
AGREE-WITH-ID = TANIMLAMAYA KATILIYOR MUSUN?
Agree-with-ID-description = Tanımlamaya katılmak ve aşağıdaki tanımlamayı önermek ister misin?
AI-Camera = YZ Kamera
ALL = TÜMÜ
All = Tümü
All-observation-options--list = Tüm gözlem seçenekleri: iNaturalist YZ Kamera, Standart Kamera, Fotoğraf Kitaplığından Yükleme ve Ses Kaydedici
All-observations = Tüm gözlemler
All-observations-need-a-date-and-location-to-be-used-for-science = Tüm gözlemlerin bilim için kullanılabilmesi için bir tarih ve konuma ihtiyacı vardır. Daha fazla bilgi gerekiyorsa lütfen gözlemleri düzenleyin.
All-organisms = Tüm organizmalar
all-rights-reserved = tüm hakları saklıdır
All-taxa = Tüm taksonlar
ALL-USERS-EXCEPT = TÜM KULLANICILAR, ŞUNLAR HARİÇ:
ALLOW-LOCATION-ACCESS = KONUM ERŞİMİNE İZİN VER
Already-have-an-iNaturalist-account = Zaten bir iNaturalist hesabınız var mı?
An-Internet-connection-is-required = Daha fazla gözlem yüklemek için bir internet bağlantısı gereklidir.
Analyzing-for-the-best-identification = En iyi tanımlama için analiz yapılıyor...
Any--date = Herhangi
Any--establishment-means = Herhangi
Any--media-type = Herhangi
Any--project = Herhangi
Any--quality-grade = Herhangi
Any--user = Herhangi
Anyone-using-iNaturalist-can-see = iNaturalist'i kullanan herkes bu türün nerede gözlemlendiğini görebilir ve bilim insanları bunu araştırma için en kolay şekilde kullanabilir.
APP-LANGUAGE = UYGULAMA DİLİ
apple-full-name = { JOIN($namePrefix, $givenName, $middleName, $nickname, $familyName, $nameSuffix, separator: " ") }
APPLY-FILTERS = FİLTRELERİ UYGULA
Apply-filters = Filtreleri uygula
April = Nisan
Are-you-an-educator = iNaturalist'i öğrencilerinizle kullanmak isteyen bir eğitimci misiniz?
Are-you-sure-you-want-to-log-out = iNaturalist hesabınızdan çıkış yapmak istediğinizden emin misiniz? iNaturalist'e yüklenmemiş tüm gözlemler silinecektir.
attribution-cc-by = bazı hakları saklıdır (CC BY)
attribution-cc-by-nc = bazı hakları saklıdır (CC BY-NC)
attribution-cc-by-nc-nd = bazı hakları saklıdır (CC BY-NC-ND)
attribution-cc-by-nc-sa = bazı hakları saklıdır (CC BY-NC-SA)
attribution-cc-by-nd = bazı hakları saklıdır (CC BY-ND)
attribution-cc-by-sa = bazı hakları saklıdır (CC BY-SA)
August = Ağustos
BACK-TO-LOGIN = GİRİŞE GERİ DÖN
Bulk-importer = Toplu içe aktarma
By-exiting-changes-not-saved = Çıktığınızda, gözleminizdeki değişiklikler kaydedilmeyecektir.
By-exiting-observation-not-saved = Çıktığınızda, gözleminiz kaydedilmeyecektir.
By-exiting-your-observations-not-saved = Çıktığınızda gözlemleriniz kaydedilmeyecektir. Bunları cihazınıza kaydedebilir veya silebilirsiniz.
By-exiting-your-photos-will-not-be-saved = Çıktığınızda fotoğraflarınız kaydedilmeyecektir.
By-exiting-your-recorded-sound-will-not-be-saved = Çıktığınızda, kaydettiğiniz ses kaydedilmeyecektir.
BY-ME = BENİM TARAFIMDAN
By-uploading-your-observation-to-iNaturalist-you-can = Gözleminizi iNaturalist'e yükleyerek şunları yapabilirsiniz:
Camera = Kamera
CANCEL = İPTAL
Cancel = İptal
Captive-Cultivated = Kısıtlanmış/Ekili
Casual--quality-grade = Sıradan
CC-BY = CC BY
CC-BY-NC = CC BY-NC
CC-BY-NC-ND = CC BY-NC-ND
CC-BY-NC-SA = CC BY-NC-SA
CC-BY-ND = CC BY-ND
CC-BY-SA = CC BY-SA
CC0 = CC0
CHANGE-APP-LANGUAGE = UYGULAMA DİLİNİ DEĞİŞTİR
CHANGE-DATE = TARİHİ DEĞİŞTİR
Change-date = Tarihi değiştir
CHANGE-END-DATE = BİTİŞ TARİHİNİ DEĞİŞTİR
Change-end-date = Bitiş tarihini değiştir
Change-observations-sort-order = Change observations sort order
Change-project = Projeyi değiştir
Change-species-sort-order = Change species sort order
CHANGE-START-DATE = BAŞLANGIÇ TARİHİNİ DEĞİŞTİR
Change-start-date = Bitiş tarihini değiştir
Change-taxon = Taksonu değiştir
Change-taxon-filter = Takson filtresini değiştir
Change-user = Kullanıcıyı değiştir
Change-zoom = Yakınlaştırmayı değiştir
CHECK-YOUR-EMAIL = E-POSTANIZI KONTROL EDİN!
CHOOSE-A-USERNAME = BİR KULLANICI ADI SEÇ
Choose-taxon = Takson seç
Choose-top-taxon = En önerilen taksonu seç
Clear = Temizle
Close = Kapat
Close-permission-request-screen = İzin talebi ekranını kapat
Close-search = Aramayı kapat
Closes-explanation = Açıklamayı kapatır
Closes-introduction = Tanıtımı kapatır
Closes-withdraw-id-sheet = "Tanımlamayı Geri Çek" penceresini kapatır
COLLABORATORS = KATKI SAĞLAYANLAR
Collection-Project = Koleksiyon Projesi
Combine-Photos = Fotoğrafları Birleştir
COMMENT = YORUM
Comment-options = Yorum seçenekleri
Common-Name-Scientific-Name = Yaygın Ad (Bilimsel Ad)
Community-Discussion = Topluluk Tartışması
Community-Guidelines = Topluluk İlkeleri
COMMUNITY-GUIDELINES = TOPLULUK İLKELERİ
Confidence--label = Güvenilirlik
CONFIRM = ONAYLA
Congratulations-You-made-your-first-observation = Tebrikler! İlk gözlemini yaptın!
Connect-with-expert-naturalists = Uzman doğa bilimcilerle bağlantı kur
Connect-with-other-naturalists = Diğer doğa bilimcilerle bağlantı kurun ve sohbetlere katılın.
Connection-problem-Please-try-again-later = Bağlantı sorunu. Lütfen daha sonra tekrar deneyin.
CONTACT-SUPPORT = DESTEK İLE İLETİŞİM
CONTINUE = DEVAM ET
Coordinates-copied-to-clipboard = Koordinatlar panoya kopyalandı
Copy-coordinates = Koordinatları Kopyala
Copyright = Telif Hakkı
Could-not-find-a-camera-on-this-device = Bu cihazda kamera bulunamadı
Couldnt-create-comment = Yorum oluşturulamadı
Couldnt-create-identification-error = Tanımlama oluşturulamadı { $error }
Couldnt-create-identification-unknown-error = Tanımlama oluşturulamadı, bilinmeyen hata.
CREATE-AN-ACCOUNT = HESAP OLUŞTUR
Create-observation-with-no-evidence = Kanıt olmadan gözlem oluştur
DATA-QUALITY = VERİ NİTELİĞİ
DATA-QUALITY-ASSESSMENT = VERİ NİTELİK DEĞERLENDİRMESİ
Data-Quality-Assessment = Veri Nitelik Değerlendirmesi
Data-quality-assessment-can-taxon-still-be-confirmed-improved-based-on-the-evidence = Kanıtlara dayanarak, Topluluk Taksonu hâlâ geliştirilebilir mi?
Data-quality-assessment-community-taxon-species-level-or-lower = Topluluk Taksonu tür düzeyinde ya da altında
Data-quality-assessment-date-is-accurate = Tarihi doğru
Data-quality-assessment-date-specified = Tarih belirtilmiş
Data-quality-assessment-description-casual = Bu gözlem Araştırma Sınıfı statüsü koşullarını karşılamamıştır.
Data-quality-assessment-description-needs-id = Bu gözlem henüz Araştırma Sınıfı statüsü koşullarını karşılamamıştır:
Data-quality-assessment-description-research = Artık araştırma için kullanılabilir ve diğer web sitelerinde yer alabilir.
Data-quality-assessment-evidence-of-organism = Organizmanın kanıtı
Data-quality-assessment-has-photos-or-sounds = Fotoğraf veya ses var
Data-quality-assessment-id-supported-by-two-or-more = İki ya da daha çok kişi tarafından desteklenen tanım var
Data-quality-assessment-location-is-accurate = Konum doğru
Data-quality-assessment-location-specified = Konum belirtilmiş
Data-quality-assessment-organism-is-wild = Yabani organizma
Data-quality-assessment-recent-evidence-of-organism = Organizmanın yakın zamanlı kanıtı
Data-quality-assessment-single-subject = Tek bir organizmayla ilgili kanıt
Data-quality-assessment-title-casual = Bu gözlem Sıradan Sınıf'tır
Data-quality-assessment-title-needs-id = Bu gözlemin tanımlamaya ihtiyacı var
Data-quality-assessment-title-research = Bu gözlem Araştırma Sınıfı!
DATE = TARİH
Date = Tarih
date-format-long = d LLLL yyyy
date-format-month-day = d MMM
date-format-month-year = MMMM yyyy
date-format-short = d/MM/yyyy
DATE-OBSERVED = GÖZLEM TARİHİ
Date-observed = Gözlem Tarihi
Date-observed-header-short = Gözlem Tarihi
DATE-OBSERVED-NEWEST = GÖZLEM TARİHİ - YENİDEN ESKİYE
DATE-OBSERVED-OLDEST = GÖZLEM TARİHİ - ESKİDEN YENİYE
Date-Range = Tarih Aralığı
DATE-RANGE = TARİH ARALIĞI
date-to-date = { $d1 } - { $d2 }
DATE-UPLOADED = YÜKLENME TARİHİ
Date-uploaded = Yüklenme tarihi
Date-uploaded-header-short = Yüklendi:
DATE-UPLOADED-NEWEST = YÜKLENME TARİHİ - YENİDEN ESKİYE
DATE-UPLOADED-OLDEST = YÜKLENME TARİHİ - ESKİDEN YENİYE
Date-uploaded-on-header-short = Yüklendi:
datetime-difference-days = { $count }d
datetime-difference-hours = { $count }HH
datetime-difference-minutes = { $count }mm
datetime-difference-weeks = { $count }w
datetime-format-long = HH:mm
datetime-format-long-with-zone = HH:mm (zzz)
datetime-format-short = d/MM/yyyy HH:mm
datetime-format-short-with-zone = d/MM/yyyy HH:mm zzz
December = Aralık
DELETE = SİL
Delete-all-observations = Tüm gözlemleri sil
Delete-comment = Yorumu sil
DELETE-COMMENT--question = YORUM SİLİNSİN Mİ?
Delete-current-observation = Mevcut gözlemi sil
Delete-observation = Gözlemi sil
DELETE-OBSERVATION--question = GÖZLEM SİLİNSİN Mİ?
Delete-photo = Fotoğrafı sil
Delete-sound = Sesi sil
Deletes-entered-text = Girilen metni siler
Deleting-x-of-y--observations =
    { $total ->
        [one] { $total } gözlem siliniyor
       *[other] { $total } gözlemden { $currentDeleteCount } tanesini siliyor
    }
Deleting-x-of-y-observations-2 =
    { $total ->
        [one] gözlem siliniyor
       *[other] { $total } gözlemden { $currentDeleteCount } tanesini siliyor
    }
Details = Ayrıntılar
DETAILS = AYRINTILAR
Device-storage-full = Aygıt depolama alanı dolu
Device-storage-full-description = iNaturalist fotoğraflarınızı kaydedemeyebilir veya çökebilir.
Disable-flash = Flaşı kapat
Disable-location = Konumu devre dışı bırak
Disagreement = *@{ $username } bunun <0/> olduğunu kabul etmiyor
DISCARD = İPTAL ET
DISCARD-ALL = TÜMÜNÜ İPTAL ET
DISCARD-CHANGES = DEĞİŞİKLİKLERİ İPTAL ET
DISCARD-FILTER-CHANGES = FİLTRE DEĞİŞİKLİKLERİNİ İPTAL ET
DISCARD-MEDIA--question = ORTAM İPTAL EDİLSİN Mİ?
DISCARD-OBSERVATION = GÖZLEMİ İPTAL ET
DISCARD-PHOTOS--question = FOTOĞRAFLAR İPTAL EDİLSİN Mİ?
DISCARD-RECORDING = KAYDI İPTAL ET
DISCARD-SOUND--question = SES İPTAL EDİLSİN Mİ?
DISCARD-X-OBSERVATIONS =
    { $count ->
        [one] GÖZLEMİ İPTAL ET
       *[other] { $count } GÖZLEMİ İPTAL ET
    }
DISCOVER-NATURE-AROUND-YOU = ÇEVRENDEKİ DOĞAYI KEŞFET
DISMISS = İPTAL ET
Do-you-know-what-group-this-is-in = Bunun hangi grupta olduğunu biliyor musun?
DONATE = BAĞIŞ YAP
DONATE-TO-INATURALIST = INATURALIST'E BAĞIŞ YAP
DONE = TAMAMLANDI
Dont-have-an-account = <0>Bir hesabın yok mu? </0><1>Kaydol</1>
During-app-start-no-model-found = Uygulama başlangıcı sırasında bilgisayar görü modeli bulunamadı. YZ kamerası olmayacak.
Edit = Düzenle
EDIT-COMMENT = YORUMU DÜZENLE
Edit-comment = Yorumu düzenle
Edit-identification = Tanımlamayı düzenle
EDIT-LOCATION = KONUMU DÜZENLE
Edit-location = Konumu  düzenle
Edit-Observation = Gözlemi Düzenle
Edit-your-profile-change-your-settings = Profilini düzenle, bildirim ayarlarını değiştir ve hesabının diğer tüm bölümlerini yönet.
Edits-this-observations-taxon = Bu gözlemin taksonunu düzenler
EDUCATORS = EĞİTMENLER
EMAIL = E-POSTA
EMAIL-DEBUG-LOGS = E-POSTA HATA AYIKLAMA GÜNLÜKLERİ
Enable-flash = Flaşı etkinleştir
Enable-location = Konumu etkinleştir
Enable-notifications = Bildirimleri etkinleştir
Endemic = Endemik
Endemic-to-place = { $place } bölgesine endemik
Error = Hata
ERROR = HATA
ERROR-LOADING-DQA = VND YÜKLEME HATASI
Error-title = Hata
ERROR-VOTING-IN-DQA = VND OYLAMA HATASI
Error-voting-in-DQA-description = Oyunuz VND'de kullanılmamış olabilir. İnternet bağlantınızı kontrol edin ve tekrar deneyin.
Establishment = Yerleşim Tipi
ESTABLISHMENT-MEANS = YERLEŞİM TİPİ
Every-observation-needs = Her gözlemin tanımlayıcılara yardımcı olması için bir konum, tarih ve saate ihtiyacı vardır. Konum gizliliği konusunda endişeleriniz varsa coğrafi gizliliği düzenleyebilirsiniz.
Every-time-a-collection-project = Bir koleksiyon projesinin sayfası her yüklendiğinde, iNaturalist hızlı bir arama gerçekleştirecek ve projenin gerekliliklerine uyan tüm gözlemleri görüntüleyecektir. Bu, katılımcıların gözlemlerini bir projeye manuel olarak eklemek için fazladan bir adım atmalarına gerek kalmadan bir sınıf projesi, bir park veya bir bioblitz gibi bir dizi gözlemi görüntülemenin kolay bir yoludur.
EVIDENCE = KANIT
Exact-Date = Tam Tarih
EXACT-DATE = TAM TARİH
except = dışında
EXPAND-MAP = HARİTAYI GENİŞLET
Experts-help-verify-and-improve-IDs = Uzmanlar, tanımlamaların doğrulanmasına ve geliştirilmesine yardımcı olur
Explore = Keşfet
EXPLORE = KEŞFET
Explore-Filters = Filtreleri Keşfet
EXPLORE-IDENTIFIERS = TANIMLAYICILARI KEŞFET
EXPLORE-OBSERVATIONS = GÖZLEMLERİ KEŞFET
EXPLORE-OBSERVERS = GÖZLEMCİLERİ KEŞFET
EXPLORE-SPECIES = TÜRLERİ KEŞFET
Failed-to-delete-sound = Ses silinemedi
Failed-to-log-in = Giriş yapılamadı
FEATURED = ÖNE ÇIKAN
February = Şubat
FEEDBACK = GERİ BİLDİRİM
Feedback-Submitted = Geri Bildirim Gönderildi
Fetching-location = Konum getiriliyor...
Filter = Filtre
FILTER-BY-A-PROJECT = PROJEYE GÖRE FİLTRELE
FILTER-BY-A-USER = KULLANICIYA GÖRE FİLTRELE
Filter-by-observed-between-dates = Belirli iki tarih arasında gözlemlenen gözlemlere göre filtrele
Filter-by-observed-during-months = Belirli aylarda gözlemlenen gözlemlere göre filtrele
Filter-by-observed-on-date = Belirli bir tarihte gözlemlenen gözlemlere göre filtrele
Filter-by-uploaded-between-dates = Belirli iki tarih arasında yüklenen gözlemlere göre filtrele
Filter-by-uploaded-on-date = Belirli bir tarihte yüklenen gözlemlere göre filtrele
Filters = Filtreler
Flagged = İşaretli
Flash = Flaş
Flip-camera = Kamerayı çevir
FOLLOW = TAKİP ET
FOLLOWING-X-PEOPLE =
    { $count ->
        [one] { $count } KİŞİYİ TAKİP EDİYORSUN
       *[other] { $count } KİŞİYİ TAKİP EDİYORSUN
    }
Forgot-Password = Şifremi Unuttum
GEOPRIVACY = COĞRAFİ GİZLİLİK
Geoprivacy-status = Coğrafi Gizlilik: { $status }
Get-an-instant-ID-of-any-plant-animal-fungus = Herhangi bir bitki, hayvan veya mantarın anında kimliğini öğrenin
Get-feedback-from-naturalists-and-experts-who-will-help-verify = Tanımlamalarınızı doğrulamanıza ve geliştirmenize yardımcı olacak doğa bilimcilerden ve uzmanlardan geri bildirim alın.
Get-your-identification-verified-by-real-people = Tanımlamanızın iNaturalist topluluğundaki gerçek kişiler tarafından doğrulanmasını sağlayın
Go-back = Geri git
Google-Play-Services-Not-Installed = Google Play Hizmetleri Yüklü Değil
GRANT-PERMISSION = İZİN VER
Grant-Permission-title = İzin Ver
Group-Photos = Grup Fotoğrafları
Group-photos-onboarding = Fotoğrafları gözlemlere grupla – her gözlemde yalnızca bir türe yer verdiğinden emin ol.
HELP = YARDIM
Help-create-Research-Grade-data-used-in-science-and-conservation = Bilim ve koruma alanında kullanılan Araştırma Sınıfı verilerinin oluşturulmasına yardımcı olun.
Help-protect-species = Türlerin korunmasına yardımcı olun
Hide = Gizle
Highest = En Yüksek
HIGHEST-RANK = EN YÜKSEK DÜZEY
I-agree-to-the-Terms-of-Use = <0>Kullanım Koşullarını ve Gizlilik Politikasını kabul ediyorum ve Topluluk Kurallarını inceledim (</0><1>gerekli</1><0>).</0>
Iconic-taxon-name = İkonik takson adı: { $iconicTaxon }
ID-in-Camera = Kameradaki Tanımlama
ID-Suggestions = Tanımlama Önerileri
ID-Withdrawn = Tanımlama Geri Alındı
IDENTIFICATION = TANIMLAMA
Identification-options = Tanımlama seçenekleri
IDENTIFICATIONS-WITHOUT-NUMBER =
    { $count ->
        [one] TANIMLAMA
       *[other] TANIMLAMA
    }
Identifiers = Tanımlayıcılar
Identifiers-View = Tanımlayıcılar Görünümü
IDENTIFY = TANIMLA
Identify-organisms-in-real-time-with-your-camera = Kameranızla organizmaları gerçek zamanlı olarak tanımlayın
Identify-species-anywhere = Türleri herhangi bir yerde tanımlayın
If-an-account-with-that-email-exists = Bu e-postaya sahip bir hesap varsa, e-postanıza şifre sıfırlama talimatları gönderdik.
If-you-have-an-existing-account-try-sign-in-reset = Mevcut bir iNat hesabınız varsa, kullanıcı adınız ve şifrenizle oturum açmayı veya hesabınızla ilişkili e-posta adresini kullanarak şifrenizi sıfırlamayı deneyin.
If-you-leave-x-of-your-observations-removed =
    Eğer bu geleneksel projeden ayrılırsan, { $count ->
        [one] 1 gözlemin
       *[other] { $count } gözlemin
    } de bu projeden çıkarılacaktır.
If-you-save-this-observation-and-upload-it-to-iNaturalist = Bu gözlemi kaydedip iNaturalist'e yüklersen, diğer insanlar tanımlanmasına yardımcı olabilir.
If-you-want-to-collate-compare-promote = Bir dizi mevcut projeyi birleştirmek, karşılaştırmak veya tanıtmak istiyorsan, kullanman gereken şey bir Şemsiye projesidir. Örneğin, 60'tan fazla projeyi bir araya getiren 2018 City Nature Challenge, herkesin her bir şehrin gözlemlerini karşılaştırıp kıyaslayabileceği harika bir ortam oluşturdu. Bir Şemsiye projesinde hem Koleksiyon hem de Geleneksel projeler kullanılabilir ve bir Şemsiye projesinde 500'e kadar proje yer alabilir.
If-youre-seeing-this-error = Bunu görüyorsanız ve çevrim içiyseniz, iNat personeli zaten bilgilendirilmiştir. Bir hata bulduğunuz için teşekkürler! Çevrim dışıysanız, lütfen bir ekran görüntüsü alın ve internete bağlandığınızda bize bir e-posta gönderin.
IGNORE-LOCATION = KONUMU YOKSAY
Ignore-notifications = Bildirimleri yoksay
Ignoring-location = Konumu yoksayma
Import-Photos-From = Fotoğrafları Şuradan İçe Aktar:
IMPORT-X-OBSERVATIONS =
    { $count ->
        [one] 1 GÖZLEMİ
       *[other] { $count } GÖZLEMİ
    } İÇE AKTAR
Improve-suggestions-by-using-your-location = Konumunuzu kullanarak önerileri iyileştirin
IMPROVE-THESE-SUGGESTIONS-BY-USING-YOUR-LOCATION = KONUMUNUZU KULLANARAK BU ÖNERİLERİ İYİLEŞTİRİN
improving--identification = Geliştirici
INATURALIST-ACCOUNT-SETTINGS = INATURALIST HESAP AYARLARI
iNaturalist-AI-Camera = iNaturalist YZ Kamerası
iNaturalist-can-save-photos-you-take-in-the-app-to-your-devices-library = iNaturalist, uygulamada çektiğiniz fotoğrafları cihazınızın kitaplığına kaydedebilir.
iNaturalist-can-use-your-location-to-give-you-better-identification-suggestions = iNaturalist, size daha iyi tanımlama önerileri sunmak için konumunuzu kullanabilir. Ayrıca yakınlarda görülen türleri bulmanıza yardımcı olmak için de kullanıyoruz. Konumunuzu paylaşmak, bilim için yararlı veriler oluşturmayı kolaylaştırır.
INATURALIST-COMMUNITY = INATURALIST TOPLULUĞU
INATURALIST-FORUM = INATURALIST FORUMU
iNaturalist-has-no-ID-suggestions-for-this-photo = iNaturalist'in bu fotoğraf için tanımlama önerisi yok.
INATURALIST-HELP-PAGE = INATURALIST YARDIM SAYFASI
iNaturalist-helps-you-identify = iNaturalist, bilim ve koruma için veri üretirken çevrenizdeki bitki ve hayvanları tanımlamanıza yardımcı olur. Doğa hakkında daha fazla bilgi edinmenize yardımcı olabilecek milyonlarca bilim insanı ve doğa bilimciden oluşan bir toplulukla bağlantı kurun!
iNaturalist-identification-suggestions-are-based-on = iNaturalist'in tanımlama önerileri, { $user1 }, { $user2 }, { $user3 } ve diğerleri dahil olmak üzere iNaturalist topluluğu tarafından yapılan gözlemlere ve tanımlamalara dayanmaktadır.
iNaturalist-is-a-501 = iNaturalist, Amerika Birleşik Devletleri'nde kâr amacı gütmeyen bir 501(c)(3) kuruluşudur (Vergi Kimliği/EIN 92-1296468).
iNaturalist-is-loading-ID-suggestions = iNaturalist tanımlama önerilerini yüklüyor...
iNaturalist-is-supported-by = iNaturalist, Amerika Birleşik Devletleri merkezli bağımsız, 501(c)(3) kâr amacı gütmeyen bir kuruluş tarafından desteklenmektedir. iNaturalist platformu bu uygulamayı, Seek by iNaturalist'i, iNaturalist web sitesini ve daha fazlasını içerir.
iNaturalist-is-supported-by-our-community = iNaturalist muhteşem topluluğumuz tarafından desteklenmektedir. Gözlemlerini ve tanımlamalarını ekleyen günlük doğa bilimcilerden, taksonomimizi yöneten ve moderasyona yardımcı olan küratörlere, iNaturalist'i dünya çapındaki izleyiciler için daha erişilebilir kılan gönüllü çevirmenlere ve topluluk tabanlı bağışçılarımıza kadar, iNaturalist'i bu platform haline getiren topluluğumuzdaki tüm insanlara olağanüstü minnettarız.
iNaturalist-mission-is-to-connect = iNaturalist'in misyonu insanları doğayla buluşturmak ve biyoçeşitlilik bilimi ve korumasını ilerletmektir.
INATURALIST-MISSION-VISION = INATURALIST'İN MİSYON VE VİZYONU
INATURALIST-NETWORK = INATURALIST AĞI
INATURALIST-SETTINGS = INATURALIST AYARLARI
INATURALIST-STAFF = { $inaturalist } PERSONELİ
INATURALIST-STORE = INATURALIST MAĞAZASI
INATURALIST-TEAM = INATURALIST EKİBİ
iNaturalist-users-who-have-left-an-identification = Başka bir kullanıcının gözlemine tanımlama yapan iNaturalist kullanıcıları
iNaturalist-users-who-have-observed = Belirli bir taksonu belirli bir zaman ve yerde gözlemlemiş olan iNaturalist kullanıcıları
iNaturalists-apps-are-designed-and-developed-3 = iNaturalist'in uygulamaları iNaturalist ekibi tarafından tasarlanmakta, geliştirilmekte ve desteklenmektedir: Yaron Budowski, Amanda Bullington, Tony Iwane, Johannes Klein, Patrick Leary, Joanne Lin, Scott Loarie, Abhas Misraraj, Sylvain Morin, Carrie Seltzer, Alex Shepard, Thea Skaff, Angie Ta, Ken-ichi Ueda, Kirk van Gorkom, Jason Walthall ve Jane Weeden.
iNaturalists-vision-is-a-world = iNaturalist'in vizyonu, herkesin yabani organizmaları gözlemleme ve onlar hakkında bilgi paylaşma pratiği yoluyla biyolojik çeşitliliği anlayabildiği ve sürdürebildiği bir dünyadır.
Individual-encounters-with-organisms = Organizmalarla belirli bir zaman ve yerde, genellikle kanıtlarla bireysel karşılaşmalar
Internet-Connection-Required = İnternet Bağlantısı Gereklidir
Intl-number = { $val }
Introduced = Egzotik Tür
Introduced-to-place = { $place } konumunda egzotik tür
It-can-now-be-shared-for-use-in-research = Artık araştırmalarda kullanılmak üzere paylaşılabilir
It-may-take-up-to-an-hour-to-remove-content = İlişkili tüm içeriğin tamamen silinmesi bir saat kadar sürebilir
It-might-also-be = Ayrıca şu da olabilir:
It-might-be-one-of-these = Şunlardan biri olabilir:
January = Ocak
JOIN = KATIL
Join-a-global-community-for-nature = Doğa için küresel bir topluluğa katılın
JOIN-PROJECT = PROJEYE KATIL
JOIN-PROJECT--question = PROJEYE KATILMAK İSTER MİSİN?
JOINED = KATILDIĞIN
Joined-date = Katıldı: { $date }
JOINED-X-PROJECTS =
    { $count ->
        [one] { $count } PROJEYE KATILDI
       *[other] { $count } PROJEYE KATILDI
    }
JOURNAL-POSTS-WITHOUT-NUMBER =
    { $count ->
        [one] GÜNLÜK GÖNDERİSİ
       *[other] GÜNLÜK GÖNDERİSİ
    }
July = Temmuz
June = Haziran
Just-make-sure-the-organism-is-wild = Sadece organizmanın yabani olduğundan emin olun (evcil hayvan, hayvanat bahçesi hayvanı veya bahçe bitkisi değil)
Last-Active-date = Son Aktiflik: { $date }
Lat-Lon = { NUMBER($latitude, maximumFractionDigits: 6) }, { NUMBER($longitude, maximumFractionDigits: 6) }
Lat-Lon-Acc = Enlem: { NUMBER($latitude, maximumFractionDigits: 6) }, Boylam: { NUMBER($longitude, maximumFractionDigits: 6) }, Doğruluk: { $accuracy }
leading--identification = Öncü
Learn-from-people-who-verify-and-refine-your-identifications = Tanımlamalarınızı doğrulayan ve geliştiren kişilerden öğrenin.
Learn-More = Daha Çok Bilgi
LEARN-MORE-ABOUT-THIS-GROUP = BU GRUP HAKKINDA DAHA ÇOK BİLGİ EDİN
LEARN-MORE-ABOUT-THIS-SPECIES = BU TÜR HAKKINDA DAHA ÇOK BİLGİ EDİN
Least-Observed = Least Observed
LEAVE = AYRIL
LEAVE-PROJECT = PROJEDEN AYRIL
LEAVE-PROJECT--question = PROJEDEN AYRILMAK MI?
LEAVE-US-A-REVIEW = BİR YORUM YAP!
Lets-reset-your-password = Şifrenizi sıfırlayalım.
Loading-iNaturalists-AI-Camera = iNaturalist'in YZ Kamerası Yükleniyor
Loads-content-that-requires-an-Internet-connection = İnternet bağlantısı gerektiren içerikleri yükler
LOCATION = KONUM
Location = Konum
Location-accuracy-is-too-imprecise = Konum doğruluğu, tanımlayıcılara yardımcı olmak için çok kesin değil. Lütfen yakınlaştırın.
LOCATION-TOO-IMPRECISE = KONUM ÇOK BELİRSİZ
LOG-IN = OTURUM AÇ
LOG-IN-TO-INATURALIST = INATURALIST'E GİRİŞ YAP
Log-in-to-iNaturalist = iNaturalist'e giriş yap
LOG-OUT = ÇIKIŞ YAP
LOG-OUT--question = ÇIKIŞ YAPILSIN MI?
Lowest = En düşük
LOWEST-RANK = EN DÜŞÜK DÜZEY
MAP = HARİTA
Map-Area = Harita Alanı
March = Mart
Match-Screen = Eşleşme Ekranı
maverick--identification = Farklı Öneri
May = May
MEDIA = ORTAM
Media-Type = Medya Türü
MEMBERS-WITHOUT-NUMBER =
    { $count ->
        [one] ÜYE
       *[other] ÜYE
    }
Menu = Menü
Missing-Date = Eksik Tarih
MISSING-EVIDENCE = EKSİK KANIT
Monthly-Donor = Aylık Bağışçı
Months = Aylar
MONTHS = AYLAR
More = Daha Fazla
More-info = Daha fazla bilgi
MOST-FAVED = EN BEĞENİLENLER
Most-faved = En beğenilenler
Most-Observed-Default = Most Observed (Default)
MY-CONTENT--notifications = İÇERİĞİM
My-Observations = Gözlemlerim
My-Observations--bottom-tab = Ben
Native = Yerel
Native-to-place = { $place } konumunda yerel
Navigates-to-AI-camera = YZ kamerasına gider
Navigates-to-bulk-importer = Toplu içe aktarmaya gider
Navigates-to-camera = Kameraya gider
Navigates-to-explore = Keşfet'e gider
Navigates-to-log-in-screen = Giriş ekranına gider
Navigates-to-main-menu = Ana menüye gider
Navigates-to-notifications = Bildirimlere gider
Navigates-to-observation-details = Gözlem ayrıntıları ekranına gider
Navigates-to-observation-edit-screen = Gözlem düzenleme ekranına gider
Navigates-to-photo-importer = Fotoğraf içe aktarmaya gider
Navigates-to-previous-screen = Bir önceki ekrana gider
Navigates-to-project-details = Proje ayrıntılarına gider
Navigates-to-sound-recorder = Ses kaydediciye gider
Navigates-to-suggest-identification = Tanımlama önermeye gider
Navigates-to-taxon-details = Takson ayrıntılarına gider
Navigates-to-user-profile = Kullanıcı profiline gider
Navigates-to-your-observations = Gözlemlerine gider
NEARBY = YAKINDAKİ
Nearby = Yakında
Needs-ID--quality-grade = Tanımlama Gerekli
New-Observation = Yeni Gözlem
Newest-to-oldest = En yeniden en eskiye
Next-observation = Sonraki gözlem
Next-slide = Sonraki
No-Camera-Available = Kullanılabilir Kamera Yok
No-email-app-installed = Yüklü e-posta uygulaması yok
No-email-app-installed-body = E-posta göndermenin başka bir yolu varsa, adres: { $address }
No-email-app-installed-body-check-other = E-postanızı bir web tarayıcısında veya başka bir cihazda kontrol etmeyi deneyin.
No-Location = Konum Yok
No-Media = Ortam Yok
No-model-found = Model bulunamadı
No-Notifications-Found = Bildiriminiz yok! Kendi gözlemlerinizi oluşturarak başlayın.
No-projects-match-that-search = Bu aramayla eşleşen proje yok
No-results-found-for-that-search = Bu arama için sonuç bulunamadı.
No-results-found-try-different-search = Sonuç bulunamadı. Farklı bir arama yapmayı deneyin veya filtrelerinizi ayarlayın.
no-rights-reserved-cc0 = hiçbir hakkı saklı değildir (CC0)
none--accuracy = hiçbiri
NONE--ranks = HİÇBİRİ
NOT-BY-ME = BENİM TARAFIMDAN DEĞİL
Not-enough-space-left-on-device = Aygıtta yeterli alan yok
Not-enough-space-left-on-device-try-again = Bunu yapmak için cihazınızda yeterli depolama alanı kalmadı. Lütfen biraz yer açın ve tekrar deneyin.
NOTES = NOTLAR
Notes = Notlar
NOTIFICATIONS = BİLDİRİMLER
Notifications--bottom-tab = Etkinlik
notifications-user-added-comment-to-observation-by-you = <0>{ $userName }</0> senin gözlemine bir yorum ekledi
notifications-user-added-identification-to-observation-by-you = <0>{ $userName }</0> senin gözlemine bir tanımlama ekledi
notifications-user1-added-comment-to-observation-by-user2 = <0>{ $user1 }</0>, { $user2 } tarafından yapılan gözleme bir yorum ekledi
notifications-user1-added-identification-to-observation-by-user2 = <0>{ $user1 }</0>, { $user2 } tarafından yapılan gözleme bir tanımlama ekledi
November = Kasım
Obervations-must-be-manually-added = Gözlemler, ya yükleme aşamasında ya da gözlem iNaturalist'te paylaşıldıktan sonra geleneksel bir projeye manuel olarak eklenmelidir. Bir kullanıcının gözlemlerini ekleyebilmesi için geleneksel bir projeye de katılması gerekir.
Obscured = Gizlenmiş
Observation = Gözlem
Observation-Attribution = Gözlem: © { $userName } · { $restrictions }
Observation-Copyright = Gözlem Telif Hakkı: © { $userName } · { $restrictions }
Observation-has-no-photos-and-no-sounds = Bu gözlemde fotoğraf ve ses yoktur.
Observation-location-obscured-randomized-point = Bu gözlemin konumu gizlenmiştir. Gizleme çokgeni içinde rastgele bir nokta görüyorsunuz.
Observation-location-obscured-you-can-see-your-own = Bu gözlemin konumu gizlenmiştir. Kendi gözlemlerinizin konumunu her zaman görebilirsiniz.
Observation-location-obscured-you-have-permission = Bu gözlemin konumu gizlenmiştir. Bu konumu görmek için izniniz var.
Observation-options = Gözlem seçenekleri
OBSERVATION-WAS-DELETED = GÖZLEM SİLİNDİ
Observation-with-no-evidence = Kanıtsız gözlem
Observations = Gözlemler
Observations-need-location-date--warning = iNaturalist gözlemlerinin bilim insanlarına faydalı olabilmesi için bir konum ve tarihe ihtiyacı vardır. Lütfen yüklemeden önce gözlemleri bu simge ile kontrol edin.
Observations-View = Gözlem Görünümü
OBSERVATIONS-WITHOUT-NUMBER =
    { $count ->
        [one] GÖZLEM
       *[other] GÖZLEM
    }
OBSERVE-ORGANISMS = ORGANİZMALARI GÖZLEMLE
OBSERVED-AT--label = GÖZLEM TARİHİ:
OBSERVED-IN--label = GÖZLEM YERİ:
Observers = Gözlemciler
Observers-View = Gözlemci Görünümü
October = Ekim
Offline-DQA-description = VND doğru olmayabilir. İnternet bağlantınızı kontrol edin ve tekrar deneyin.
Offline-suggestions-may-differ-from-online = Çevrim dışı öneriler çevrim içi önerilerden farklı olabilir ve takson görüntüleri ve yaygın adlar yüklenmeyebilir.
OK = TAMAM
Oldest-to-newest = En eskiden en yeniye
Once-you-create-and-upload-observations = Gözlemleri oluşturup yükledikten sonra, topluluğumuzun diğer üyeleri gözlemlerinizin araştırma sınıfına ulaşmasına yardımcı olmak için tanımlama ekleyebilir.
Open = Açık
OPEN-EMAIL = E-POSTAYI AÇ
Open-menu = Menüyü aç.
OPEN-SETTINGS = AYARLARI AÇ
Opens-add-comment-form = Yorum ekleme formunu açar.
Opens-AI-camera = YZ kamerasını açar.
Opens-edit-comment-form = Yorum düzenleme formunu açar.
Opens-location-permission-prompt = Konum izni istemini açar
OR-SIGN-IN-WITH = VEYA ŞUNUNLA OTURUM AÇIN
Or-you-can-try-to-get-a-clearer-photo-by-zooming-in-getting-closer = Ayrıca, yakınlaştırarak, yaklaşarak veya farklı bir açı deneyerek daha net bir fotoğraf elde etmeyi deneyebilirsiniz.
Organism-is-captive = Organizma kısıtlanmış
Organisms-that-are-identified-to-species = Tür düzeyinde veya altında tanımlanan organizmalar
OTHER-DATA = DİĞER VERİLER
OTHER-SUGGESTIONS = DİĞER ÖNERİLER
OTHERS--notifications = DİĞER
PASSWORD = ŞİFRE
PEOPLE--title = KİŞİLER
Photo-importer = Fotoğraf içe aktarıcı
PHOTO-LICENSING = FOTOĞRAF LİSANSLAMA
Photos = Fotoğraflar
Photos-you-take-will-appear-here = Çektiğiniz fotoğraflar burada görünecek
Please-allow-Camera-Access = Lütfen Kamera erişimine izin verin
Please-allow-Location-Access = Lütfen Konum erişimine izin verin
Please-allow-Microphone-Access = Lütfen Mikrofon erişimine izin verin
Please-choose-a-different-password = Lütfen farklı bir şifre seçin.
Please-Grant-Permission = Lütfen İzin Verin
PLEASE-LOG-IN = LÜTFEN GİRİŞ YAPIN
Please-make-sure-your-password-is-at-least-6-characters = Lütfen şifrenizin en az 6 karakterden oluştuğundan emin olun.
Please-try-again-when-you-are-connected-to-the-internet = Lütfen internete bağlı olduğunuzda tekrar deneyin.
Please-try-again-when-you-are-online = Lütfen çevrim içi olduğunuzda tekrar deneyin!
Point-the-camera-at-an-animal-plant-or-fungus = Kamerayı bir hayvana, bitkiye veya mantara yönelt
POTENTIAL-DISAGREEMENT = OLASI UYUŞMAZLIK
Potential-disagreement-description = <0>Kanıt bunun </0><1></1><0> olduğunu doğrulamak için yeterli mi?<0>
Potential-disagreement-disagree = <0>Hayır ama bu bir </0><1></1> üyesi
Potential-disagreement-unsure = <0>Bilmiyorum ama </0><1></1> olduğuna eminim
Press-and-hold-to-view-more-options = Daha çok seçenek görüntülemek için basılı tutun
Previous-observation = Önceki gözlem
Previous-slide = Önceki
Privacy-Policy = Gizlilik Politikası
PRIVACY-POLICY = GİZLİLİK POLİTİKASI
Private = Özel
PROJECT = PROJE
Project-Members-Only = Yalnızca Proje Üyeleri
PROJECT-REQUIREMENTS = PROJE GEREKLİLİKLERİ
project-start-time-datetime = Başlangıç zamanı: { $datetime }
PROJECTS = PROJELER
Projects = Projeler
PROJECTS-X = ({ $projectCount }) PROJE
Pull-to-refresh-and-sync-observations = Gözlemleri yenilemek ve eşitlemek için çekin
Pull-to-refresh-notifications = Bildirimleri yenilemek için çekin
QUALITY-GRADE = NİTELİK SINIFI
Quality-Grade = Kalite Derecesi
Quality-Grade-Casual--label = Nitelik Sınıfı: Sıradan
Quality-Grade-Needs-ID--label = Nitelik Sınıfı: Tanımlama Gerekli
Quality-Grade-Research--label = Nitelik Sınıfı: Araştırma
Ranks-CLASS = SINIF
Ranks-Class = Sınıf
Ranks-COMPLEX = KOMPLEKS
Ranks-Complex = Kompleks
Ranks-EPIFAMILY = EPİ FAMİLYA
Ranks-Epifamily = Epi Familya
Ranks-FAMILY = FAMİLYA
Ranks-Family = Familya
Ranks-FORM = FORM
Ranks-Form = Form
Ranks-GENUS = CİNS
Ranks-Genus = Cins
Ranks-GENUSHYBRID = MELEZ CİNS
Ranks-Genushybrid = Melez Cins
Ranks-HYBRID = MELEZ
Ranks-Hybrid = Melez
Ranks-INFRACLASS = İNFRA SINIF
Ranks-Infraclass = İnfra Sınıf
Ranks-INFRAHYBRID = İNFRA MELEZ
Ranks-Infrahybrid = İnfra Melez
Ranks-INFRAORDER = İNFRA TAKIM
Ranks-Infraorder = İnfra Takım
Ranks-KINGDOM = ÂLEM
Ranks-Kingdom = Alem
Ranks-ORDER = TAKIM
Ranks-Order = Sıralama
Ranks-PARVORDER = GEÇİŞ TAKIMI
Ranks-Parvorder = Geçiş Takımı
Ranks-PHYLUM = ŞUBE
Ranks-Phylum = Şube
Ranks-SECTION = SEKSİYON
Ranks-Section = Seksiyon
Ranks-SPECIES = TÜR
Ranks-Species = Türler
Ranks-Statefmatter = İçeriğin durumu
Ranks-STATEOFMATTER = KÖK TAKSON
Ranks-SUBCLASS = ALT SINIF
Ranks-Subclass = Alt Sınıf
Ranks-SUBFAMILY = ALT FAMİLYA
Ranks-Subfamily = Alt Familya
Ranks-SUBGENUS = ALT CİNS
Ranks-Subgenus = Alt Cins
Ranks-Subkingdom = Alt Alem
Ranks-SUBORDER = ALT TAKIM
Ranks-Suborder = Alt Takım
Ranks-SUBPHYLUM = ALT ŞUBE
Ranks-Subphylum = Alt Şube
Ranks-SUBSECTION = ALT SEKSİYON
Ranks-Subsection = Alt Seksiyon
Ranks-SUBSPECIES = ALT TÜR
Ranks-Subspecies = Alt Tür
Ranks-SUBTERCLASS = SUBTERCLASS
Ranks-Subterclass = Enaltsınıf
Ranks-SUBTRIBE = ALT OYMAK
Ranks-Subtribe = Alt Oymak
Ranks-SUPERCLASS = ÜST SINIF
Ranks-Superclass = Üst Sınıf
Ranks-SUPERFAMILY = ÜST FAMİLYA
Ranks-Superfamily = Üst Familya
Ranks-SUPERORDER = ÜST TAKIM
Ranks-Superorder = Üst Takım
Ranks-SUPERTRIBE = ÜST OYMAK
Ranks-Supertribe = Üst Oymak
Ranks-TRIBE = OYMAK
Ranks-Tribe = Oymak
Ranks-VARIETY = VARYETE
Ranks-Variety = Varyasyon
Ranks-ZOOSECTION = ZOO SEKSİYON
Ranks-Zoosection = Zoobölüm
Ranks-ZOOSUBSECTION = ZOO ALT SEKSİYON
Ranks-Zoosubsection = Zooaltbölüm
Read-more-on-Wikipedia = Vikipedi'den daha fazlasını okuyun
Record-a-sound = Ses kaydet
Record-animal-sounds = Hayvan seslerini kaydet
RECORD-NEW-SOUND = YENİ SES KAYDET
RECORD-SOUND = SES KAYDET
Record-verb = Kayıt
Recording-sound = Ses kaydediliyor
Recording-stopped-Tap-to-play-the-current-recording = Kayıt durdu. Geçerli kaydı oynatmak için dokunun.
REDO-SEARCH-IN-MAP-AREA = HARİTA ALANINDA YENİDEN ARAMA YAP
Remove-agreement = Uyuşmayı kaldır
Remove-disagreement = Uyumsuzluğu kaldır
Remove-favorite = Favoriyi kaldır
Remove-identification = Tanımlamayı kaldır
Remove-Photos = Fotoğrafları Kaldır
Remove-project-filter = Proje filtresini kaldır
Remove-taxon-filter = Takson filtresini kaldır
Remove-user-filter = Kullanıcı filtresini kaldır
Removes-this-observations-taxon = Bu gözlemin taksonunu kaldırır
Removes-your-vote-of-agreement = Uyuşma oyunuzu kaldırır
Removes-your-vote-of-disagreement = Uyuşmazlık oyunuzu kaldırır
Research-Grade--quality-grade = Araştırma Sınıfı
RESEARCH-GRADE--quality-grade = ARAŞTIRMA SINIFI
Research-Grade-Status = Araştırma Sınıfı Statüsü
RESET-PASSWORD = ŞİFREYİ SIFIRLA
RESET-RECORDING = KAYDI SIFIRLA
RESET-SEARCH = ARAMAYI SIFIRLA
RESET-SOUND-header = SES SIFIRLANSIN MI?
Reset-verb = Sıfırla
RESTART-APP = UYGULAMAYI YENİDEN BAŞLAT
Restore = Geri yükle
Reveal = Göster
REVIEW-INATURALIST = INATURALIST'İ DEĞERLENDİR
REVIEWED = İNCELENDİ
Reviewed-observations-only = Sadece incelenmiş gözlemler
Satellite--map-type = Uydu
SAVE = KAYDET
SAVE-ALL = TÜMÜNÜ KAYDET
Save-all-observations = Tüm gözlemleri kaydet
SAVE-CHANGES = DEĞİŞİKLİKLERİ KAYDET
SAVE-FOR-LATER = DAHA SONRASI İÇİN KAYDET
SAVE-LOCATION = KONUMU KAYDET
SAVE-PHOTOS = FOTOĞRAFLARI KAYDET
Save-photos-to-your-library = Fotoğrafları kütüphanene kaydet
Saved-Observation = Gözlem kaydedildi, yükleme kuyruğunda
Scientific-Name = Bilimsel Ad
Scientific-Name-Common-Name = Bilimsel Ad (Yaygın Ad)
SEARCH = ARAMA
Search = Arama Yap
Search-for-a-project = Bir proje ara
SEARCH-FOR-A-TAXON = BİR TAKSON ARA
Search-for-a-taxon = Bir takson ara
SEARCH-LOCATION = KONUM ARA
SEARCH-PROJECTS = PROJE ARA
Search-suggestions-with-location = Konum ile arama önerileri
Search-suggestions-without-location = Konumsuz arama önerileri
SEARCH-TAXA = TAKSON ARA
SEARCH-USERS = KULLANICI ARA
See-observations-by-this-user-in-Explore = Keşfet'te bu kullanıcı tarafından yapılan gözlemlere bak
See-observations-of-this-taxon-in-explore = Keşfet'te bu taksonun gözlemlerine bak
See-project-members = Proje üyelerine bak
See-species-observed-by-this-user-in-Explore = Keşfet'te bu kullanıcı tarafından gözlemlenen türleri gör
Select-a-date-and-time-for-observation = Gözlem için bir tarih ve saat seçin
Select-captive-or-cultivated-status = Kısıtlanmış veya ekili statüsünü seç
Select-geoprivacy-status = Coğrafi Gizlilik statüsünü seç
Select-or-drag-media = Ortam seçin veya sürükleyin
Select-photo = Fotoğraf seç
SELECT-THIS-TAXON = BU TAKSONU SEÇ
Select-user = Kullanıcı seç
Selects-iconic-taxon-X-for-identification = Tanımlama için ikonik takson { $iconicTaxon } seçer
Separate-Photos = Ayrı Fotoğraflar
September = Eylül
SETTINGS = AYARLAR
Share = Paylaş
SHARE-DEBUG-LOGS = HATA AYIKLAMA GÜNLÜKLERİNİ PAYLAŞ
Share-location = Konum Paylaş
Share-map = Haritayı paylaş
Share-your-observation-where-it-can-help-scientists = Dünyanın dört bir yanındaki bilim insanlarının biyoçeşitliliği daha iyi anlamasına yardımcı olabileceği gözleminizi paylaşın.
SHOP-INATURALIST-MERCH = INATURALIST ÜRÜNLERİNİ SATIN AL
Show-observation-options = Gözlem seçeneklerini göster.
Showing-offline-search-results--taxa = Çevrim dışı arama sonuçları gösteriliyor. Daha fazla tür aramak için internete bağlıyken tekrar deneyin.
Shows-identification-suggestions = Tanımlama önerilerini gösterir
Shows-observation-creation-options = Gözlem oluşturma seçeneklerini gösterir.
Sign-in-with-Apple = Apple ile giriş yap
Sign-in-with-Apple-Failed = Apple ile Giriş Yapılamadı
Sign-in-with-Google = Google ile giriş yap
Sign-in-with-Google-Failed = Google ile Giriş Yapılamadı
Skip-for-now = Şimdilik atla
Something-went-wrong = Bir şeyler ters gitti.
Sorry-this-observation-was-deleted = Üzgünüz, bu gözlem silindi
Sorry-we-dont-know-how-to-open-that-URL = Üzgünüz, bu URL'yi nasıl açacağımızı bilmiyoruz: { $url }
SORT-BY = SIRALAMA ÖLÇÜTÜ
Sort-by = Sıralama ölçütü
SORT-SPECIES = SORT SPECIES
sound-playback-separator = /
Sound-recorder = Ses kaydedici
sound-recorder-help-A-recording-of = Tanımlayıcılara yardımcı olmak için 5-15 saniyelik bir kayıt en iyisidir.
sound-recorder-help-Get-as-close-as-you-can = Organizmayı kaydetmek için güvenli bir şekilde yaklaşabildiğiniz kadar yaklaşın.
sound-recorder-help-Get-closer = Yaklaşın
sound-recorder-help-Keep-it-short = Kısa tutun
sound-recorder-help-Make-sure = Kendi hareketinizin sesinin organizmanın sesini örtmediğinden emin olun.
sound-recorder-help-One-organism = Bir organizma
sound-recorder-help-Stop-moving = Hareket etmeyin
sound-recorder-help-Try-to-isolate = Tek bir organizmanın sesini ayrıştırmaya çalışın. Yapamazsanız, hangi organizmayı kaydettiğinizi not ettiğinizden emin olun.
Sounds = Sesler
Source-List = <0>(Kaynak Listesi: </0><1>{ $source }</1><0>)</0>
Species = Türler
Species-View = Tür Görünümü
Species-with-the-least-observations-appear-first = Species with the least observations appear first
Species-with-the-most-observations-appear-first = Species with the most observations appear first
SPECIES-WITHOUT-NUMBER =
    { $count ->
        [one] TÜR
       *[other] TÜR
    }
Standard--map-type = Standart
Start-must-be-before-end = Başlangıç tarihi bitiş tarihinden önce olmalıdır.
Start-upload = Yüklemeye başla
Starts-recording-sound = Ses kaydetmeye başlar
Stay-on-this-screen = Konumunuz yüklenirken bu ekranda kalın.
Still-need-help = Hala yardıma mı ihtiyacınız var? Buradan bir destek talebinde bulunabilirsiniz.
Stop-upload = Yüklemeyi durdur
Stop-verb = Dur
Stops-recording-sound = Ses kaydını durdurur
SUBMIT = GÖNDER
SUBMIT-ID-SUGGESTION = TANIMLAMA ÖNERİSİNİ GÖNDER
SUGGEST-ID = TANIMLAMA ÖNER
supporting--identification = Destekleyici
Switches-to-tab = { $tab } sekmesine geçer.
Sync-observations = Gözlemleri eşitle
Syncing = Senkronize Ediliyor...
Take-photo = Fotoğraf çek
Take-photos = Fotoğraf çek
Taxa = Taksonlar
TAXON = TAKSON
TAXON-NAMES-DISPLAY = TAKSON ADI GÖRÜNÜMÜ
TAXONOMIC-RANKS = TAKSONOMİK DÜZEY
TAXONOMY-header = TAKSONOMİ
TEAM = EKİP
Terms-of-Use = Kullanım Koşulları
TERMS-OF-USE = KULLANIM KOŞULLARI
Thank-you-for-sharing-your-feedback = Gelişmemize yardımcı olmak için geri bildiriminizi paylaştığınız için teşekkür ederiz!
Thanks-for-using-any-suggestions = Bu uygulamayı kullandığınız için teşekkürler! Geliştiriciler için herhangi bir öneriniz var mı?
That-email-is-already-associated-with-an-account = Bu e-posta zaten bir hesapla ilişkilendirilmiştir.
That-user-profile-doesnt-exist = Bu kullanıcı profili mevcut değil
That-username-is-unavailable = Bu kullanıcı adı kullanılamıyor
The-AI-is-not-confident-It-may-be-one-of-the-IDs-below = YZ emin değil. Aşağıdaki tanımlamalardan biri olabilir.
The-AI-is-not-confident-Upload-to-ask-the-community = YZ emin değil. Topluluğa sormak için yükleyin.
The-exact-location-will-be-hidden = Kesin konum kamuya açık olarak gizlenecek ve bunun yerine daha geniş bir alana genelleştirilecektir. (Tehdit altındaki ve nesli tükenmekte olan türler otomatik olarak gizlenir).
The-iNaturalist-community-will-help-verify-and-refine-identifications = iNaturalist topluluğu, bilim ve koruma için Araştırma Sınıfı veriler oluşturmak üzere gözlemlerinizdeki tanımlamaları doğrulamaya ve iyileştirmeye yardımcı olacaktır.
The-iNaturalist-Network = iNaturalist ağı, küresel iNaturalist topluluğuna tamamen bağlı olan yerelleştirilmiş web sitelerinden oluşan bir koleksiyondur. Ağ siteleri, yerel kullanımı teşvik eden ve yerel biyolojik çeşitliliğe fayda sağlamak için iNaturalist'ten elde edilen verilerin kullanımını kolaylaştıran yerel kurumlar tarafından desteklenmektedir.
The-location-will-not-be-visible-to-others = Konum başkaları tarafından görülemeyecektir, bu da gözlemin tespit edilmesini olanaksız hale getirebilir
The-models-that-suggest-species = Görsel benzerlik ve konuma dayalı olarak tür öneren modeller Sara Beery, Tom Brooks, Elijah Cole, Christian Lange, Oisin Mac Aodha, Pietro Perona ve Grant Van Horn ile yapılan iş birliği sayesinde ortaya çıkmıştır.
There-was-an-error-that-might-be-fixed-by-logging-in-again = Tekrar giriş yaparak düzeltilebilecek bir hata oluştu.
This-is-a-wild-organism = Bu yabani bir organizmadır ve insanlar tarafından bu konuma getirilmemiştir.
This-is-how-taxon-names-will-be-displayed = Tüm takson adları iNaturalist'te size bu şekilde gösterilecektir:
This-is-your-identification-other-people-may-help-confirm-it = Bu senin tanımlaman. Diğer insanlar bunu doğrulamaya yardımcı olabilir!
This-may-take-a-few-seconds = Bu işlem birkaç saniye sürebilir.
This-observation-has-no-comments-or-identifications-yet = Bu gözlemle ilgili henüz bir yorum ya da tanımlama yapılmamıştır.
This-observation-has-not-met-the-conditions-required-to-meet-Research-Grade = Bu gözlem, Araştırma Sınıfı statüsü için gerekli koşulları karşılamamıştır
This-observation-is-not-eligible-for-research-grade-status = Bu gözlem araştırma sınıfı statüsü için uygun değildir. Aşağıdaki Veri Nitelik Değerlendirmesi'nden daha çok bilgi edinin.
This-observation-is-research-grade-and-can-be-used-by-scientists = Bu gözlem araştırma sınıfıdır ve bilim insanları tarafından kullanılabilir!
This-observation-needs-more-identifications = Bu gözlemin Araştırma Sınıfı statüsüne ulaşması için daha çok tanımlamaya ihtiyacı var
This-observation-needs-more-identifications-to-become-research-grade = Bu gözlemin araştırma sınıfı statüsü kazanması için daha çok tanımlamaya ihtiyacı var.
This-observer-has-opted-out-of-the-Community-Taxon = Bu gözlemci Topluluk Taksonu'nundan vazgeçti
This-organism-was-placed-by-humans = Bu organizma bu konuma insanlar tarafından yerleştirilmiştir. Bu durum bahçe bitkileri, evcil hayvanlar ve hayvanat bahçesi hayvanları gibi şeyler için geçerlidir.
This-user-has-no-followers = Bu kullanıcının takipçisi bulunmamaktadır.
This-user-has-not-joined-any-projects = Bu kullanıcı henüz hiçbir projeye katılmadı.
This-user-is-not-following-anyone = Bu kullanıcı hiç kimseyi takip etmiyor.
To-sync-your-observations-to-iNaturalist = Gözlemlerinizi iNaturalist ile eşitlemek için lütfen giriş yapın.
To-view-nearby-organisms-please-enable-location = Yakındaki organizmaları görüntülemek için lütfen konumu etkinleştir.
To-view-nearby-projects-please-enable-location = Yakındaki projeleri görüntülemek için lütfen konumu etkinleştir.
Toggle-map-type = Harita türünü değiştir
TOP-ID-SUGGESTION = EN İYİ TANIMLAMA ÖNERİSİ
Traditional-Project = Geleneksel Proje
Umbrella-Project = Şemsiye Projesi
UNFOLLOW = TAKİBİ BIRAK
UNFOLLOW-USER = TAKİP BIRAKILSIN MI?
Unknown--rank = Bilinmeyen
Unknown--taxon = Bilinmeyen
Unknown--user = Bilinmeyen
Unknown-error = Bilinmeyen hata
Unknown-organism = Bilinmeyen organizma
Unreviewed-observations-only = Sadece incelenmemiş gözlemler
Upload-Complete = Yükleme Tamamlandı
Upload-in-progress = Yükleme devam ediyor
UPLOAD-NOW = ŞİMDİ YÜKLE
Upload-photos = Fotoğraf yükle
Upload-Progress = Yükleme yüzde { $uploadProgress } tamamlandı
UPLOAD-TO-INATURALIST = INATURALIST'E YÜKLE
Upload-x-observations =
    { $count ->
        [one] 1 gözlem
       *[other] { $count } gözlem
    } yükle
Upload-your-observations-to-contribute-data-to-help-save-species = Türlerin kurtarılmasına yardımcı olacak verilere katkıda bulunmak için gözlemlerinizi yükleyin.
Uploaded-via-application = Şuradan yüklendi: { $application }
Uploading-x-of-y = Yükleniyor { $currentUploadCount } / { $total }
Uploading-x-of-y-observations =
    { $total ->
        [one] { $currentUploadCount } gözlem yüklenyor
       *[other] { $currentUploadCount } / { $total } gözlem yükleniyor
    }
Use-iNaturalist-to-identify-any-living-thing = Herhangi bir canlıyı tanımlamak için iNaturalist'i kullanın
USE-LOCATION = KONUMU KULLAN
Use-the-devices-other-camera = Aygıtın diğer kamerasını kullan.
Use-the-iNaturalist-camera-to-see-real-time-identifications-and-take-photos = Gerçek zamanlı tanımlamaları görmek ve fotoğraf çekmek için iNaturalist kamerasını kullanın!
Use-your-devices-microphone-to-record-animal-sounds-and-share-them = Hayvan seslerini kaydetmek için aygıtınızın mikrofonunu kullanın ve tanımlamalar elde etmek ve bilime katkıda bulunmak için bunları paylaşın!
USER = KULLANICI
User = Kullanıcı { $userHandle }
USERNAME-OR-EMAIL = KULLANICI ADI VEYA E-POSTA
Users = Kullanıcılar
Using-location = Konumu kullanma
Verified-IDs-are-used-for-science-and-conservation = Doğrulanmış tanımlamalar bilim ve koruma için kullanılır
Version-app-build = Sürüm { $appVersion } ({ $buildVersion })
VIEW-ALL-X-PLACES = { $count } YERİN TÜMÜNÜ GÖRÜNTÜLE
VIEW-ALL-X-PROJECTS = { $count } PROJENİN TÜMÜNÜ GÖRÜNTÜLE
VIEW-ALL-X-TAXA = { $count } TAKSONUN TÜMÜNÜ GÖRÜNTÜLE
VIEW-ALL-X-USERS = { $count } KULLANICININ TÜMÜNÜ GÖRÜNTÜLE
VIEW-CHILDREN-TAXA = ALT TAKSONLARI GÖRÜNTÜLE
VIEW-DATA-QUALITY-ASSESSMENT = VERİ NİTELİK DEĞERLENDİRMESİNİ GÖRÜNTÜLE
VIEW-EDUCATORS-GUIDE = EĞİTMEN REHBERİNİ GÖRÜNTÜLE
VIEW-FOLLOWERS = TAKİPÇİLERİ GÖRÜNTÜLE
VIEW-FOLLOWING = TAKİP EDİLENLERİ GÖRÜNTÜLE
View-in-browser = Tarayıcıda görüntüle
VIEW-IN-EXPLORE = KEŞFET'TE GÖRÜNTÜLE
VIEW-INATURALIST-HELP = INATURALIST YARDIMINI GÖRÜNTÜLE
View-photo = Fotoğraf görüntüle
View-photo-licensing-info = Fotoğraf lisanslama bilgilerini görüntüle
VIEW-PROJECT-REQUIREMENTS = PROJE GEREKLİLİKLERİNİ GÖRÜNTÜLE
VIEW-PROJECTS = PROJELERİ GÖRÜNTÜLE
View-suggestions = Önerileri görüntüle
Watch-your-notifications-for-identifications = Tanımlamalar için bildirimlerinize bakın!
We-are-not-confident-enough-to-make-a-top-ID-suggestion = En iyi tanımlama önerisinde bulunacak kadar emin değiliz ancak işte diğer bazı öneriler:
Welcome-back = Tekrar hoş geldin!
WHAT-IS-INATURALIST = INATURALIST NEDİR?
Whats-more-by-recording = Dahası, gözlemlerinizi kaydedip paylaşarak, doğayı daha iyi anlamak ve korumak için çalışan bilim insanları için araştırma sınıfında veriler oluşturacaksınız. Eğer açık havada bulduklarınızı kaydetmeyi ya da sadece yaşam hakkında bir şeyler öğrenmeyi seviyorsanız, bize katılın!
When-tapping-the-green-observation-button = Yeşil gözlem düğmesine dokunduğunda, şu açılsın:
WIKIPEDIA = VİKİPEDİ
Wild = Yabani
WILD-STATUS = YABANİ STATÜ
Withdraw = Geri Al
WITHDRAW-ID = TANIMLAMAYI GERİ ÇEK
WITHDRAW-ID-QUESTION = TANIMLAMA GERİ ÇEKİLSİN Mİ?
Withdraws-identification = Tanımlamayı geri çeker
Worldwide = Dünya çapında
WORLDWIDE = DÜNYA GENELİ
Would-you-like-to-discard-your-current-recording-and-start-over = Mevcut kaydınızı iptal edip baştan başlamak ister misiniz?
Would-you-like-to-suggest-the-following-identification = Aşağıdaki tanımlamayı önermek ister misiniz?
x-comments =
    { $count ->
        [one] { $count } yorum
       *[other] { $count } yorum
    }
x-failed =
    { $count ->
        [one] { $count } başarısız
       *[other] { $count } başarısız
    }
X-FOLLOWERS =
    { $count ->
        [one] { $count } TAKİPÇİ
       *[other] { $count } TAKİPÇİ
    }
X-Identifications =
    { $count ->
        [one] { $count } Tanımlama
       *[other] { $count } Tanımlama
    }
x-identifications =
    { $count ->
        [one] { $count } tanımlama
       *[other] { $count } tanımlama
    }
X-Identifiers =
    { $count ->
        [one] { $count } Tanımlayıcı
       *[other] { $count } Tanımlayıcı
    }
X-MEMBERS =
    { $count ->
        [one] { $count } ÜYE
       *[other] { $count } ÜYE
    }
X-Observations =
    { $count ->
        [one] 1 Gözlem
       *[other] { $count } Gözlem
    }
X-OBSERVATIONS--below-number =
    { $count ->
        [one] GÖZLEM
       *[other] GÖZLEM
    }
X-observations-deleted =
    { $count ->
        [one] 1 gözlem silindi
       *[other] { $count } gözlem silindi
    }
X-observations-uploaded =
    { $count ->
        [one] 1 gözlem yüklendi
       *[other] { $count } gözlem yüklendi
    }
X-Observers =
    { $count ->
        [one] { $count } Gözlemci
       *[other] { $count } Gözlemci
    }
X-of-Y =
    { $x ->
        [one] 1
       *[other] { $x }
    } { $y ->
        [one] / { $y }
       *[other] / { $y }
    }
X-percent = %{ $count }
X-percent-confidence = %{ $count } güvenilirlik
X-PHOTOS =
    { $photoCount ->
        [one] 1 FOTOĞRAF
       *[other] { $photoCount } FOTOĞRAF
    }
X-PHOTOS-X-OBSERVATIONS =
    { $photoCount ->
        [one] 1 FOTOĞRAF
       *[other] { $photoCount } FOTOĞRAF
    }, { $observationCount ->
        [one] 1 GÖZLEM
       *[other] { $observationCount } GÖZLEM
    }
X-PHOTOS-Y-SOUNDS =
    { $photoCount ->
        [one] 1 FOTOĞRAF
       *[other] { $photoCount } FOTOĞRAF
    }, { $soundCount ->
        [one] 1 SES
       *[other] { $soundCount } SES
    }
X-PROJECTS = { $projectCount } PROJE
x-saved =
    { $count ->
        [one] { $count } tanesi kaydedildi
       *[other] { $count } tanesi kaydedildi
    }
X-SOUNDS =
    { $count ->
        [one] 1 SES
       *[other] { $count } SES
    }
X-Species =
    { $count ->
        [one] { $count } Tür
       *[other] { $count } Tür
    }
X-SPECIES--below-number =
    { $count ->
        [one] TÜR
       *[other] TÜR
    }
x-uploaded =
    { $count ->
        [one] { $count } tane yüklendi
       *[other] { $count } tane yüklendi
    }
x-uploading =
    { $count ->
        [one] { $count } tane yükleniyor
       *[other] { $count } tane yükleniyor
    }
x-uploads-failed =
    { $count ->
        [one] { $count } yükleme başarısız
       *[other] { $count } yükleme başarısız
    }
You-are-offline = Çevrim dışısınız
You-are-offline-Tap-to-reload = Çevrim dışısınız. Yeniden yüklemek için dokunun.
You-are-offline-Tap-to-try-again = Çevrim dışısınız. Tekrar denemek için dokunun.
You-can-add-up-to-20-media = Gözlem başına en çok 20 fotoğraf ve 20 ses ekleyebilirsin.
You-can-also-check-out-merchandise = Ayrıca iNaturalist ve Seek ürünlerine aşağıdaki mağazamızdan göz atabilirsiniz!
You-can-click-join-on-the-project-page = Proje sayfasındaki “katıl” butonuna tıklayabilirsiniz.
You-can-find-answers-on-our-help-page = Cevapları yardım sayfamızda bulabilirsiniz.
You-can-now-upload-your-observations-to-iNaturalist-and-contribute = Artık gözlemlerinizi iNaturalist'e yükleyebilir ve küresel biyoçeşitlilik araştırmalarına katkıda bulunabilirsiniz.
You-can-only-add-20-photos-per-observation = Gözlem başına yalnızca 20 fotoğraf ekleyebilirsiniz
You-can-still-share-the-file = Dosyayı yine de başka bir uygulama ile paylaşabilirsiniz. E-posta ile gönderebiliyorsanız, lütfen { $email } adresine gönderin
You-can-upload-this-observation-to-our-community = Gerçek bir kişiden tanımlama tespiti almak için bu gözlemi topluluğumuza yükleyebilir ve YZ'nin gelecekte tanımlama tespitlerini geliştirmesine yardımcı olabilirsiniz
You-changed-filters-will-be-discarded = Filtreleri değiştirdiniz ancak bunlar keşif arama sonuçlarınıza uygulanmadı.
You-have-opted-out-of-the-Community-Taxon = Topluluk Taksonundan vazgeçmeyi tercih ettiniz
You-havent-joined-any-projects-yet = Henüz hiçbir projeye katılmadın!
You-havent-observed-any-species-yet = Henüz hiçbir türü gözlemlemedin.
You-likely-observed-a-species-in-this-group = Muhtemelen bu gruptaki bir türü gözlemlediniz
You-likely-observed-this-species = Muhtemelen bu türü gözlemlediniz
You-may-have-observed-a-species-in-this-group = Bu gruptaki bir türü gözlemlemiş olabilirsiniz
You-may-have-observed-this-species = Bu türü gözlemlemiş olabilirsiniz
You-may-notice-changes-to-how-things-look-and-flow = İşlerin görünümünde ve akışında değişiklikler olduğunu fark edebilirsiniz. Seçeneklerinizi ayarlardan kontrol edebilirsiniz.
You-must-install-Google-Play-Services-to-sign-in-with-Google = Google ile oturum açmak için Google Play Hizmetleri'ni yüklemeniz gerekir.
You-need-an-Internet-connection-to-do-that = Bunu yapmak için bir internet bağlantısına ihtiyacınız var.
You-need-log-in-to-do-that = Bunu yapabilmek için oturum açmanız gerekir.
You-observed-a-species-in-this-group = Bu grupta bir tür gözlemlediniz
You-observed-this-species = Bu türü gözlemlediniz
You-will-see-notifications = Giriş yaptıktan ve gözlemleri yükledikten sonra burada bildirimler göreceksiniz.
Your-donation-to-iNaturalist = iNaturalist'e yapacağınız bağış, milyonlarca insanı doğaya bağlayan ve dünya çapında biyolojik çeşitliliğin korunmasını sağlayan mobil uygulamaların ve web sitesinin geliştirilmesini ve istikrarını destekler!
Your-email-is-confirmed = E-postanız onaylandı! Devam etmek için lütfen giriş yapın.
Your-location-uncertainty-is-over-x-km = Konum belirsizliğiniz { $x } km'nin üzerinde, bu da tanımlayıcılara yardımcı olmak için çok yüksek. Konumu düzenleyin ve doğruluk dairesi yeşile dönene ve organizmayı gözlemlediğiniz yerin ortasına gelene kadar yakınlaştırın.
Your-observations-can-help-science = Gözlemleriniz bilime yardımcı olabilir!
Youre-ready-to-share-your-observations = Gözlemlerinizi paylaşmaya hazırsınız!
Youve-denied-permission-prompt = İzniniz reddedildi. Lütfen ayarlar uygulamasından izin verin.
Youve-previously-denied-camera-permissions = Daha önce kamera izinlerini reddetmiştiniz, bu nedenle lütfen ayarlardan etkinleştirin.
Youve-previously-denied-location-permissions = Daha önce konum izinlerini reddetmiştiniz, bu nedenle lütfen ayarlardan etkinleştirin.
Youve-previously-denied-microphone-permissions = Daha önce mikrofon izinlerini reddetmiştiniz, bu nedenle lütfen ayarlardan etkinleştirin.
Zoom-in-as-much-as-possible-to-improve = Konum doğruluğunu artırmak ve daha iyi tanımlamalar elde etmek için mümkün olduğunca yakınlaştırın.
Zoom-to-current-location = Mevcut konuma yakınlaştır
zoom-x = { $zoom }x
