# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Distributes iNaturalistReactNative Android bundle to the Play Store internal track"
  lane :internal do
    gradle(task: "bundle", build_type: "Release")
    upload_to_play_store(
      track: "internal",
      release_status: "draft",
      package_name: ENV["PACKAGE_NAME"],
      skip_upload_apk: true
    )
    slack(
     message: "iNaturalistReactNative Android internal build successfully deployed!",
     success: true,
     slack_url: ENV["SLACK_WEBHOOK"],
     default_payloads: [:lane, :test_result, :git_branch, :last_git_commit_hash],
     attachment_properties: {
          fields: [
              {
                 title: "Version",
                 value: android_get_version_name(gradle_file: "app/build.gradle")
              },
              {
                title: "Build",
                value: android_get_version_code(gradle_file: "app/build.gradle")
              }
          ]
      })
  end
end
